// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "it",
        "default",
        "X e acceso. → X e acceso.
X e spento. → X e spento.
La temperatura Y. → La temperatura Y.",
    ),
    (
        "it",
        "butler",
        "X e acceso. → Molto bene. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Molto bene. La temperatura Y.",
    ),
    (
        "it",
        "locker",
        "X e acceso. → Fatto. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Fatto. La temperatura Y.",
    ),
    (
        "it",
        "fuersorglich",
        "X e acceso. → Subito. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Subito. La temperatura Y.",
    ),
    (
        "it",
        "party",
        "X e acceso. → Andiamo. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Andiamo. La temperatura Y.",
    ),
    (
        "it",
        "grantig",
        "X e acceso. → Va be'. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Va be'. La temperatura Y.",
    ),
    (
        "it",
        "sarkastisch",
        "X e acceso. → Certo. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Certo. La temperatura Y.",
    ),
    (
        "it",
        "pirat",
        "X e acceso. → Aye. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Aye. La temperatura Y.",
    ),
    (
        "it",
        "hippie",
        "X e acceso. → Easy. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Easy. La temperatura Y.",
    ),
    (
        "it",
        "gollum",
        "X e acceso. → Si. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Si. La temperatura Y.",
    ),
    (
        "it",
        "jarvis",
        "X e acceso. → Of course, sir. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Of course, sir. La temperatura Y.",
    ),
    (
        "sv",
        "default",
        "X är på. → X är på.
X är av. → X är av.
Temperaturen Y. → Temperaturen Y.",
    ),
    (
        "sv",
        "butler",
        "X är på. → Mycket väl. X är på.
X är av. → X är av.
Temperaturen Y. → Mycket väl. Temperaturen Y.",
    ),
    (
        "sv",
        "locker",
        "X är på. → Okej. X är på.
X är av. → X är av.
Temperaturen Y. → Okej. Temperaturen Y.",
    ),
    (
        "sv",
        "fuersorglich",
        "X är på. → Gör det genast. X är på.
X är av. → X är av.
Temperaturen Y. → Gör det genast. Temperaturen Y.",
    ),
    (
        "sv",
        "party",
        "X är på. → Nu kör vi. X är på.
X är av. → X är av.
Temperaturen Y. → Nu kör vi. Temperaturen Y.",
    ),
    (
        "sv",
        "grantig",
        "X är på. → Nåväl. X är på.
X är av. → X är av.
Temperaturen Y. → Nåväl. Temperaturen Y.",
    ),
    (
        "sv",
        "sarkastisch",
        "X är på. → Javisst. X är på.
X är av. → X är av.
Temperaturen Y. → Javisst. Temperaturen Y.",
    ),
    (
        "sv",
        "pirat",
        "X är på. → Aye. X är på.
X är av. → X är av.
Temperaturen Y. → Aye. Temperaturen Y.",
    ),
    (
        "sv",
        "hippie",
        "X är på. → Lugnt. X är på.
X är av. → X är av.
Temperaturen Y. → Lugnt. Temperaturen Y.",
    ),
    (
        "sv",
        "gollum",
        "X är på. → Ja. X är på.
X är av. → X är av.
Temperaturen Y. → Ja. Temperaturen Y.",
    ),
    (
        "sv",
        "jarvis",
        "X är på. → Of course, sir. X är på.
X är av. → X är av.
Temperaturen Y. → Of course, sir. Temperaturen Y.",
    ),
    (
        "af",
        "default",
        "X is aan. → X is aan.
X is af. → X is af.
Die temperatuur Y. → Die temperatuur Y.",
    ),
    (
        "af",
        "butler",
        "X is aan. → Baie goed. X is aan.
X is af. → X is af.
Die temperatuur Y. → Baie goed. Die temperatuur Y.",
    ),
    (
        "af",
        "locker",
        "X is aan. → Reg. X is aan.
X is af. → X is af.
Die temperatuur Y. → Reg. Die temperatuur Y.",
    ),
    (
        "af",
        "fuersorglich",
        "X is aan. → Ek doen dit nou. X is aan.
X is af. → X is af.
Die temperatuur Y. → Ek doen dit nou. Die temperatuur Y.",
    ),
    (
        "af",
        "party",
        "X is aan. → Kom ons gaan. X is aan.
X is af. → X is af.
Die temperatuur Y. → Kom ons gaan. Die temperatuur Y.",
    ),
    (
        "af",
        "grantig",
        "X is aan. → Goed. X is aan.
X is af. → X is af.
Die temperatuur Y. → Goed. Die temperatuur Y.",
    ),
    (
        "af",
        "sarkastisch",
        "X is aan. → Natuurlik. X is aan.
X is af. → X is af.
Die temperatuur Y. → Natuurlik. Die temperatuur Y.",
    ),
    (
        "af",
        "pirat",
        "X is aan. → Aye. X is aan.
X is af. → X is af.
Die temperatuur Y. → Aye. Die temperatuur Y.",
    ),
    (
        "af",
        "hippie",
        "X is aan. → Easy. X is aan.
X is af. → X is af.
Die temperatuur Y. → Easy. Die temperatuur Y.",
    ),
    (
        "af",
        "gollum",
        "X is aan. → Ja. X is aan.
X is af. → X is af.
Die temperatuur Y. → Ja. Die temperatuur Y.",
    ),
    (
        "af",
        "jarvis",
        "X is aan. → Of course, sir. X is aan.
X is af. → X is af.
Die temperatuur Y. → Of course, sir. Die temperatuur Y.",
    ),
    (
        "sl",
        "default",
        "X je prizgan. → X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "sl",
        "butler",
        "X je prizgan. → Zelo dobro. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Zelo dobro. Temperatura Y.",
    ),
    (
        "sl",
        "locker",
        "X je prizgan. → V redu. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → V redu. Temperatura Y.",
    ),
    (
        "sl",
        "fuersorglich",
        "X je prizgan. → Naredim takoj. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Naredim takoj. Temperatura Y.",
    ),
    (
        "sl",
        "party",
        "X je prizgan. → Gremo. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Gremo. Temperatura Y.",
    ),
    (
        "sl",
        "grantig",
        "X je prizgan. → No dobro. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → No dobro. Temperatura Y.",
    ),
    (
        "sl",
        "sarkastisch",
        "X je prizgan. → Seveda. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Seveda. Temperatura Y.",
    ),
    (
        "sl",
        "pirat",
        "X je prizgan. → Aye. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "sl",
        "hippie",
        "X je prizgan. → Sproščeno. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Sproščeno. Temperatura Y.",
    ),
    (
        "sl",
        "gollum",
        "X je prizgan. → Da. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Da. Temperatura Y.",
    ),
    (
        "sl",
        "jarvis",
        "X je prizgan. → Of course, sir. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Of course, sir. Temperatura Y.",
    ),
    (
        "zh-CN",
        "default",
        "X开了。 → X开了。
X关了。 → X关了。
温度Y。 → 温度Y。",
    ),
    (
        "zh-CN",
        "butler",
        "X开了。 → 好的。 X开了。
X关了。 → X关了。
温度Y。 → 好的。 温度Y。",
    ),
    (
        "zh-CN",
        "locker",
        "X开了。 → 行。 X开了。
X关了。 → X关了。
温度Y。 → 行。 温度Y。",
    ),
    (
        "zh-CN",
        "fuersorglich",
        "X开了。 → 马上就做。 X开了。
X关了。 → X关了。
温度Y。 → 马上就做。 温度Y。",
    ),
    (
        "zh-CN",
        "party",
        "X开了。 → 走起。 X开了。
X关了。 → X关了。
温度Y。 → 走起。 温度Y。",
    ),
    (
        "zh-CN",
        "grantig",
        "X开了。 → 行吧。 X开了。
X关了。 → X关了。
温度Y。 → 行吧。 温度Y。",
    ),
    (
        "zh-CN",
        "sarkastisch",
        "X开了。 → 当然。 X开了。
X关了。 → X关了。
温度Y。 → 当然。 温度Y。",
    ),
    (
        "zh-CN",
        "pirat",
        "X开了。 → Aye. X开了。
X关了。 → X关了。
温度Y。 → Aye. 温度Y。",
    ),
    (
        "zh-CN",
        "hippie",
        "X开了。 → 放松。 X开了。
X关了。 → X关了。
温度Y。 → 放松。 温度Y。",
    ),
    (
        "zh-CN",
        "gollum",
        "X开了。 → 是。 X开了。
X关了。 → X关了。
温度Y。 → 是。 温度Y。",
    ),
    (
        "zh-CN",
        "jarvis",
        "X开了。 → Of course, sir. X开了。
X关了。 → X关了。
温度Y。 → Of course, sir. 温度Y。",
    ),
    (
        "ur",
        "default",
        "X چالو ہے۔ → X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → درجہ حرارت Y۔",
    ),
    (
        "ur",
        "butler",
        "X چالو ہے۔ → ٹھیک ہے۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ٹھیک ہے۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "locker",
        "X چالو ہے۔ → سمجھ گیا۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → سمجھ گیا۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "fuersorglich",
        "X چالو ہے۔ → ابھی کرتا ہوں۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ابھی کرتا ہوں۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "party",
        "X چالو ہے۔ → چلو۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → چلو۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "grantig",
        "X چالو ہے۔ → ہاں جی۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ہاں جی۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "sarkastisch",
        "X چالو ہے۔ → یقینا۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → یقینا۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "pirat",
        "X چالو ہے۔ → Aye. X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → Aye. درجہ حرارت Y۔",
    ),
    (
        "ur",
        "hippie",
        "X چالو ہے۔ → آرام سے۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → آرام سے۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "gollum",
        "X چالو ہے۔ → ہاں۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ہاں۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "jarvis",
        "X چالو ہے۔ → Of course, sir. X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → Of course, sir. درجہ حرارت Y۔",
    ),
    (
        "et",
        "default",
        "X on sees. → X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Temperatuur Y.",
    ),
    (
        "et",
        "butler",
        "X on sees. → Hasti. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Hasti. Temperatuur Y.",
    ),
    (
        "et",
        "locker",
        "X on sees. → Selge. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Selge. Temperatuur Y.",
    ),
    (
        "et",
        "fuersorglich",
        "X on sees. → Teen kohe. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Teen kohe. Temperatuur Y.",
    ),
    (
        "et",
        "party",
        "X on sees. → Laks. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Laks. Temperatuur Y.",
    ),
    (
        "et",
        "grantig",
        "X on sees. → Olgu. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Olgu. Temperatuur Y.",
    ),
    (
        "et",
        "sarkastisch",
        "X on sees. → Muidugi. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Muidugi. Temperatuur Y.",
    ),
    (
        "et",
        "pirat",
        "X on sees. → Aye. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Aye. Temperatuur Y.",
    ),
    (
        "et",
        "hippie",
        "X on sees. → Rahulikult. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Rahulikult. Temperatuur Y.",
    ),
    (
        "et",
        "gollum",
        "X on sees. → Jah. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Jah. Temperatuur Y.",
    ),
    (
        "et",
        "jarvis",
        "X on sees. → Of course, sir. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Of course, sir. Temperatuur Y.",
    ),
    (
        "kw",
        "default",
        "X yw enowys. → X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → An tempredh Y.",
    ),
    (
        "kw",
        "butler",
        "X yw enowys. → Da lowr. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Da lowr. An tempredh Y.",
    ),
    (
        "kw",
        "locker",
        "X yw enowys. → Komprenys. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Komprenys. An tempredh Y.",
    ),
    (
        "kw",
        "fuersorglich",
        "X yw enowys. → Y hwrav henna lemmyn. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Y hwrav henna lemmyn. An tempredh Y.",
    ),
    (
        "kw",
        "party",
        "X yw enowys. → Deun yn-rag. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Deun yn-rag. An tempredh Y.",
    ),
    (
        "kw",
        "grantig",
        "X yw enowys. → Da. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Da. An tempredh Y.",
    ),
    (
        "kw",
        "sarkastisch",
        "X yw enowys. → Yn sur. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Yn sur. An tempredh Y.",
    ),
    (
        "kw",
        "pirat",
        "X yw enowys. → Aye. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Aye. An tempredh Y.",
    ),
    (
        "kw",
        "hippie",
        "X yw enowys. → Esbos. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Esbos. An tempredh Y.",
    ),
    (
        "kw",
        "gollum",
        "X yw enowys. → Ya. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Ya. An tempredh Y.",
    ),
    (
        "kw",
        "jarvis",
        "X yw enowys. → Of course, sir. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Of course, sir. An tempredh Y.",
    ),
    (
        "vi",
        "default",
        "X dang bat. → X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Nhiet do Y.",
    ),
    (
        "vi",
        "butler",
        "X dang bat. → Tot. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Tot. Nhiet do Y.",
    ),
    (
        "vi",
        "locker",
        "X dang bat. → Hieu. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Hieu. Nhiet do Y.",
    ),
    (
        "vi",
        "fuersorglich",
        "X dang bat. → Toi lam ngay. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Toi lam ngay. Nhiet do Y.",
    ),
    (
        "vi",
        "party",
        "X dang bat. → Di nao. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Di nao. Nhiet do Y.",
    ),
    (
        "vi",
        "grantig",
        "X dang bat. → Thoi duoc. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Thoi duoc. Nhiet do Y.",
    ),
    (
        "vi",
        "sarkastisch",
        "X dang bat. → Duong nhien. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Duong nhien. Nhiet do Y.",
    ),
    (
        "vi",
        "pirat",
        "X dang bat. → Aye. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Aye. Nhiet do Y.",
    ),
    (
        "vi",
        "hippie",
        "X dang bat. → De. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → De. Nhiet do Y.",
    ),
    (
        "vi",
        "gollum",
        "X dang bat. → Co. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Co. Nhiet do Y.",
    ),
    (
        "vi",
        "jarvis",
        "X dang bat. → Of course, sir. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Of course, sir. Nhiet do Y.",
    ),
    (
        "mr",
        "default",
        "X चालू आहे। → X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Tapman Y.",
    ),
    (
        "mr",
        "butler",
        "X चालू आहे। → Theek. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Theek. Tapman Y.",
    ),
    (
        "mr",
        "locker",
        "X चालू आहे। → Kalale. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Kalale. Tapman Y.",
    ),
    (
        "mr",
        "fuersorglich",
        "X चालू आहे। → Aata karto. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Aata karto. Tapman Y.",
    ),
    (
        "mr",
        "party",
        "X चालू आहे। → Chala. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Chala. Tapman Y.",
    ),
    (
        "mr",
        "grantig",
        "X चालू आहे। → Theek aahe. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Theek aahe. Tapman Y.",
    ),
    (
        "mr",
        "sarkastisch",
        "X चालू आहे। → Nakkich. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Nakkich. Tapman Y.",
    ),
    (
        "mr",
        "pirat",
        "X चालू आहे। → Aye. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Aye. Tapman Y.",
    ),
    (
        "mr",
        "hippie",
        "X चालू आहे। → Shant. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Shant. Tapman Y.",
    ),
    (
        "mr",
        "gollum",
        "X चालू आहे। → Ho. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Ho. Tapman Y.",
    ),
    (
        "mr",
        "jarvis",
        "X चालू आहे। → Of course, sir. X चालू आहे।
X बंद आहे। → X बंद आहे।
Tapman Y. → Of course, sir. Tapman Y.",
    ),
    (
        "ka",
        "default",
        "X ჩართულია. → X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "ka",
        "butler",
        "X ჩართულია. → Kargi. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Kargi. Temperatura Y.",
    ),
    (
        "ka",
        "locker",
        "X ჩართულია. → Gavige. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Gavige. Temperatura Y.",
    ),
    (
        "ka",
        "fuersorglich",
        "X ჩართულია. → Ekhla vaketeb. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Ekhla vaketeb. Temperatura Y.",
    ),
    (
        "ka",
        "party",
        "X ჩართულია. → Tsavidet. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Tsavidet. Temperatura Y.",
    ),
    (
        "ka",
        "grantig",
        "X ჩართულია. → Kargi. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Kargi. Temperatura Y.",
    ),
    (
        "ka",
        "sarkastisch",
        "X ჩართულია. → Rataqmaunda. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Rataqmaunda. Temperatura Y.",
    ),
    (
        "ka",
        "pirat",
        "X ჩართულია. → Aye. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "ka",
        "hippie",
        "X ჩართულია. → Mshvidad. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Mshvidad. Temperatura Y.",
    ),
    (
        "ka",
        "gollum",
        "X ჩართულია. → Ki. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Ki. Temperatura Y.",
    ),
    (
        "ka",
        "jarvis",
        "X ჩართულია. → Of course, sir. X ჩართულია.
X გამორთულია. → X გამორთულია.
Temperatura Y. → Of course, sir. Temperatura Y.",
    ),
];
