// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "es",
        "default",
        "X esta encendido. → X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → La temperatura Y.",
    ),
    (
        "es",
        "butler",
        "X esta encendido. → Muy bien. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Muy bien. La temperatura Y.",
    ),
    (
        "es",
        "locker",
        "X esta encendido. → Hecho. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Hecho. La temperatura Y.",
    ),
    (
        "es",
        "fuersorglich",
        "X esta encendido. → Ahora mismo. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Ahora mismo. La temperatura Y.",
    ),
    (
        "es",
        "party",
        "X esta encendido. → Vamos. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Vamos. La temperatura Y.",
    ),
    (
        "es",
        "grantig",
        "X esta encendido. → Bueno. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Bueno. La temperatura Y.",
    ),
    (
        "es",
        "sarkastisch",
        "X esta encendido. → Claro. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Claro. La temperatura Y.",
    ),
    (
        "es",
        "pirat",
        "X esta encendido. → Aye. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Aye. La temperatura Y.",
    ),
    (
        "es",
        "hippie",
        "X esta encendido. → Tranqui. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Tranqui. La temperatura Y.",
    ),
    (
        "es",
        "gollum",
        "X esta encendido. → Si. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Si. La temperatura Y.",
    ),
    (
        "es",
        "jarvis",
        "X esta encendido. → Of course, sir. X esta encendido.
X esta apagado. → X esta apagado.
La temperatura Y. → Of course, sir. La temperatura Y.",
    ),
    (
        "nb",
        "default",
        "X er pa. → X er pa.
X er av. → X er av.
Temperaturen Y. → Temperaturen Y.",
    ),
    (
        "nb",
        "butler",
        "X er pa. → Godt. X er pa.
X er av. → X er av.
Temperaturen Y. → Godt. Temperaturen Y.",
    ),
    (
        "nb",
        "locker",
        "X er pa. → Greit. X er pa.
X er av. → X er av.
Temperaturen Y. → Greit. Temperaturen Y.",
    ),
    (
        "nb",
        "fuersorglich",
        "X er pa. → Gjor det med en gang. X er pa.
X er av. → X er av.
Temperaturen Y. → Gjor det med en gang. Temperaturen Y.",
    ),
    (
        "nb",
        "party",
        "X er pa. → Da kjorer vi. X er pa.
X er av. → X er av.
Temperaturen Y. → Da kjorer vi. Temperaturen Y.",
    ),
    (
        "nb",
        "grantig",
        "X er pa. → Na vel. X er pa.
X er av. → X er av.
Temperaturen Y. → Na vel. Temperaturen Y.",
    ),
    (
        "nb",
        "sarkastisch",
        "X er pa. → Selvsagt. X er pa.
X er av. → X er av.
Temperaturen Y. → Selvsagt. Temperaturen Y.",
    ),
    (
        "nb",
        "pirat",
        "X er pa. → Aye. X er pa.
X er av. → X er av.
Temperaturen Y. → Aye. Temperaturen Y.",
    ),
    (
        "nb",
        "hippie",
        "X er pa. → Chill. X er pa.
X er av. → X er av.
Temperaturen Y. → Chill. Temperaturen Y.",
    ),
    (
        "nb",
        "gollum",
        "X er pa. → Ja. X er pa.
X er av. → X er av.
Temperaturen Y. → Ja. Temperaturen Y.",
    ),
    (
        "nb",
        "jarvis",
        "X er pa. → Of course, sir. X er pa.
X er av. → X er av.
Temperaturen Y. → Of course, sir. Temperaturen Y.",
    ),
    (
        "pt-BR",
        "default",
        "X esta ligado. → X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → A temperatura Y.",
    ),
    (
        "pt-BR",
        "butler",
        "X esta ligado. → Muito bem. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Muito bem. A temperatura Y.",
    ),
    (
        "pt-BR",
        "locker",
        "X esta ligado. → Feito. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Feito. A temperatura Y.",
    ),
    (
        "pt-BR",
        "fuersorglich",
        "X esta ligado. → Ja faco. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Ja faco. A temperatura Y.",
    ),
    (
        "pt-BR",
        "party",
        "X esta ligado. → Bora. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Bora. A temperatura Y.",
    ),
    (
        "pt-BR",
        "grantig",
        "X esta ligado. → Tudo bem. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Tudo bem. A temperatura Y.",
    ),
    (
        "pt-BR",
        "sarkastisch",
        "X esta ligado. → Claro. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Claro. A temperatura Y.",
    ),
    (
        "pt-BR",
        "pirat",
        "X esta ligado. → Aye. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Aye. A temperatura Y.",
    ),
    (
        "pt-BR",
        "hippie",
        "X esta ligado. → De boa. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → De boa. A temperatura Y.",
    ),
    (
        "pt-BR",
        "gollum",
        "X esta ligado. → Sim. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Sim. A temperatura Y.",
    ),
    (
        "pt-BR",
        "jarvis",
        "X esta ligado. → Of course, sir. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Of course, sir. A temperatura Y.",
    ),
    (
        "hr",
        "default",
        "X je upaljen. → X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "hr",
        "butler",
        "X je upaljen. → Vrlo dobro. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Vrlo dobro. Temperatura Y.",
    ),
    (
        "hr",
        "locker",
        "X je upaljen. → U redu. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → U redu. Temperatura Y.",
    ),
    (
        "hr",
        "fuersorglich",
        "X je upaljen. → Odmah to radim. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Odmah to radim. Temperatura Y.",
    ),
    (
        "hr",
        "party",
        "X je upaljen. → Idemo. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Idemo. Temperatura Y.",
    ),
    (
        "hr",
        "grantig",
        "X je upaljen. → Dobro. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Dobro. Temperatura Y.",
    ),
    (
        "hr",
        "sarkastisch",
        "X je upaljen. → Naravno. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Naravno. Temperatura Y.",
    ),
    (
        "hr",
        "pirat",
        "X je upaljen. → Aye. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "hr",
        "hippie",
        "X je upaljen. → Opusteno. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Opusteno. Temperatura Y.",
    ),
    (
        "hr",
        "gollum",
        "X je upaljen. → Da. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Da. Temperatura Y.",
    ),
    (
        "hr",
        "jarvis",
        "X je upaljen. → Of course, sir. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Of course, sir. Temperatura Y.",
    ),
    (
        "uk",
        "default",
        "X увімкнено. → X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Температура Y.",
    ),
    (
        "uk",
        "butler",
        "X увімкнено. → Дуже добре. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Дуже добре. Температура Y.",
    ),
    (
        "uk",
        "locker",
        "X увімкнено. → Гаразд. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Гаразд. Температура Y.",
    ),
    (
        "uk",
        "fuersorglich",
        "X увімкнено. → Зроблю зараз. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Зроблю зараз. Температура Y.",
    ),
    (
        "uk",
        "party",
        "X увімкнено. → Ходімо. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Ходімо. Температура Y.",
    ),
    (
        "uk",
        "grantig",
        "X увімкнено. → Ну добре. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Ну добре. Температура Y.",
    ),
    (
        "uk",
        "sarkastisch",
        "X увімкнено. → Звісно. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Звісно. Температура Y.",
    ),
    (
        "uk",
        "pirat",
        "X увімкнено. → Aye. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Aye. Температура Y.",
    ),
    (
        "uk",
        "hippie",
        "X увімкнено. → Спокійно. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Спокійно. Температура Y.",
    ),
    (
        "uk",
        "gollum",
        "X увімкнено. → Так. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Так. Температура Y.",
    ),
    (
        "uk",
        "jarvis",
        "X увімкнено. → Of course, sir. X увімкнено.
X вимкнено. → X вимкнено.
Температура Y. → Of course, sir. Температура Y.",
    ),
    (
        "fa",
        "default",
        "X روشن است. → X روشن است.
X خاموش است. → X خاموش است.
دما Y. → دما Y.",
    ),
    (
        "fa",
        "butler",
        "X روشن است. → باشه. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → باشه. دما Y.",
    ),
    (
        "fa",
        "locker",
        "X روشن است. → فهمیدم. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → فهمیدم. دما Y.",
    ),
    (
        "fa",
        "fuersorglich",
        "X روشن است. → الان انجام میدهم. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → الان انجام میدهم. دما Y.",
    ),
    (
        "fa",
        "party",
        "X روشن است. → بزن بریم. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → بزن بریم. دما Y.",
    ),
    (
        "fa",
        "grantig",
        "X روشن است. → خب. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → خب. دما Y.",
    ),
    (
        "fa",
        "sarkastisch",
        "X روشن است. → البته. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → البته. دما Y.",
    ),
    (
        "fa",
        "pirat",
        "X روشن است. → Aye. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → Aye. دما Y.",
    ),
    (
        "fa",
        "hippie",
        "X روشن است. → آروم. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → آروم. دما Y.",
    ),
    (
        "fa",
        "gollum",
        "X روشن است. → بله. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → بله. دما Y.",
    ),
    (
        "fa",
        "jarvis",
        "X روشن است. → Of course, sir. X روشن است.
X خاموش است. → X خاموش است.
دما Y. → Of course, sir. دما Y.",
    ),
    (
        "cy",
        "default",
        "X yn ymlaen. → X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Y tymheredd Y.",
    ),
    (
        "cy",
        "butler",
        "X yn ymlaen. → Iawn. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Iawn. Y tymheredd Y.",
    ),
    (
        "cy",
        "locker",
        "X yn ymlaen. → Wedi dal. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Wedi dal. Y tymheredd Y.",
    ),
    (
        "cy",
        "fuersorglich",
        "X yn ymlaen. → Gwnaf hynny nawr. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Gwnaf hynny nawr. Y tymheredd Y.",
    ),
    (
        "cy",
        "party",
        "X yn ymlaen. → Ymlaen a ni. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Ymlaen a ni. Y tymheredd Y.",
    ),
    (
        "cy",
        "grantig",
        "X yn ymlaen. → Iawn te. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Iawn te. Y tymheredd Y.",
    ),
    (
        "cy",
        "sarkastisch",
        "X yn ymlaen. → Wrth gwrs. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Wrth gwrs. Y tymheredd Y.",
    ),
    (
        "cy",
        "pirat",
        "X yn ymlaen. → Aye. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Aye. Y tymheredd Y.",
    ),
    (
        "cy",
        "hippie",
        "X yn ymlaen. → Hawdd. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Hawdd. Y tymheredd Y.",
    ),
    (
        "cy",
        "gollum",
        "X yn ymlaen. → Ie. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Ie. Y tymheredd Y.",
    ),
    (
        "cy",
        "jarvis",
        "X yn ymlaen. → Of course, sir. X yn ymlaen.
X yn diffodd. → X yn diffodd.
Y tymheredd Y. → Of course, sir. Y tymheredd Y.",
    ),
    (
        "lb",
        "default",
        "X ass un. → X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → D Temperatur Y.",
    ),
    (
        "lb",
        "butler",
        "X ass un. → Ganz gutt. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Ganz gutt. D Temperatur Y.",
    ),
    (
        "lb",
        "locker",
        "X ass un. → Geet. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Geet. D Temperatur Y.",
    ),
    (
        "lb",
        "fuersorglich",
        "X ass un. → Machen ech direkt. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Machen ech direkt. D Temperatur Y.",
    ),
    (
        "lb",
        "party",
        "X ass un. → Loosst eis. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Loosst eis. D Temperatur Y.",
    ),
    (
        "lb",
        "grantig",
        "X ass un. → Schon gutt. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Schon gutt. D Temperatur Y.",
    ),
    (
        "lb",
        "sarkastisch",
        "X ass un. → Natierlech. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Natierlech. D Temperatur Y.",
    ),
    (
        "lb",
        "pirat",
        "X ass un. → Aye. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Aye. D Temperatur Y.",
    ),
    (
        "lb",
        "hippie",
        "X ass un. → Easy. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Easy. D Temperatur Y.",
    ),
    (
        "lb",
        "gollum",
        "X ass un. → Jo. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Jo. D Temperatur Y.",
    ),
    (
        "lb",
        "jarvis",
        "X ass un. → Of course, sir. X ass un.
X ass aus. → X ass aus.
D Temperatur Y. → Of course, sir. D Temperatur Y.",
    ),
    (
        "sw",
        "default",
        "X imewashwa. → X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Joto Y.",
    ),
    (
        "sw",
        "butler",
        "X imewashwa. → Vizuri. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Vizuri. Joto Y.",
    ),
    (
        "sw",
        "locker",
        "X imewashwa. → Sawa. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Sawa. Joto Y.",
    ),
    (
        "sw",
        "fuersorglich",
        "X imewashwa. → Nafanya sasa. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Nafanya sasa. Joto Y.",
    ),
    (
        "sw",
        "party",
        "X imewashwa. → Twende. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Twende. Joto Y.",
    ),
    (
        "sw",
        "grantig",
        "X imewashwa. → Sawa basi. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Sawa basi. Joto Y.",
    ),
    (
        "sw",
        "sarkastisch",
        "X imewashwa. → Bila shaka. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Bila shaka. Joto Y.",
    ),
    (
        "sw",
        "pirat",
        "X imewashwa. → Aye. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Aye. Joto Y.",
    ),
    (
        "sw",
        "hippie",
        "X imewashwa. → Poa. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Poa. Joto Y.",
    ),
    (
        "sw",
        "gollum",
        "X imewashwa. → Ndiyo. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Ndiyo. Joto Y.",
    ),
    (
        "sw",
        "jarvis",
        "X imewashwa. → Of course, sir. X imewashwa.
X imezimwa. → X imezimwa.
Joto Y. → Of course, sir. Joto Y.",
    ),
    (
        "ml",
        "default",
        "X തെളിഞ്ഞു. → X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Temperature Y.",
    ),
    (
        "ml",
        "butler",
        "X തെളിഞ്ഞു. → Nannayi. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Nannayi. Temperature Y.",
    ),
    (
        "ml",
        "locker",
        "X തെളിഞ്ഞു. → Manasilayi. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Manasilayi. Temperature Y.",
    ),
    (
        "ml",
        "fuersorglich",
        "X തെളിഞ്ഞു. → Ippol cheyyunnu. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Ippol cheyyunnu. Temperature Y.",
    ),
    (
        "ml",
        "party",
        "X തെളിഞ്ഞു. → Pokaam. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Pokaam. Temperature Y.",
    ),
    (
        "ml",
        "grantig",
        "X തെളിഞ്ഞു. → Sheri. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Sheri. Temperature Y.",
    ),
    (
        "ml",
        "sarkastisch",
        "X തെളിഞ്ഞു. → Theerchayayi. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Theerchayayi. Temperature Y.",
    ),
    (
        "ml",
        "pirat",
        "X തെളിഞ്ഞു. → Aye. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Aye. Temperature Y.",
    ),
    (
        "ml",
        "hippie",
        "X തെളിഞ്ഞു. → Shaantam. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Shaantam. Temperature Y.",
    ),
    (
        "ml",
        "gollum",
        "X തെളിഞ്ഞു. → Athe. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Athe. Temperature Y.",
    ),
    (
        "ml",
        "jarvis",
        "X തെളിഞ്ഞു. → Of course, sir. X തെളിഞ്ഞു.
X അണഞ്ഞു. → X അണഞ്ഞു.
Temperature Y. → Of course, sir. Temperature Y.",
    ),
    (
        "hy",
        "default",
        "X միացված է։ → X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Jermastichane Y.",
    ),
    (
        "hy",
        "butler",
        "X միացված է։ → Lav. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Lav. Jermastichane Y.",
    ),
    (
        "hy",
        "locker",
        "X միացված է։ → Hasatsa. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Hasatsa. Jermastichane Y.",
    ),
    (
        "hy",
        "fuersorglich",
        "X միացված է։ → Hima k anem. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Hima k anem. Jermastichane Y.",
    ),
    (
        "hy",
        "party",
        "X միացված է։ → Gnanq. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Gnanq. Jermastichane Y.",
    ),
    (
        "hy",
        "grantig",
        "X միացված է։ → Lav. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Lav. Jermastichane Y.",
    ),
    (
        "hy",
        "sarkastisch",
        "X միացված է։ → Ihayt. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Ihayt. Jermastichane Y.",
    ),
    (
        "hy",
        "pirat",
        "X միացված է։ → Aye. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Aye. Jermastichane Y.",
    ),
    (
        "hy",
        "hippie",
        "X միացված է։ → Hangelist. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Hangelist. Jermastichane Y.",
    ),
    (
        "hy",
        "gollum",
        "X միացված է։ → Ayo. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Ayo. Jermastichane Y.",
    ),
    (
        "hy",
        "jarvis",
        "X միացված է։ → Of course, sir. X միացված է։
X անջատված է։ → X անջատված է։
Jermastichane Y. → Of course, sir. Jermastichane Y.",
    ),
];
