// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "pt",
        "default",
        "X esta ligado. → X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → A temperatura Y.",
    ),
    (
        "pt",
        "butler",
        "X esta ligado. → Muito bem. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Muito bem. A temperatura Y.",
    ),
    (
        "pt",
        "locker",
        "X esta ligado. → Feito. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Feito. A temperatura Y.",
    ),
    (
        "pt",
        "fuersorglich",
        "X esta ligado. → Ja faco. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Ja faco. A temperatura Y.",
    ),
    (
        "pt",
        "party",
        "X esta ligado. → Vamos. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Vamos. A temperatura Y.",
    ),
    (
        "pt",
        "grantig",
        "X esta ligado. → Pronto. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Pronto. A temperatura Y.",
    ),
    (
        "pt",
        "sarkastisch",
        "X esta ligado. → Claro. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Claro. A temperatura Y.",
    ),
    (
        "pt",
        "pirat",
        "X esta ligado. → Aye. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Aye. A temperatura Y.",
    ),
    (
        "pt",
        "hippie",
        "X esta ligado. → Easy. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Easy. A temperatura Y.",
    ),
    (
        "pt",
        "gollum",
        "X esta ligado. → Sim. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Sim. A temperatura Y.",
    ),
    (
        "pt",
        "jarvis",
        "X esta ligado. → Of course, sir. X esta ligado.
X esta desligado. → X esta desligado.
A temperatura Y. → Of course, sir. A temperatura Y.",
    ),
    (
        "fi",
        "default",
        "X on paalla. → X on paalla.
X on pois. → X on pois.
Lampotila Y. → Lampotila Y.",
    ),
    (
        "fi",
        "butler",
        "X on paalla. → Hyva on. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Hyva on. Lampotila Y.",
    ),
    (
        "fi",
        "locker",
        "X on paalla. → Okei. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Okei. Lampotila Y.",
    ),
    (
        "fi",
        "fuersorglich",
        "X on paalla. → Teen sen heti. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Teen sen heti. Lampotila Y.",
    ),
    (
        "fi",
        "party",
        "X on paalla. → Mennään. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Mennään. Lampotila Y.",
    ),
    (
        "fi",
        "grantig",
        "X on paalla. → No selva. X on paalla.
X on pois. → X on pois.
Lampotila Y. → No selva. Lampotila Y.",
    ),
    (
        "fi",
        "sarkastisch",
        "X on paalla. → Totta kai. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Totta kai. Lampotila Y.",
    ),
    (
        "fi",
        "pirat",
        "X on paalla. → Aye. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Aye. Lampotila Y.",
    ),
    (
        "fi",
        "hippie",
        "X on paalla. → Rennosti. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Rennosti. Lampotila Y.",
    ),
    (
        "fi",
        "gollum",
        "X on paalla. → Kylla. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Kylla. Lampotila Y.",
    ),
    (
        "fi",
        "jarvis",
        "X on paalla. → Of course, sir. X on paalla.
X on pois. → X on pois.
Lampotila Y. → Of course, sir. Lampotila Y.",
    ),
    (
        "cs",
        "default",
        "X je zapnute. → X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Teplota Y.",
    ),
    (
        "cs",
        "butler",
        "X je zapnute. → Velmi dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Velmi dobre. Teplota Y.",
    ),
    (
        "cs",
        "locker",
        "X je zapnute. → Jasne. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Jasne. Teplota Y.",
    ),
    (
        "cs",
        "fuersorglich",
        "X je zapnute. → Hned to udelam. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Hned to udelam. Teplota Y.",
    ),
    (
        "cs",
        "party",
        "X je zapnute. → Jedeme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Jedeme. Teplota Y.",
    ),
    (
        "cs",
        "grantig",
        "X je zapnute. → No dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → No dobre. Teplota Y.",
    ),
    (
        "cs",
        "sarkastisch",
        "X je zapnute. → Samozrejme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Samozrejme. Teplota Y.",
    ),
    (
        "cs",
        "pirat",
        "X je zapnute. → Aye. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Aye. Teplota Y.",
    ),
    (
        "cs",
        "hippie",
        "X je zapnute. → Pohoda. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Pohoda. Teplota Y.",
    ),
    (
        "cs",
        "gollum",
        "X je zapnute. → Ano. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Ano. Teplota Y.",
    ),
    (
        "cs",
        "jarvis",
        "X je zapnute. → Of course, sir. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Of course, sir. Teplota Y.",
    ),
    (
        "bg",
        "default",
        "X е включен. → X е включен.
X е изключен. → X е изключен.
Температурата Y. → Температурата Y.",
    ),
    (
        "bg",
        "butler",
        "X е включен. → Много добре. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Много добре. Температурата Y.",
    ),
    (
        "bg",
        "locker",
        "X е включен. → Ок. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Ок. Температурата Y.",
    ),
    (
        "bg",
        "fuersorglich",
        "X е включен. → Правя го веднага. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Правя го веднага. Температурата Y.",
    ),
    (
        "bg",
        "party",
        "X е включен. → Давай. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Давай. Температурата Y.",
    ),
    (
        "bg",
        "grantig",
        "X е включен. → Добре де. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Добре де. Температурата Y.",
    ),
    (
        "bg",
        "sarkastisch",
        "X е включен. → Разбира се. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Разбира се. Температурата Y.",
    ),
    (
        "bg",
        "pirat",
        "X е включен. → Aye. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Aye. Температурата Y.",
    ),
    (
        "bg",
        "hippie",
        "X е включен. → Спокойно. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Спокойно. Температурата Y.",
    ),
    (
        "bg",
        "gollum",
        "X е включен. → Да. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Да. Температурата Y.",
    ),
    (
        "bg",
        "jarvis",
        "X е включен. → Of course, sir. X е включен.
X е изключен. → X е изключен.
Температурата Y. → Of course, sir. Температурата Y.",
    ),
    (
        "zh-TW",
        "default",
        "X開了。 → X開了。
X關了。 → X關了。
溫度Y。 → 溫度Y。",
    ),
    (
        "zh-TW",
        "butler",
        "X開了。 → 好的。 X開了。
X關了。 → X關了。
溫度Y。 → 好的。 溫度Y。",
    ),
    (
        "zh-TW",
        "locker",
        "X開了。 → 行。 X開了。
X關了。 → X關了。
溫度Y。 → 行。 溫度Y。",
    ),
    (
        "zh-TW",
        "fuersorglich",
        "X開了。 → 馬上就做。 X開了。
X關了。 → X關了。
溫度Y。 → 馬上就做。 溫度Y。",
    ),
    (
        "zh-TW",
        "party",
        "X開了。 → 走起。 X開了。
X關了。 → X關了。
溫度Y。 → 走起。 溫度Y。",
    ),
    (
        "zh-TW",
        "grantig",
        "X開了。 → 行吧。 X開了。
X關了。 → X關了。
溫度Y。 → 行吧。 溫度Y。",
    ),
    (
        "zh-TW",
        "sarkastisch",
        "X開了。 → 當然。 X開了。
X關了。 → X關了。
溫度Y。 → 當然。 溫度Y。",
    ),
    (
        "zh-TW",
        "pirat",
        "X開了。 → Aye. X開了。
X關了。 → X關了。
溫度Y。 → Aye. 溫度Y。",
    ),
    (
        "zh-TW",
        "hippie",
        "X開了。 → 放鬆。 X開了。
X關了。 → X關了。
溫度Y。 → 放鬆。 溫度Y。",
    ),
    (
        "zh-TW",
        "gollum",
        "X開了。 → 是。 X開了。
X關了。 → X關了。
溫度Y。 → 是。 溫度Y。",
    ),
    (
        "zh-TW",
        "jarvis",
        "X開了。 → Of course, sir. X開了。
X關了。 → X關了。
溫度Y。 → Of course, sir. 溫度Y。",
    ),
    (
        "tr",
        "default",
        "X acik. → X acik.
X kapali. → X kapali.
Sicaklik Y. → Sicaklik Y.",
    ),
    (
        "tr",
        "butler",
        "X acik. → Peki. X acik.
X kapali. → X kapali.
Sicaklik Y. → Peki. Sicaklik Y.",
    ),
    (
        "tr",
        "locker",
        "X acik. → Tamam. X acik.
X kapali. → X kapali.
Sicaklik Y. → Tamam. Sicaklik Y.",
    ),
    (
        "tr",
        "fuersorglich",
        "X acik. → Hemen yapiyorum. X acik.
X kapali. → X kapali.
Sicaklik Y. → Hemen yapiyorum. Sicaklik Y.",
    ),
    (
        "tr",
        "party",
        "X acik. → Hadi. X acik.
X kapali. → X kapali.
Sicaklik Y. → Hadi. Sicaklik Y.",
    ),
    (
        "tr",
        "grantig",
        "X acik. → Peki o zaman. X acik.
X kapali. → X kapali.
Sicaklik Y. → Peki o zaman. Sicaklik Y.",
    ),
    (
        "tr",
        "sarkastisch",
        "X acik. → Tabii. X acik.
X kapali. → X kapali.
Sicaklik Y. → Tabii. Sicaklik Y.",
    ),
    (
        "tr",
        "pirat",
        "X acik. → Aye. X acik.
X kapali. → X kapali.
Sicaklik Y. → Aye. Sicaklik Y.",
    ),
    (
        "tr",
        "hippie",
        "X acik. → Rahat. X acik.
X kapali. → X kapali.
Sicaklik Y. → Rahat. Sicaklik Y.",
    ),
    (
        "tr",
        "gollum",
        "X acik. → Evet. X acik.
X kapali. → X kapali.
Sicaklik Y. → Evet. Sicaklik Y.",
    ),
    (
        "tr",
        "jarvis",
        "X acik. → Of course, sir. X acik.
X kapali. → X kapali.
Sicaklik Y. → Of course, sir. Sicaklik Y.",
    ),
    (
        "eu",
        "default",
        "X piztuta dago. → X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Tenperatura Y.",
    ),
    (
        "eu",
        "butler",
        "X piztuta dago. → Oso ondo. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Oso ondo. Tenperatura Y.",
    ),
    (
        "eu",
        "locker",
        "X piztuta dago. → Ados. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Ados. Tenperatura Y.",
    ),
    (
        "eu",
        "fuersorglich",
        "X piztuta dago. → Oraintxe. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Oraintxe. Tenperatura Y.",
    ),
    (
        "eu",
        "party",
        "X piztuta dago. → Goazen. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Goazen. Tenperatura Y.",
    ),
    (
        "eu",
        "grantig",
        "X piztuta dago. → Tira. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Tira. Tenperatura Y.",
    ),
    (
        "eu",
        "sarkastisch",
        "X piztuta dago. → Noski. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Noski. Tenperatura Y.",
    ),
    (
        "eu",
        "pirat",
        "X piztuta dago. → Aye. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Aye. Tenperatura Y.",
    ),
    (
        "eu",
        "hippie",
        "X piztuta dago. → Lasai. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Lasai. Tenperatura Y.",
    ),
    (
        "eu",
        "gollum",
        "X piztuta dago. → Bai. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Bai. Tenperatura Y.",
    ),
    (
        "eu",
        "jarvis",
        "X piztuta dago. → Of course, sir. X piztuta dago.
X itzalita dago. → X itzalita dago.
Tenperatura Y. → Of course, sir. Tenperatura Y.",
    ),
    (
        "lt",
        "default",
        "X ijungta. → X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "lt",
        "butler",
        "X ijungta. → Labai gerai. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Labai gerai. Temperatura Y.",
    ),
    (
        "lt",
        "locker",
        "X ijungta. → Aisku. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Aisku. Temperatura Y.",
    ),
    (
        "lt",
        "fuersorglich",
        "X ijungta. → Padarysiu iskart. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Padarysiu iskart. Temperatura Y.",
    ),
    (
        "lt",
        "party",
        "X ijungta. → Vaziuojam. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Vaziuojam. Temperatura Y.",
    ),
    (
        "lt",
        "grantig",
        "X ijungta. → Gerai. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Gerai. Temperatura Y.",
    ),
    (
        "lt",
        "sarkastisch",
        "X ijungta. → Zinoma. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Zinoma. Temperatura Y.",
    ),
    (
        "lt",
        "pirat",
        "X ijungta. → Aye. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "lt",
        "hippie",
        "X ijungta. → Ramiai. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Ramiai. Temperatura Y.",
    ),
    (
        "lt",
        "gollum",
        "X ijungta. → Taip. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Taip. Temperatura Y.",
    ),
    (
        "lt",
        "jarvis",
        "X ijungta. → Of course, sir. X ijungta.
X isjungta. → X isjungta.
Temperatura Y. → Of course, sir. Temperatura Y.",
    ),
    (
        "hi",
        "default",
        "X जल रहा है। → X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Tapman Y.",
    ),
    (
        "hi",
        "butler",
        "X जल रहा है। → Theek. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Theek. Tapman Y.",
    ),
    (
        "hi",
        "locker",
        "X जल रहा है। → Samajh gaya. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Samajh gaya. Tapman Y.",
    ),
    (
        "hi",
        "fuersorglich",
        "X जल रहा है। → Abhi karta hoon. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Abhi karta hoon. Tapman Y.",
    ),
    (
        "hi",
        "party",
        "X जल रहा है। → Chalo. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Chalo. Tapman Y.",
    ),
    (
        "hi",
        "grantig",
        "X जल रहा है। → Theek hai. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Theek hai. Tapman Y.",
    ),
    (
        "hi",
        "sarkastisch",
        "X जल रहा है। → Zaroor. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Zaroor. Tapman Y.",
    ),
    (
        "hi",
        "pirat",
        "X जल रहा है। → Aye. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Aye. Tapman Y.",
    ),
    (
        "hi",
        "hippie",
        "X जल रहा है। → Aaram se. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Aaram se. Tapman Y.",
    ),
    (
        "hi",
        "gollum",
        "X जल रहा है। → Haan. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Haan. Tapman Y.",
    ),
    (
        "hi",
        "jarvis",
        "X जल रहा है। → Of course, sir. X जल रहा है।
X बंद है। → X बंद है।
Tapman Y. → Of course, sir. Tapman Y.",
    ),
    (
        "ta",
        "default",
        "X எரிகிறது. → X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Veppam Y.",
    ),
    (
        "ta",
        "butler",
        "X எரிகிறது. → Nandraga. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Nandraga. Veppam Y.",
    ),
    (
        "ta",
        "locker",
        "X எரிகிறது. → Purinjiduchu. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Purinjiduchu. Veppam Y.",
    ),
    (
        "ta",
        "fuersorglich",
        "X எரிகிறது. → Ippo seiren. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Ippo seiren. Veppam Y.",
    ),
    (
        "ta",
        "party",
        "X எரிகிறது. → Povom. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Povom. Veppam Y.",
    ),
    (
        "ta",
        "grantig",
        "X எரிகிறது. → Sari. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Sari. Veppam Y.",
    ),
    (
        "ta",
        "sarkastisch",
        "X எரிகிறது. → Kandippa. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Kandippa. Veppam Y.",
    ),
    (
        "ta",
        "pirat",
        "X எரிகிறது. → Aye. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Aye. Veppam Y.",
    ),
    (
        "ta",
        "hippie",
        "X எரிகிறது. → Amaidhi. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Amaidhi. Veppam Y.",
    ),
    (
        "ta",
        "gollum",
        "X எரிகிறது. → Aam. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Aam. Veppam Y.",
    ),
    (
        "ta",
        "jarvis",
        "X எரிகிறது. → Of course, sir. X எரிகிறது.
X அணைந்தது. → X அணைந்தது.
Veppam Y. → Of course, sir. Veppam Y.",
    ),
    (
        "mn",
        "default",
        "X асаа. → X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Temperatur Y.",
    ),
    (
        "mn",
        "butler",
        "X асаа. → Za saikhan. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Za saikhan. Temperatur Y.",
    ),
    (
        "mn",
        "locker",
        "X асаа. → Oilgoloo. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Oilgoloo. Temperatur Y.",
    ),
    (
        "mn",
        "fuersorglich",
        "X асаа. → Odoo khine. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Odoo khine. Temperatur Y.",
    ),
    (
        "mn",
        "party",
        "X асаа. → Yavya. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Yavya. Temperatur Y.",
    ),
    (
        "mn",
        "grantig",
        "X асаа. → Za. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Za. Temperatur Y.",
    ),
    (
        "mn",
        "sarkastisch",
        "X асаа. → Medeej. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Medeej. Temperatur Y.",
    ),
    (
        "mn",
        "pirat",
        "X асаа. → Aye. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Aye. Temperatur Y.",
    ),
    (
        "mn",
        "hippie",
        "X асаа. → Amjuun. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Amjuun. Temperatur Y.",
    ),
    (
        "mn",
        "gollum",
        "X асаа. → Tiim. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Tiim. Temperatur Y.",
    ),
    (
        "mn",
        "jarvis",
        "X асаа. → Of course, sir. X асаа.
X унтраа. → X унтраа.
Temperatur Y. → Of course, sir. Temperatur Y.",
    ),
];
