// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "ca",
        "default",
        "X esta encès. → X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → La temperatura Y.",
    ),
    (
        "ca",
        "butler",
        "X esta encès. → Molt be. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Molt be. La temperatura Y.",
    ),
    (
        "ca",
        "locker",
        "X esta encès. → Fet. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Fet. La temperatura Y.",
    ),
    (
        "ca",
        "fuersorglich",
        "X esta encès. → Ara mateix. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Ara mateix. La temperatura Y.",
    ),
    (
        "ca",
        "party",
        "X esta encès. → Som-hi. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Som-hi. La temperatura Y.",
    ),
    (
        "ca",
        "grantig",
        "X esta encès. → Be. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Be. La temperatura Y.",
    ),
    (
        "ca",
        "sarkastisch",
        "X esta encès. → Esclar. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Esclar. La temperatura Y.",
    ),
    (
        "ca",
        "pirat",
        "X esta encès. → Aye. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Aye. La temperatura Y.",
    ),
    (
        "ca",
        "hippie",
        "X esta encès. → Tranqui. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Tranqui. La temperatura Y.",
    ),
    (
        "ca",
        "gollum",
        "X esta encès. → Si. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Si. La temperatura Y.",
    ),
    (
        "ca",
        "jarvis",
        "X esta encès. → Of course, sir. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Of course, sir. La temperatura Y.",
    ),
    (
        "de-CH",
        "default",
        "X isch aa. → X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → D Temperatur Y.",
    ),
    (
        "de-CH",
        "butler",
        "X isch aa. → Guet. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Guet. D Temperatur Y.",
    ),
    (
        "de-CH",
        "locker",
        "X isch aa. → Passt. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Passt. D Temperatur Y.",
    ),
    (
        "de-CH",
        "fuersorglich",
        "X isch aa. → Mach i gli. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Mach i gli. D Temperatur Y.",
    ),
    (
        "de-CH",
        "party",
        "X isch aa. → Lauft. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Lauft. D Temperatur Y.",
    ),
    (
        "de-CH",
        "grantig",
        "X isch aa. → Scho guet. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Scho guet. D Temperatur Y.",
    ),
    (
        "de-CH",
        "sarkastisch",
        "X isch aa. → Na klar. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Na klar. D Temperatur Y.",
    ),
    (
        "de-CH",
        "pirat",
        "X isch aa. → Aye. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Aye. D Temperatur Y.",
    ),
    (
        "de-CH",
        "hippie",
        "X isch aa. → Easy. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Easy. D Temperatur Y.",
    ),
    (
        "de-CH",
        "gollum",
        "X isch aa. → Ja. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Ja. D Temperatur Y.",
    ),
    (
        "de-CH",
        "jarvis",
        "X isch aa. → Of course, sir. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Of course, sir. D Temperatur Y.",
    ),
    (
        "sk",
        "default",
        "X je zapnute. → X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Teplota Y.",
    ),
    (
        "sk",
        "butler",
        "X je zapnute. → Velmi dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Velmi dobre. Teplota Y.",
    ),
    (
        "sk",
        "locker",
        "X je zapnute. → Jasne. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Jasne. Teplota Y.",
    ),
    (
        "sk",
        "fuersorglich",
        "X je zapnute. → Hned to spravim. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Hned to spravim. Teplota Y.",
    ),
    (
        "sk",
        "party",
        "X je zapnute. → Ideme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Ideme. Teplota Y.",
    ),
    (
        "sk",
        "grantig",
        "X je zapnute. → No dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → No dobre. Teplota Y.",
    ),
    (
        "sk",
        "sarkastisch",
        "X je zapnute. → Samozrejme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Samozrejme. Teplota Y.",
    ),
    (
        "sk",
        "pirat",
        "X je zapnute. → Aye. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Aye. Teplota Y.",
    ),
    (
        "sk",
        "hippie",
        "X je zapnute. → Pohoda. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Pohoda. Teplota Y.",
    ),
    (
        "sk",
        "gollum",
        "X je zapnute. → Ano. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Ano. Teplota Y.",
    ),
    (
        "sk",
        "jarvis",
        "X je zapnute. → Of course, sir. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Of course, sir. Teplota Y.",
    ),
    (
        "el",
        "default",
        "X ειναι ανοιχτο. → X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Η θερμοκρασια Y.",
    ),
    (
        "el",
        "butler",
        "X ειναι ανοιχτο. → Πολυ καλα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Πολυ καλα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "locker",
        "X ειναι ανοιχτο. → Ενταξει. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Ενταξει. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "fuersorglich",
        "X ειναι ανοιχτο. → Το κανω αμεσως. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Το κανω αμεσως. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "party",
        "X ειναι ανοιχτο. → Πάμε. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Πάμε. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "grantig",
        "X ειναι ανοιχτο. → Καλα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Καλα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "sarkastisch",
        "X ειναι ανοιχτο. → Φυσικα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Φυσικα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "pirat",
        "X ειναι ανοιχτο. → Aye. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Aye. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "hippie",
        "X ειναι ανοιχτο. → Χαλαρα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Χαλαρα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "gollum",
        "X ειναι ανοιχτο. → Ναι. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Ναι. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "jarvis",
        "X ειναι ανοιχτο. → Of course, sir. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Of course, sir. Η θερμοκρασια Y.",
    ),
    (
        "zh-HK",
        "default",
        "X開咗。 → X開咗。
X關咗。 → X關咗。
溫度Y。 → 溫度Y。",
    ),
    (
        "zh-HK",
        "butler",
        "X開咗。 → 好呀。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 好呀。 溫度Y。",
    ),
    (
        "zh-HK",
        "locker",
        "X開咗。 → 得。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 得。 溫度Y。",
    ),
    (
        "zh-HK",
        "fuersorglich",
        "X開咗。 → 而家就做。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 而家就做。 溫度Y。",
    ),
    (
        "zh-HK",
        "party",
        "X開咗。 → 嚟啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 嚟啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "grantig",
        "X開咗。 → 算啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 算啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "sarkastisch",
        "X開咗。 → 當然啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 當然啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "pirat",
        "X開咗。 → Aye. X開咗。
X關咗。 → X關咗。
溫度Y。 → Aye. 溫度Y。",
    ),
    (
        "zh-HK",
        "hippie",
        "X開咗。 → 放鬆啲。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 放鬆啲。 溫度Y。",
    ),
    (
        "zh-HK",
        "gollum",
        "X開咗。 → 係。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 係。 溫度Y。",
    ),
    (
        "zh-HK",
        "jarvis",
        "X開咗。 → Of course, sir. X開咗。
X關咗。 → X關咗。
溫度Y。 → Of course, sir. 溫度Y。",
    ),
    (
        "th",
        "default",
        "X เปิดแล้ว. → X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → อุณหภูมิ Y.",
    ),
    (
        "th",
        "butler",
        "X เปิดแล้ว. → ได้เลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ได้เลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "locker",
        "X เปิดแล้ว. → โอเค. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → โอเค. อุณหภูมิ Y.",
    ),
    (
        "th",
        "fuersorglich",
        "X เปิดแล้ว. → ทำให้เลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ทำให้เลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "party",
        "X เปิดแล้ว. → ไปเลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ไปเลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "grantig",
        "X เปิดแล้ว. → ก็ได้. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ก็ได้. อุณหภูมิ Y.",
    ),
    (
        "th",
        "sarkastisch",
        "X เปิดแล้ว. → แน่นอน. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → แน่นอน. อุณหภูมิ Y.",
    ),
    (
        "th",
        "pirat",
        "X เปิดแล้ว. → Aye. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → Aye. อุณหภูมิ Y.",
    ),
    (
        "th",
        "hippie",
        "X เปิดแล้ว. → สบายๆ. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → สบายๆ. อุณหภูมิ Y.",
    ),
    (
        "th",
        "gollum",
        "X เปิดแล้ว. → ใช่. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ใช่. อุณหภูมิ Y.",
    ),
    (
        "th",
        "jarvis",
        "X เปิดแล้ว. → Of course, sir. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → Of course, sir. อุณหภูมิ Y.",
    ),
    (
        "ga",
        "default",
        "Ta X ar siul. → Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → An teocht Y.",
    ),
    (
        "ga",
        "butler",
        "Ta X ar siul. → Go maith. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Go maith. An teocht Y.",
    ),
    (
        "ga",
        "locker",
        "Ta X ar siul. → Faighte. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Faighte. An teocht Y.",
    ),
    (
        "ga",
        "fuersorglich",
        "Ta X ar siul. → Deanaim e anois. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Deanaim e anois. An teocht Y.",
    ),
    (
        "ga",
        "party",
        "Ta X ar siul. → Ar aghaidh linn. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ar aghaidh linn. An teocht Y.",
    ),
    (
        "ga",
        "grantig",
        "Ta X ar siul. → Ceart go leor. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ceart go leor. An teocht Y.",
    ),
    (
        "ga",
        "sarkastisch",
        "Ta X ar siul. → Ar ndoigh. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ar ndoigh. An teocht Y.",
    ),
    (
        "ga",
        "pirat",
        "Ta X ar siul. → Aye. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Aye. An teocht Y.",
    ),
    (
        "ga",
        "hippie",
        "Ta X ar siul. → Easca. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Easca. An teocht Y.",
    ),
    (
        "ga",
        "gollum",
        "Ta X ar siul. → Ta. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ta. An teocht Y.",
    ),
    (
        "ga",
        "jarvis",
        "Ta X ar siul. → Of course, sir. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Of course, sir. An teocht Y.",
    ),
    (
        "lv",
        "default",
        "X ir ieslegts. → X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "lv",
        "butler",
        "X ir ieslegts. → Labi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Labi. Temperatura Y.",
    ),
    (
        "lv",
        "locker",
        "X ir ieslegts. → Skaidrs. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Skaidrs. Temperatura Y.",
    ),
    (
        "lv",
        "fuersorglich",
        "X ir ieslegts. → Darisu tulit. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Darisu tulit. Temperatura Y.",
    ),
    (
        "lv",
        "party",
        "X ir ieslegts. → Ejam. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Ejam. Temperatura Y.",
    ),
    (
        "lv",
        "grantig",
        "X ir ieslegts. → Labi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Labi. Temperatura Y.",
    ),
    (
        "lv",
        "sarkastisch",
        "X ir ieslegts. → Protams. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Protams. Temperatura Y.",
    ),
    (
        "lv",
        "pirat",
        "X ir ieslegts. → Aye. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "lv",
        "hippie",
        "X ir ieslegts. → Mierigi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Mierigi. Temperatura Y.",
    ),
    (
        "lv",
        "gollum",
        "X ir ieslegts. → Ja. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Ja. Temperatura Y.",
    ),
    (
        "lv",
        "jarvis",
        "X ir ieslegts. → Of course, sir. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Of course, sir. Temperatura Y.",
    ),
    (
        "bn",
        "default",
        "X জ্বলছে। → X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Tapmatra Y.",
    ),
    (
        "bn",
        "butler",
        "X জ্বলছে। → Bhalo. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Bhalo. Tapmatra Y.",
    ),
    (
        "bn",
        "locker",
        "X জ্বলছে। → Bujhechi. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Bujhechi. Tapmatra Y.",
    ),
    (
        "bn",
        "fuersorglich",
        "X জ্বলছে। → Ekhon korchi. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Ekhon korchi. Tapmatra Y.",
    ),
    (
        "bn",
        "party",
        "X জ্বলছে। → Cholo. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Cholo. Tapmatra Y.",
    ),
    (
        "bn",
        "grantig",
        "X জ্বলছে। → Thik. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Thik. Tapmatra Y.",
    ),
    (
        "bn",
        "sarkastisch",
        "X জ্বলছে। → Obosshoi. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Obosshoi. Tapmatra Y.",
    ),
    (
        "bn",
        "pirat",
        "X জ্বলছে। → Aye. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Aye. Tapmatra Y.",
    ),
    (
        "bn",
        "hippie",
        "X জ্বলছে। → Aaram. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Aaram. Tapmatra Y.",
    ),
    (
        "bn",
        "gollum",
        "X জ্বলছে। → Hyan. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Hyan. Tapmatra Y.",
    ),
    (
        "bn",
        "jarvis",
        "X জ্বলছে। → Of course, sir. X জ্বলছে।
X নিভানো। → X নিভানো।
Tapmatra Y. → Of course, sir. Tapmatra Y.",
    ),
    (
        "te",
        "default",
        "X వెలిగింది. → X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Ushnota Y.",
    ),
    (
        "te",
        "butler",
        "X వెలిగింది. → Baagundi. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Baagundi. Ushnota Y.",
    ),
    (
        "te",
        "locker",
        "X వెలిగింది. → Ardham ayindi. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Ardham ayindi. Ushnota Y.",
    ),
    (
        "te",
        "fuersorglich",
        "X వెలిగింది. → Ippudu chestunnanu. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Ippudu chestunnanu. Ushnota Y.",
    ),
    (
        "te",
        "party",
        "X వెలిగింది. → Podam. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Podam. Ushnota Y.",
    ),
    (
        "te",
        "grantig",
        "X వెలిగింది. → Sare. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Sare. Ushnota Y.",
    ),
    (
        "te",
        "sarkastisch",
        "X వెలిగింది. → Kesam. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Kesam. Ushnota Y.",
    ),
    (
        "te",
        "pirat",
        "X వెలిగింది. → Aye. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Aye. Ushnota Y.",
    ),
    (
        "te",
        "hippie",
        "X వెలిగింది. → Prashantam. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Prashantam. Ushnota Y.",
    ),
    (
        "te",
        "gollum",
        "X వెలిగింది. → Avunu. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Avunu. Ushnota Y.",
    ),
    (
        "te",
        "jarvis",
        "X వెలిగింది. → Of course, sir. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
Ushnota Y. → Of course, sir. Ushnota Y.",
    ),
];
