version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      rust-patch:
        update-types:
          - patch
      rust-minor:
        update-types:
          - minor
    labels:
      - dependencies
    commit-message:
      prefix: cargo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    commit-message:
      prefix: ci
