#[derive(Debug)]
pub(super) struct LegacyWaiver {
    pub id: &'static str,
    pub suite: &'static str,
    pub group: &'static str,
    pub label: &'static str,
    pub kind: &'static str,
    pub fingerprint: u64,
    pub reason: &'static str,
}

const LEGACY_WAIVERS: &[LegacyWaiver] = &[
    waiver(
        "W-DE-AREA-001",
        "wohnung_mittel",
        "query_area",
        "status::status_licht_badezimmer",
        "parity",
        0x3cf7_65ee_1c90_6f1e,
        "V2 rejects an area query without an Assist-visible light in that area",
    ),
    waiver(
        "W-DE-AREA-002",
        "wohnung_mittel",
        "query_area",
        "status::temperatur_wohnung",
        "parity",
        0x7597_b6da_099c_0777,
        "V2 rejects an area query without an Assist-visible climate entity in that area",
    ),
    waiver(
        "W-DE-MULTI-001",
        "wohnung_mittel",
        "multiple_intents",
        "multi::licht_und_heizung",
        "parity",
        0x1a7f_6228_52fe_0b45,
        "V1 emits a targetless climate control; V2 drops that invalid step and keeps the grounded light",
    ),
    waiver(
        "W-DE-MULTI-002",
        "wohnung_mittel",
        "multiple_intents",
        "multi::zwei_raeume_und_heizung",
        "parity",
        0xa354_8495_9180_b3a8,
        "V1 expands climate control into an area without an Assist-visible climate entity; V2 keeps the valid lights",
    ),
    waiver(
        "W-DE-FOLLOWUP-001",
        "familienhaus_de",
        "state_persistance",
        "area_hallway_and_powder_room_lights::hallway_and_powder_room_lights_set_brightness",
        "oracle",
        0xa1d7_aad1_0267_e90e,
        "approved legacy follow-up miss: only the hallway target is retained",
    ),
    waiver(
        "W-EN-MEDIA-002",
        "family_home_en",
        "devices",
        "media_player_family_tv::media_player_family_tv_unpause",
        "oracle",
        0x6a6a_01f1_1997_65c2,
        "approved legacy miss: resume is misclassified as search-and-play",
    ),
    waiver(
        "W-EN-MEDIA-003",
        "family_home_en",
        "devices",
        "media_player_family_tv::media_player_family_tv_unmute",
        "parity",
        0x288d_e9db_da16_e1a2,
        "V1 emits a targetless mute step; V2 keeps the grounded player command",
    ),
    waiver(
        "W-EN-MEDIA-004",
        "family_home_en",
        "devices",
        "media_player_living_tv::media_player_living_tv_unpause",
        "oracle",
        0x6a6a_01f1_1997_65c2,
        "approved legacy miss: resume is misclassified as search-and-play",
    ),
    waiver(
        "W-EN-COVER-001",
        "family_home_en",
        "state_persistance",
        "area_bedroom_2_covers::bedroom_2_covers_set_position",
        "parity",
        0x33eb_f0ca_6d2f_09e9,
        "V1 emits HassSetPosition on a status question; V2 queries the covers",
    ),
    waiver(
        "W-EN-COVER-002",
        "family_home_en",
        "state_persistance",
        "area_master_bedroom_and_living_covers::master_bedroom_and_living_covers_set_position",
        "parity",
        0x4512_69ed_b117_67f2,
        "V1 emits HassSetPosition on a status question; V2 queries the covers",
    ),
    waiver(
        "W-EN-COVER-003",
        "family_home_en",
        "state_persistance",
        "device_cover_living_blinds::cover_living_blinds_persistance_position",
        "parity",
        0xe0dd_0eab_71e1_eee2,
        "V1 emits HassSetPosition without the required position slot; V2 rejects it",
    ),
    waiver(
        "W-EN-LIST-001A",
        "family_home_en",
        "lists",
        "lists::shopping_list_complete_bread",
        "parity",
        0x4888_5f70_c4b9_4b0e,
        "V1 appends a list-add intent with no item; V2 keeps only the complete-item step",
    ),
    waiver(
        "W-EN-LIST-001B",
        "family_home_en",
        "lists",
        "lists::shopping_list_complete_bread",
        "parity",
        0xf2b2_5ba8_d991_f18b,
        "V1 completes a list item without the item slot; V2 asks for clarification",
    ),
    waiver(
        "W-EN-LIST-002A",
        "family_home_en",
        "lists",
        "lists::chores_complete_scrub_the_toilet",
        "parity",
        0xc7e1_4e75_bacc_edc4,
        "V1 appends a list-add intent with no item; V2 keeps only the complete-item step",
    ),
    waiver(
        "W-EN-LIST-002B",
        "family_home_en",
        "lists",
        "lists::chores_complete_scrub_the_toilet",
        "parity",
        0x848c_44b7_47ff_b716,
        "V1 appends a list-add intent with no item; V2 keeps only the complete-item step",
    ),
    waiver(
        "W-EN-LIST-002C",
        "family_home_en",
        "lists",
        "lists::chores_complete_scrub_the_toilet",
        "parity",
        0x70d2_1764_c8e5_0d60,
        "V1 appends a list-add intent with no item; V2 keeps only the complete-item step",
    ),
    waiver(
        "W-EN-LIST-002D",
        "family_home_en",
        "lists",
        "lists::chores_complete_scrub_the_toilet",
        "parity",
        0x9b40_f5f6_3a90_9886,
        "V1 completes a list item without the item slot; V2 asks for clarification",
    ),
    waiver(
        "W-EN-COVER-008",
        "family_home_en",
        "area",
        "master_bedroom_covers::master_bedroom_covers_close",
        "parity",
        0xe9c6_c0c5_4490_0f16,
        "V1 expands curtains to a preferred area; V2 rejects an ungrounded cover close",
    ),
    waiver(
        "W-EN-COVER-005",
        "family_home_en",
        "query_devices",
        "cover_garage_door::cover_garage_door_get_status",
        "parity",
        0xf73d_a423_2c71_b88b,
        "V1 appends TurnOff on an open-or-closed question; V2 only queries the garage door",
    ),
    waiver(
        "W-EN-COVER-006",
        "family_home_en",
        "state_persistance",
        "device_cover_garage_door::cover_garage_door_open",
        "parity",
        0xf73d_a423_2c71_b88b,
        "V1 appends TurnOff on an open-or-closed question; V2 only queries the garage door",
    ),
    waiver(
        "W-EN-COVER-007",
        "family_home_en",
        "state_persistance",
        "device_cover_garage_door::cover_garage_door_open",
        "parity",
        0xc3e8_2fc0_ce77_d9c2,
        "V1 appends TurnOff on an up-or-down question; V2 only queries the garage door",
    ),
    waiver(
        "W-EN-LOCK-001",
        "family_home_en",
        "state_persistance",
        "device_lock_garage_entry::lock_garage_entry_lock",
        "parity",
        0xb4f4_0269_f5d4_8e94,
        "V1 appends TurnOff on an open-or-closed question; V2 only queries the lock",
    ),
    waiver(
        "W-EN-LOCK-002",
        "family_home_en",
        "devices",
        "lock_garage_entry::lock_garage_entry_unlock",
        "parity",
        0x9db5_50d3_5a77_370c,
        "V1 treats 'flick the lock on the door' as unlock; V2 locks the named entity",
    ),
    waiver(
        "W-EN-HALL-001",
        "family_home_en",
        "query_area",
        "hallway_lights::hallway_lights_list_off_lights",
        "parity",
        0x2b06_26a3_e91e_5daf,
        "V1 appends TurnOff on an on-or-off question; V2 only queries the hallway lights",
    ),
    waiver(
        "W-EN-HALL-002",
        "family_home_en",
        "query_devices",
        "light_hallway_light::light_hallway_light_get_status",
        "parity",
        0x2b06_26a3_e91e_5daf,
        "V1 appends TurnOff on an on-or-off question; V2 only queries the hallway lights",
    ),
    waiver(
        "W-DE-MUTE-001",
        "familienhaus_de",
        "devices",
        "media_player_family_tv::media_player_family_tv_unmute",
        "parity",
        0x1f0a_f6dd_3ab6_37d6,
        "V1 appends a TurnOff after unmute; V2 keeps only the unmute command",
    ),
    waiver(
        "W-DE-MUTE-002",
        "familienhaus_de",
        "devices",
        "media_player_living_tv::media_player_living_tv_unmute",
        "parity",
        0x2d67_2c0b_7535_6a01,
        "V1 appends a TurnOff after unmute; V2 keeps only the unmute command",
    ),
    waiver(
        "W-EN-AREA-001",
        "wohnung_en",
        "query_area",
        "status::how_warm_home",
        "parity",
        0x7597_b6da_099c_0777,
        "V2 rejects an area query without an Assist-visible climate entity in that area",
    ),
    waiver(
        "W-DE-SCENE-001",
        "wohnung_mittel",
        "devices",
        "geraete::filmabend",
        "parity",
        0xf52d_5a7d_f09a_ae19,
        "V1 emits a duplicate scene TurnOn without domain; V2 keeps the single grounded scene intent",
    ),
    waiver(
        "W-DE-SCENE-002",
        "familienhaus_de",
        "devices",
        "scenes::movie_night",
        "parity",
        0x0bd8_4c53_85cc_2c8a,
        "V1 emits a duplicate scene TurnOn without domain; V2 keeps the single grounded scene intent",
    ),
    waiver(
        "W-DE-SCENE-003",
        "familienhaus_de",
        "devices",
        "scenes::dinner_time",
        "parity",
        0x1755_53c0_cb73_af9f,
        "V1 emits a duplicate scene TurnOn without domain; V2 keeps the single grounded scene intent",
    ),
    waiver(
        "W-DE-SCENE-004",
        "familienhaus_de",
        "devices",
        "scenes::kids_bedtime",
        "parity",
        0x22ae_5e24_fbc9_e533,
        "V1 emits a duplicate scene TurnOn without domain; V2 keeps the single grounded scene intent",
    ),
    waiver(
        "W-DE-SCENE-005",
        "familienhaus_de",
        "devices",
        "scenes::good_morning",
        "parity",
        0xd277_1eae_5f2e_5c69,
        "V1 emits a duplicate scene TurnOn without domain; V2 keeps the single grounded scene intent",
    ),
    waiver(
        "W-DE-SCRIPT-001",
        "familienhaus_de",
        "devices",
        "scripts::good_night",
        "parity",
        0x8cb8_1440_ff73_8764,
        "V1 emits a duplicate script TurnOn without domain; V2 keeps the single grounded script intent",
    ),
    waiver(
        "W-DE-SCRIPT-002",
        "familienhaus_de",
        "devices",
        "scripts::leaving_home",
        "parity",
        0x5e9f_c7a7_6165_865e,
        "V1 emits a duplicate script TurnOn without domain; V2 keeps the single grounded script intent",
    ),
];

const fn waiver(
    id: &'static str,
    suite: &'static str,
    group: &'static str,
    label: &'static str,
    kind: &'static str,
    fingerprint: u64,
    reason: &'static str,
) -> LegacyWaiver {
    LegacyWaiver { id, suite, group, label, kind, fingerprint, reason }
}

pub(super) fn matching(suite: &str, group: &str, label: &str, kind: &str, fingerprint: u64) -> Option<&'static LegacyWaiver> {
    LEGACY_WAIVERS.iter().find(|waiver| {
        waiver.suite == suite && waiver.group == group && waiver.label == label && waiver.kind == kind && waiver.fingerprint == fingerprint
    })
}

pub(super) fn for_case<'a>(suite: &'a str, group: &'a str, label: &'a str) -> impl Iterator<Item = &'static LegacyWaiver> + 'a {
    LEGACY_WAIVERS.iter().filter(move |waiver| waiver.suite == suite && waiver.group == group && waiver.label == label)
}

pub(super) fn expected_for<'a>(suite: &'a str, groups: &'a [&'a str]) -> impl Iterator<Item = &'static LegacyWaiver> + 'a {
    LEGACY_WAIVERS.iter().filter(move |waiver| waiver.suite == suite && groups.contains(&waiver.group))
}
