#!/usr/bin/env python3
"""Stdlib tests for CHANGELOG release-note extraction."""

from __future__ import annotations

import importlib.util
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _load():
    path = ROOT / "scripts" / "release-notes.py"
    spec = importlib.util.spec_from_file_location("klar_release_notes", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mod = _load()


class ReleaseNotesTests(unittest.TestCase):
    def test_extracts_2026_8_4(self) -> None:
        notes = mod.section((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "2026.8.4")
        self.assertIn("### Security", notes)
        self.assertIn("SHA-256", notes)
        self.assertNotIn("## [2026.8.3]", notes)
        self.assertNotIn("## [2026.8.5]", notes)

    def test_extracts_2026_8_5(self) -> None:
        notes = mod.section((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "2026.8.5")
        self.assertIn("### Bug Fixes", notes)
        self.assertIn("Adaptive Lighting", notes)
        self.assertNotIn("## [2026.8.4]", notes)

    def test_synthetic_range(self) -> None:
        text = (
            "# Changelog\n\n"
            "## [1.2.0](https://example.test/compare/1.1.0...1.2.0) - 2026-01-02\n\n"
            "### Features\n\n- extra lights\n\n"
            "## [1.1.0] - 2026-01-01\n\n"
            "### Bug Fixes\n\n- older\n"
        )
        notes = mod.section(text, "v1.2.0")
        self.assertIn("extra lights", notes)
        self.assertNotIn("older", notes)

    def test_missing_version(self) -> None:
        self.assertEqual(mod.section("# Changelog\n", "9.9.9"), "")
        self.assertEqual(mod.main(["release-notes.py", "9.9.9"]), 1)

    def test_calver_base_strips_rc_suffix(self) -> None:
        self.assertEqual(mod.calver_base("v2026.8.30-staging.a1b2c3d"), "2026.8.30")
        self.assertEqual(mod.calver_base("2026.8.30-rc.12"), "2026.8.30")

    def test_staging_notes_list_commits_since_main(self) -> None:
        notes = mod.commits_since(
            [
                "feat: full-home language lift",
                "Merge pull request #92 from org/branch",
                "fix: gitleaks RE2 panic",
            ],
            "main",
        )
        self.assertIn("## Changes since `main`", notes)
        self.assertIn("- feat: full-home language lift", notes)
        self.assertIn("- fix: gitleaks RE2 panic", notes)
        self.assertNotIn("Merge pull request", notes)

    def test_heading_without_groups_is_rejected(self) -> None:
        empty = "## [2026.8.4] - 2026-08-15\n\n<!-- generated by git-cliff -->\n"
        notes = mod.section(empty, "2026.8.4")
        self.assertTrue(notes)
        self.assertIsNone(re.search(r"^### ", notes, re.M))


if __name__ == "__main__":
    unittest.main()
