#!/usr/bin/env python3
"""Generate compiled Assist language packs.

de/en already live under src/lang/packs/ as hand-written reference packs.
This script never overwrites them; it only registers their paths.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lang_packs.emit import write_pack, write_registry
from lang_packs.ha_ui import write_ha_translations
from lang_packs.expand import expand
from lang_packs.lexicons import ALL_CORES, BUILTINS
from lang_packs.voices import HAND_BUNDLES, locale_bundle, PERSONALITY_KEYS


def main() -> None:
    generated = [expand(core) for core in ALL_CORES]
    for lang in generated:
        write_pack(lang)
        print("wrote", lang["code"])
    registry = BUILTINS + generated
    write_registry(registry)
    smoke = Path(__file__).resolve().parents[2] / "tests" / "assist_langs.rs"
    cases = []
    for code, text, intent in (
        ("de", "licht wohnzimmer an", "HassTurnOn"),
        ("de", "licht kuche aus", "HassTurnOff"),
        ("de", "was steht an", "KlarGetCalendarEvents"),
        ("de", "termin zahnarzt morgen um 15 uhr", "KlarCreateCalendarEvent"),
        ("de", "loesch zahnarzt kalender", "KlarDeleteCalendarEvent"),
        ("de", "verschieb zahnarzt morgen um 16 kalender", "KlarMoveCalendarEvent"),
        ("en", "turn on the living room light", "HassTurnOn"),
        ("en", "turn off the kitchen light", "HassTurnOff"),
        ("en", "whats on my calendar", "KlarGetCalendarEvents"),
        ("en", "add dentist tomorrow at 3 to my calendar", "KlarCreateCalendarEvent"),
        ("en", "delete dentist calendar", "KlarDeleteCalendarEvent"),
        ("en", "move dentist tomorrow at 4 calendar", "KlarMoveCalendarEvent"),
    ):
        cases.append(f'    ("{code}", "{text}", "{intent}"),')
    for lang in generated:
        for text, intent in lang.get("smoke", []):
            if intent.startswith(("HassTurn", "KlarGetCalendar", "KlarCreateCalendar", "KlarDeleteCalendar", "KlarMoveCalendar")):
                cases.append(f'    ("{lang["code"]}", "{text}", "{intent}"),')
    smoke.write_text(
        """// @generated by scripts/lang_packs. DO NOT EDIT.
use klar_nlu::home::default_home;
use klar_nlu::nlu::parse;
use klar_nlu::session::Session;
use klar_nlu::types::{ParseDecision, Settings};

const CASES: &[(&str, &str, &str)] = &[
"""
        + "\n".join(cases)
        + """
];

#[test]
fn compiled_assist_packs_execute_home_commands() {
    let home = default_home();
    for (lang, text, intent) in CASES {
        assert_ne!(*lang, "ru", "russian is not shipped");
        let settings = Settings { languages: vec![(*lang).into()], ..Settings::default() };
        let mut session = Session::default();
        let outcome = parse(text, &home, &mut session, &[], &settings);
        let names: Vec<_> =
            outcome.plan.as_ref().map(|plan| plan.intents().into_iter().map(|item| item.name).collect()).unwrap_or_default();
        assert!(
            matches!(outcome.decision, ParseDecision::Execute) && names.iter().any(|name| name == intent),
            "{lang} {text} decision={:?} intents={names:?}",
            outcome.decision
        );
    }
}

#[test]
fn russian_is_not_a_compiled_pack() {
    assert!(klar_nlu::lang::LangId::from_code("ru").is_none());
    assert!(!klar_nlu::lang::LangId::all().iter().any(|id| id.code() == "ru"));
}
""",
        encoding="utf-8",
    )
    datasets = Path(__file__).resolve().parents[2] / "tests" / "datasets" / "assist"
    for lang in generated:
        dest = datasets / lang["code"]
        dest.mkdir(parents=True, exist_ok=True)
        rows = []
        for text, intent in lang.get("smoke", []):
            kind = {
                "HassTurnOn": "light_on",
                "HassTurnOff": "light_off",
                "KlarGetCalendarEvents": "calendar_list",
                "KlarCreateCalendarEvent": "calendar_create",
                "KlarDeleteCalendarEvent": "calendar_delete",
                "KlarMoveCalendarEvent": "calendar_move",
                "MassPlayMedia": "play_media",
            }.get(intent, intent.lower())
            rows.append(
                f"- name: {kind}\n  sentences:\n    - {text}\n  nlu_expect:\n    intents:\n      - intent: {intent}\n"
            )
        (dest / "representative.yaml").write_text("".join(rows), encoding="utf-8")
    write_speech_locale(generated)
    write_ha_translations()
    print("registry", len(registry), "languages")


def write_speech_locale(generated: list[dict]) -> None:
    packs = dict(HAND_BUNDLES)
    shots: dict[str, dict[str, str]] = {
        "de": {},
        "en": {},
    }
    for lang in generated:
        bundle = locale_bundle(lang)
        packs[lang["code"]] = bundle
        shots[lang["code"]] = refine_shot_rows(bundle)
    dest = Path(__file__).resolve().parents[2] / "custom_components" / "klar_nlu" / "speech_locale.py"
    dest.write_text(
        "# @generated by scripts/lang_packs. DO NOT EDIT.\n\n"
        f"SPEECH_PACKS = {repr(packs)}\n\n"
        f"REFINE_SHOTS = {repr(shots)}\n",
        encoding="utf-8",
    )
    print("wrote speech_locale", dest)


def refine_shot_rows(bundle: dict) -> dict[str, str]:
    on = (bundle.get("turn_on") or "{target}.").replace("{target}", "X")
    off = (bundle.get("turn_off") or "{target}.").replace("{target}", "X")
    temp = (bundle.get("get_temp") or "{loc}").replace("{loc}", "Y")
    personality = bundle.get("personality") or {}
    rows = {
        "default": f"{on} → {on}\n{off} → {off}\n{temp} → {temp}",
    }
    for key in PERSONALITY_KEYS:
        variants = list(personality.get(key) or ["", "", ""])
        while len(variants) < 3:
            variants.append("")
        rows[key] = "\n".join(
            (
                f"{on} → {variants[0]}{on}",
                f"{off} → {off}",
                f"{temp} → {(variants[0] if not variants[2] else variants[2])}{temp}",
            )
        )
    return rows


if __name__ == "__main__":
    main()
