#!/usr/bin/env python3
"""Generate compiled Assist language packs (not de/en)."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lang_packs.emit import write_pack, write_registry
from lang_packs.expand import expand
from lang_packs.lexicons import ALL_CORES, BUILTINS


def main() -> None:
    generated = [expand(core) for core in ALL_CORES]
    for lang in generated:
        write_pack(lang)
        print("wrote", lang["code"])
    registry = BUILTINS + generated
    write_registry(registry)
    smoke = Path(__file__).resolve().parents[2] / "tests" / "assist_langs.rs"
    cases = []
    for code, text, intent in (
        ("de", "licht wohnzimmer an", "HassTurnOn"),
        ("de", "licht kuche aus", "HassTurnOff"),
        ("en", "turn on the living room light", "HassTurnOn"),
        ("en", "turn off the kitchen light", "HassTurnOff"),
    ):
        cases.append(f'    ("{code}", "{text}", "{intent}"),')
    for lang in generated:
        for text, intent in lang.get("smoke", []):
            cases.append(f'    ("{lang["code"]}", "{text}", "{intent}"),')
    smoke.write_text(
        """// @generated by scripts/lang_packs. DO NOT EDIT.
use klar_nlu::home::default_home;
use klar_nlu::nlu::parse;
use klar_nlu::session::Session;
use klar_nlu::types::{ParseDecision, Settings};

const CASES: &[(&str, &str, &str)] = &[
"""
        + "\n".join(cases)
        + """
];

#[test]
fn compiled_assist_packs_execute_home_commands() {
    let home = default_home();
    for (lang, text, intent) in CASES {
        assert_ne!(*lang, "ru", "russian is not shipped");
        let settings = Settings { languages: vec![(*lang).into()], ..Settings::default() };
        let mut session = Session::default();
        let outcome = parse(text, &home, &mut session, &[], &settings);
        let names: Vec<_> =
            outcome.plan.as_ref().map(|plan| plan.intents().into_iter().map(|item| item.name).collect()).unwrap_or_default();
        assert!(
            matches!(outcome.decision, ParseDecision::Execute) && names.iter().any(|name| name == intent),
            "{lang} {text} decision={:?} intents={names:?}",
            outcome.decision
        );
    }
}

#[test]
fn russian_is_not_a_compiled_pack() {
    assert!(klar_nlu::lang::LangId::from_code("ru").is_none());
    assert!(!klar_nlu::lang::LangId::all().iter().any(|id| id.code() == "ru"));
}
""",
        encoding="utf-8",
    )
    datasets = Path(__file__).resolve().parents[2] / "tests" / "datasets" / "assist"
    for lang in generated:
        dest = datasets / lang["code"]
        dest.mkdir(parents=True, exist_ok=True)
        rows = []
        for text, intent in lang.get("smoke", []):
            kind = "light_on" if intent == "HassTurnOn" else "light_off"
            rows.append(
                f"- name: {kind}\n  sentences:\n    - {text}\n  nlu_expect:\n    intents:\n      - intent: {intent}\n"
            )
        (dest / "representative.yaml").write_text("".join(rows), encoding="utf-8")
    print("registry", len(registry), "languages")


if __name__ == "__main__":
    main()
