"""HA UI copy recovered for Nordic Assist locales."""

from __future__ import annotations

EUROPE_NORTH: dict[str, dict[str, str]] = {
    "da": {
        "user_desc": 'Denne integration taler med Assist. En separat motor fortolker tale: Klar NLU-appen, denne medfølgende proces eller Docker. På Home Assistant OS skal du også installere appen og vælge Brug Klar NLU-appen. Uden app startes den medfølgende motor. Kør ikke begge.',
        "mode": 'Motor',
        "channel": 'Udgivelseskanal',
        "url": 'Klar-API-URL',
        "token": 'Skrivetoken',
        "invalid": 'URL skal være http(s) uden brugernavn.',
        "already": 'Klar NLU er allerede konfigureret',
        "opt_desc": 'Personligheden gemmes her og overlever geninstallation af Klar-appen.',
        "personality": 'Personlighed',
        "languages": 'Sprog',
        "fallback": 'Samtaleagent til smalltalk',
        "refine_speech": 'Lad LLM omskrive NLU-svar',
        "refine_prompt": 'Forfiningsprompt',
        "assist_filter": 'Styr kun enheder synlige for Assist',
        "nlu_rag": 'NLU-RAG (valgfrit)',
        "quiet_ack": 'Kort bekræftelse (klokke)',
        "help_personality": 'Ligger i denne integration, ikke i Klar-appen.',
        "help_refine_speech": 'Klar styrer stadig enhederne. Fallback-LLM omskriver svaret.',
        "help_refine_prompt": 'Systemprompt til stemmen. Ingen enhedsstyring, ingen nye fakta, samme sprog.',
        "help_token": 'Samme token som i Klar-appen.',
        "help_assist": 'Til: kun det Assist må se. Fra: også skjulte enheder.',
        "help_rag": 'Fra som standard. Ved chat sendes kun det genkendte udsnit til fallback-modellen.',
        "help_quiet": 'Ved simpelt lys eller kontakt tænd/sluk ingen sætning, kun en kort tone.',
        "help_languages": 'Standard er Home Assistants systemsprog.',
        "help_channel": 'Når som helst. Staging peger på Klar NLU (Staging).',
        "local": 'Start den medfølgende motor (kun HACS)',
        "remote": 'Brug Klar NLU-appen eller Docker',
        "stable": 'Stable (produktion)',
        "staging": 'Staging (releasekandidat)',
        "system": 'Systemsprog',
        "all": 'Alle sprog',
        "normal": 'Normal',
        "casual": 'Afslappet',
        "caring": 'Omsorgsfuld',
        "grumpy": 'Gnaven',
        "sarcastic": 'Sarkastisk',
        "pirate": 'Pirat',
        "quiet_name": 'Kort bekræftelse',
        "heard": 'Sidst hørt',
        "decision": 'Sidste beslutning',
        "speech": 'Sidste svar',
        "area": 'Hørt i',
        "down_title": 'Klar-motor stoppet',
        "down_desc": 'Den medfølgende Klar-proces kører ikke. Genindlæs Klar NLU under Indstillinger → Enheder og tjenester.',
    },
    "nb": {
        "user_desc": 'Denne integrasjonen snakker med Assist. En egen motor tolker tale: Klar NLU-appen, denne medfølgende prosessen eller Docker. På Home Assistant OS, installer også appen og velg Bruk Klar NLU-appen. Uten app, start den medfølgende motoren. Ikke kjør begge.',
        "mode": 'Motor',
        "channel": 'Utgivelseskanal',
        "url": 'Klar-API-URL',
        "token": 'Skrivetoken',
        "invalid": 'URL må være http(s) uten brukernavn.',
        "already": 'Klar NLU er allerede satt opp',
        "opt_desc": 'Personligheten lagres her og overlever reinstallasjon av Klar-appen.',
        "personality": 'Personlighet',
        "languages": 'Språk',
        "fallback": 'Samtaleagent for småprat',
        "refine_speech": 'La LLM omskrive NLU-svar',
        "refine_prompt": 'Forbedringsprompt',
        "assist_filter": 'Styr bare enheter som er synlige for Assist',
        "nlu_rag": 'NLU-RAG (valgfritt)',
        "quiet_ack": 'Kort bekreftelse (ding)',
        "help_personality": 'Ligger i denne integrasjonen, ikke i Klar-appen.',
        "help_refine_speech": 'Klar styrer fortsatt enhetene. Reserve-LLM omskriver svaret.',
        "help_refine_prompt": 'Systemprompt for stemmen. Ingen enhetsstyring, ingen nye fakta, samme språk.',
        "help_token": 'Samme token som i Klar-appen.',
        "help_assist": 'På: bare det Assist kan se. Av: også skjulte enheter.',
        "help_rag": 'Av som standard. Ved prat sendes bare det gjenkjente utsnittet til reservemodellen.',
        "help_quiet": 'Ved enkelt lys eller bryter av/på ingen setning, bare en kort tone.',
        "help_languages": 'Standard er Home Assistants systemspråk.',
        "help_channel": 'Når som helst. Staging peker på Klar NLU (Staging).',
        "local": 'Start den medfølgende motoren (kun HACS)',
        "remote": 'Bruk Klar NLU-appen eller Docker',
        "stable": 'Stable (produksjon)',
        "staging": 'Staging (utgivelseskandidat)',
        "system": 'Systemspråk',
        "all": 'Alle språk',
        "normal": 'Normal',
        "casual": 'Uformell',
        "caring": 'Omsorgsfull',
        "grumpy": 'Gretten',
        "sarcastic": 'Sarkastisk',
        "pirate": 'Pirat',
        "quiet_name": 'Kort bekreftelse',
        "heard": 'Sist hørt',
        "decision": 'Siste beslutning',
        "speech": 'Siste svar',
        "area": 'Hørt i',
        "down_title": 'Klar-motor stoppet',
        "down_desc": 'Den medfølgende Klar-prosessen kjører ikke. Last Klar NLU på nytt under Innstillinger → Enheter og tjenester.',
    },
    "sv": {
        "user_desc": 'Den här integrationen pratar med Assist. En separat motor tolkar tal: Klar NLU-appen, den här medföljande processen eller Docker. På Home Assistant OS, installera även appen och välj Använd Klar NLU-appen. Utan app, starta den medföljande motorn. Kör inte båda.',
        "mode": 'Motor',
        "channel": 'Utgivningskanal',
        "url": 'Klar-API-URL',
        "token": 'Skrivtoken',
        "invalid": 'URL måste vara http(s) utan användarnamn.',
        "already": 'Klar NLU är redan konfigurerad',
        "opt_desc": 'Personligheten sparas här och överlever ominstallation av Klar-appen.',
        "personality": 'Personlighet',
        "languages": 'Språk',
        "fallback": 'Konversationsagent för smalltalk',
        "refine_speech": 'Låt LLM skriva om NLU-svar',
        "refine_prompt": 'Förfiningsprompt',
        "assist_filter": 'Styr bara enheter som Assist får se',
        "nlu_rag": 'NLU-RAG (valfritt)',
        "quiet_ack": 'Kort bekräftelse (pling)',
        "help_personality": 'Ligger i den här integrationen, inte i Klar-appen.',
        "help_refine_speech": 'Klar styr fortfarande enheterna. Reserv-LLM skriver om svaret.',
        "help_refine_prompt": 'Systemprompt för rösten. Ingen enhetsstyrning, inga nya fakta, samma språk.',
        "help_token": 'Samma token som i Klar-appen.',
        "help_assist": 'På: bara det Assist får se. Av: även dolda enheter.',
        "help_rag": 'Av som standard. Vid chatt skickas bara det igenkända utsnittet till reservmodellen.',
        "help_quiet": 'Vid enkel ljus- eller brytarkommando ingen mening, bara en kort ton.',
        "help_languages": 'Standard är Home Assistants systemspråk.',
        "help_channel": 'När som helst. Staging pekar på Klar NLU (Staging).',
        "local": 'Starta den medföljande motorn (endast HACS)',
        "remote": 'Använd Klar NLU-appen eller Docker',
        "stable": 'Stable (produktion)',
        "staging": 'Staging (releasekandidat)',
        "system": 'Systemspråk',
        "all": 'Alla språk',
        "normal": 'Normal',
        "casual": 'Avslappnad',
        "caring": 'Omsorgsfull',
        "grumpy": 'Grinig',
        "sarcastic": 'Sarkastisk',
        "pirate": 'Pirat',
        "quiet_name": 'Kort bekräftelse',
        "heard": 'Senast hörts',
        "decision": 'Senaste beslut',
        "speech": 'Senaste svar',
        "area": 'Hördes i',
        "down_title": 'Klar-motorn stoppad',
        "down_desc": 'Den medföljande Klar-processen körs inte. Ladda om Klar NLU under Inställningar → Enheter och tjänster.',
    },
    "fi": {
        "user_desc": 'Tämä integraatio puhuu Assistille. Erillinen moottori tulkitsee puheen: Klar NLU -sovellus, tämä mukana tuleva prosessi tai Docker. Home Assistant OS:ssä asenna myös sovellus ja valitse Käytä Klar NLU -sovellusta. Ilman sovellusta käynnistä mukana tuleva moottori. Älä käytä molempia.',
        "mode": 'Moottori',
        "channel": 'Julkaisukanava',
        "url": 'Klar-API:n URL',
        "token": 'Kirjoituspoletti',
        "invalid": 'URL:n on oltava http(s) ilman käyttäjätunnusta.',
        "already": 'Klar NLU on jo määritetty',
        "opt_desc": 'Persoonallisuus tallennetaan tähän ja säilyy Klar-sovelluksen uudelleenasennuksen jälkeen.',
        "personality": 'Persoonallisuus',
        "languages": 'Kielet',
        "fallback": 'Keskusteluagentti small talkiin',
        "refine_speech": 'Anna LLM:n muotoilla NLU-vastaukset',
        "refine_prompt": 'Viimeistelykehote',
        "assist_filter": 'Ohjaa vain Assistille näkyviä entiteettejä',
        "nlu_rag": 'NLU-RAG (valinnainen)',
        "quiet_ack": 'Lyhyt vahvistus (kello)',
        "help_personality": 'Tässä integraatiossa, ei Klar-sovelluksessa.',
        "help_refine_speech": 'Klar ohjaa edelleen laitteita. Varalla oleva LLM muotoilee vastauksen.',
        "help_refine_prompt": 'Äänen järjestelmäkehote. Ei laiteohjausta, ei uusia faktoja, sama kieli.',
        "help_token": 'Sama poletti kuin Klar-sovelluksessa.',
        "help_assist": 'Päällä: vain se mitä Assist saa nähdä. Pois: myös piilotetut.',
        "help_rag": 'Oletuksena pois. Keskustelussa vain tunnistettu ote menee varamalliin.',
        "help_quiet": 'Yksinkertaisessa valon tai kytkimen päälle/pois-komennossa ei lausetta, vain lyhyt ääni.',
        "help_languages": 'Oletus on Home Assistantin järjestelmäkieli.',
        "help_channel": 'Milloin tahansa. Staging osoittaa Klar NLU (Staging) -palveluun.',
        "local": 'Käynnistä mukana tuleva moottori (vain HACS)',
        "remote": 'Käytä Klar NLU -sovellusta tai Dockeria',
        "stable": 'Stable (tuotanto)',
        "staging": 'Staging (ehdokas)',
        "system": 'Järjestelmäkieli',
        "all": 'Kaikki kielet',
        "normal": 'Tavallinen',
        "casual": 'Rento',
        "caring": 'Huolehtiva',
        "grumpy": 'Äksy',
        "sarcastic": 'Sarkastinen',
        "pirate": 'Piraatti',
        "quiet_name": 'Lyhyt vahvistus',
        "heard": 'Viimeksi kuultu',
        "decision": 'Viimeinen päätös',
        "speech": 'Viimeinen vastaus',
        "area": 'Kuultu alueella',
        "down_title": 'Klar-moottori pysähtyi',
        "down_desc": 'Mukana tuleva Klar-prosessi ei ole käynnissä. Lataa Klar NLU uudelleen kohdasta Asetukset → Laitteet ja palvelut.',
    },
    "pl": {
        "user_desc": 'Ta integracja rozmawia z Assist. Osobny silnik analizuje mowę: aplikacja Klar NLU, ten dołączony proces albo Docker. W Home Assistant OS zainstaluj też aplikację i wybierz Użyj aplikacji Klar NLU. Bez aplikacji uruchom dołączony silnik. Nie uruchamiaj obu.',
        "mode": 'Silnik',
        "channel": 'Kanał wydań',
        "url": 'URL API Klar',
        "token": 'Token zapisu',
        "invalid": 'URL musi być http(s), bez nazwy użytkownika.',
        "already": 'Klar NLU jest już skonfigurowane',
        "opt_desc": 'Osobowość jest zapisana tutaj i przetrwa reinstalację aplikacji Klar.',
        "personality": 'Osobowość',
        "languages": 'Języki',
        "fallback": 'Agent rozmowy do pogawędki',
        "refine_speech": 'Pozwól LLM przerobić odpowiedzi NLU',
        "refine_prompt": 'Prompt dopracowania',
        "assist_filter": 'Steruj tylko encjami widocznymi dla Assist',
        "nlu_rag": 'NLU-RAG (opcjonalnie)',
        "quiet_ack": 'Krótkie potwierdzenie (dźwięk)',
        "help_personality": 'Jest w tej integracji, nie w aplikacji Klar.',
        "help_refine_speech": 'Klar nadal steruje urządzeniami. Zapasowy LLM przerabia odpowiedź.',
        "help_refine_prompt": 'Prompt systemowy głosu. Bez sterowania urządzeniami, bez nowych faktów, ten sam język.',
        "help_token": 'Ten sam token co w aplikacji Klar.',
        "help_assist": 'Wł.: tylko to, co Assist może widzieć. Wył.: także ukryte encje.',
        "help_rag": 'Domyślnie wył. Przy czacie tylko rozpoznany fragment idzie do modelu zapasowego.',
        "help_quiet": 'Przy prostym włączeniu lub wyłączeniu światła brak zdania, tylko krótki dźwięk.',
        "help_languages": 'Domyślnie język systemu Home Assistant.',
        "help_channel": 'W każdej chwili. Staging wskazuje na Klar NLU (Staging).',
        "local": 'Uruchom dołączony silnik (tylko HACS)',
        "remote": 'Użyj aplikacji Klar NLU lub Dockera',
        "stable": 'Stable (produkcja)',
        "staging": 'Staging (kandydat)',
        "system": 'Język systemu',
        "all": 'Wszystkie języki',
        "normal": 'Zwykła',
        "casual": 'Swobodna',
        "caring": 'Troskliwa',
        "grumpy": 'Zrzędliwa',
        "sarcastic": 'Sarkastyczna',
        "pirate": 'Pirat',
        "quiet_name": 'Krótkie potwierdzenie',
        "heard": 'Ostatnio usłyszane',
        "decision": 'Ostatnia decyzja',
        "speech": 'Ostatnia odpowiedź',
        "area": 'Usłyszane w',
        "down_title": 'Silnik Klar zatrzymany',
        "down_desc": 'Dołączony proces Klar nie działa. Przeładuj Klar NLU w Ustawienia → Urządzenia i usługi.',
    },
    "cs": {
        "user_desc": 'Tato integrace mluví s Assist. Samostatný engine zpracovává řeč: aplikace Klar NLU, tento přibalený proces nebo Docker. V Home Assistant OS nainstalujte i aplikaci a zvolte Použít aplikaci Klar NLU. Bez aplikace spusťte přibalený engine. Nespouštějte obojí.',
        "mode": 'Engine',
        "channel": 'Kanál vydání',
        "url": 'URL Klar API',
        "token": 'Zapisovací token',
        "invalid": 'URL musí být http(s) bez uživatelského jména.',
        "already": 'Klar NLU už je nastavené',
        "opt_desc": 'Osobnost je uložená tady a přežije přeinstalaci aplikace Klar.',
        "personality": 'Osobnost',
        "languages": 'Jazyky',
        "fallback": 'Konverzační agent pro pokec',
        "refine_speech": 'Nechat LLM upravit odpovědi NLU',
        "refine_prompt": 'Prompt pro úpravu',
        "assist_filter": 'Ovládat jen entity viditelné pro Assist',
        "nlu_rag": 'NLU-RAG (volitelné)',
        "quiet_ack": 'Krátké potvrzení (zvonek)',
        "help_personality": 'Je v této integraci, ne v aplikaci Klar.',
        "help_refine_speech": 'Klar dál ovládá zařízení. Záložní LLM upraví odpověď.',
        "help_refine_prompt": 'Systémový prompt hlasu. Bez ovládání zařízení, bez nových faktů, stejný jazyk.',
        "help_token": 'Stejný token jako v aplikaci Klar.',
        "help_assist": 'Zapnuto: jen to, co Assist smí vidět. Vypnuto: i skryté entity.',
        "help_rag": 'Ve výchozím stavu vypnuto. V chatu jde na záložní model jen rozpoznaný úsek.',
        "help_quiet": 'U jednoduchého zapnutí nebo vypnutí světla žádná věta, jen krátký tón.',
        "help_languages": 'Výchozí je systémový jazyk Home Assistantu.',
        "help_channel": 'Kdykoli. Staging míří na Klar NLU (Staging).',
        "local": 'Spustit přibalený engine (jen HACS)',
        "remote": 'Použít aplikaci Klar NLU nebo Docker',
        "stable": 'Stable (produkce)',
        "staging": 'Staging (kandidát)',
        "system": 'Jazyk systému',
        "all": 'Všechny jazyky',
        "normal": 'Běžná',
        "casual": 'Uvolněná',
        "caring": 'Pečující',
        "grumpy": 'Mrzutá',
        "sarcastic": 'Sarkastická',
        "pirate": 'Pirát',
        "quiet_name": 'Krátké potvrzení',
        "heard": 'Naposledy slyšeno',
        "decision": 'Poslední rozhodnutí',
        "speech": 'Poslední odpověď',
        "area": 'Slyšeno v',
        "down_title": 'Klar engine zastaven',
        "down_desc": 'Přibalený proces Klar neběží. Znovu načtěte Klar NLU v Nastavení → Zařízení a služby.',
    },
    "ca": {
        "user_desc": 'Aquesta integració parla amb Assist. Un motor separat analitza la veu: l’app Klar NLU, aquest procés inclòs o Docker. A Home Assistant OS instal·leu també l’app i trieu Fer servir l’app Klar NLU. Sense app, inicieu el motor inclòs. No executeu tots dos.',
        "mode": 'Motor',
        "channel": 'Canal de publicació',
        "url": 'URL de l’API Klar',
        "token": 'Testimoni d’escriptura',
        "invalid": 'L’URL ha de ser http(s), sense usuari.',
        "already": 'Klar NLU ja està configurat',
        "opt_desc": 'La personalitat es desa aquí i sobreviu a la reinstal·lació de l’app Klar.',
        "personality": 'Personalitat',
        "languages": 'Llengües',
        "fallback": 'Agent de conversa per a xerrameca',
        "refine_speech": "Deixar que l'LLM reformuli les respostes NLU",
        "refine_prompt": 'Indicació de refinament',
        "assist_filter": 'Controlar només entitats exposades a Assist',
        "nlu_rag": 'NLU-RAG (opcional)',
        "quiet_ack": 'Confirmació breu (timbre)',
        "help_personality": 'És en aquesta integració, no a l’app Klar.',
        "help_refine_speech": "Klar continua controlant els aparells. L'LLM de reserva reformula la resposta.",
        "help_refine_prompt": 'Indicació de sistema de la veu. Sense control d’aparells, sense fets nous, mateixa llengua.',
        "help_token": 'El mateix testimoni que a l’app Klar.',
        "help_assist": 'Activat: només el que Assist pot veure. Desactivat: també entitats ocultes.',
        "help_rag": 'Desactivat per defecte. Al xat només el fragment reconegut va al model de reserva.',
        "help_quiet": 'En encendre o apagar simple, sense frase: només un timbre curt al satèl·lit.',
        "help_languages": 'Per defecte, la llengua del sistema de Home Assistant.',
        "help_channel": 'En qualsevol moment. Staging apunta a Klar NLU (Staging).',
        "local": 'Iniciar el motor inclòs (només HACS)',
        "remote": 'Fer servir l’app Klar NLU o Docker',
        "stable": 'Stable (producció)',
        "staging": 'Staging (candidat)',
        "system": 'Llengua del sistema',
        "all": 'Totes les llengües',
        "normal": 'Normal',
        "casual": 'Informal',
        "caring": 'Atenta',
        "grumpy": 'Rondinaire',
        "sarcastic": 'Sarcastica',
        "pirate": 'Pirata',
        "quiet_name": 'Confirmació breu',
        "heard": 'Darrera escolta',
        "decision": 'Darrera decisió',
        "speech": 'Darrera resposta',
        "area": 'Escoltat a',
        "down_title": 'Motor Klar aturat',
        "down_desc": 'El procés Klar inclòs no s’està executant. Torneu a carregar Klar NLU a Configuració → Dispositius i serveis.',
    },
}
