"""West Slavic, South Slavic, Greek, Hungarian, Ukrainian, Bulgarian."""

from __future__ import annotations

from lang_packs.core import pack


def slavic() -> list[dict]:
    return [
        pack(
            "cs",
            "Čeština",
            ["cs", "cs-CZ"],
            on=["zapni"],
            off=["vypni"],
            open_=["otevri"],
            close=["zavri"],
            query=["co", "jak"],
            set_=["nastav"],
            light=["svetlo"],
            cover=["zaves"],
            climate=["topeni", "teplota", "klima"],
            media=["televize", "hudba"],
            lock=["zamek"],
            door=["dvere"],
            timer=["casovac"],
            list_=["seznam"],
            fan=["ventilator"],
            vacuum=["vysavac"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["a"],
            or_=["nebo"],
            yes=["ano", "ok"],
            all_=["vse"],
            extra_w={
                "play": ["play", "pust"],
                "pause": ["pause"],
                "lock_v": ["zamkni"],
                "unlock": ["odemkni"],
                "add": ["pridej"],
                "done": ["hotovo"],
                "minutes": ["minut", "minuty"],
            },
            extra_verbs=[("next", "Next"), ("dalsi", "Next")],
            living="obyvak",
            kitchen="kuchyne",
            unknown="Zapni svetlo v obyvaku.",
            need_on="Co zapnout?",
            need_off="Co vypnout?",
            confirm="Mam to opravdu udelat?",
            numbers=["nula", "jedna", "dva", "tri", "ctyri", "pet", "sest", "sedm", "osm", "devet", "deset", "jedenact", "dvanact", "trinact", "ctrnact", "patnact", "sestnact", "sedmnact", "osmnact", "devatenact", "dvacet", "tricet", "ctyricet", "padesat", "sedesat", "sedmdesat", "osmdesat", "devadesat", "sto"],
            colors=[("cervena", "red"), ("modra", "blue"), ("zelena", "green"), ("zluta", "yellow"), ("oranzova", "orange"), ("ruzova", "pink"), ("cerna", "black"), ("bila", "white"), ("fialova", "purple")],
            and_join=" a ",
            or_join=" nebo ",
        ),
        pack(
            "sk",
            "Slovenčina",
            ["sk", "sk-SK"],
            on=["zapni"],
            off=["vypni"],
            open_=["otvor"],
            close=["zatvor"],
            query=["co", "ako"],
            set_=["nastav"],
            light=["svetlo"],
            cover=["zaves"],
            climate=["kurenie", "teplota"],
            media=["televizia", "hudba"],
            lock=["zamok"],
            door=["dvere"],
            timer=["casovac"],
            list_=["zoznam"],
            fan=["ventilator"],
            vacuum=["vysavac"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["a"],
            or_=["alebo"],
            yes=["ano", "ok"],
            all_=["vsetko"],
            living="obyvacka",
            kitchen="kuchyne",
            unknown="Zapni svetlo v obyvacke.",
            need_on="Co zapnut?",
            need_off="Co vypnut?",
            confirm="Mam to naozaj spravit?",
            numbers=["nula", "jeden", "dva", "tri", "styri", "pat", "sest", "sedem", "osem", "devat", "desat", "jedenast", "dvanast", "trinast", "strnast", "patnast", "sestnast", "sedemnast", "osemnast", "devatnast", "dvadsat", "tridsat", "styridsat", "padest", "sestdesiat", "sedemdesiat", "osemdesiat", "devatdesiat", "sto"],
            and_join=" a ",
            or_join=" alebo ",
        ),
        pack(
            "pl",
            "Polski",
            ["pl", "pl-PL"],
            on=["wlacz"],
            off=["wylacz"],
            open_=["otworz"],
            close=["zamknij"],
            query=["co", "jak"],
            set_=["ustaw"],
            light=["swiatlo"],
            cover=["zaslona"],
            climate=["ogrzewanie", "temperatura"],
            media=["telewizor", "muzyka"],
            lock=["zamek"],
            door=["drzwi"],
            timer=["minutnik"],
            list_=["lista"],
            fan=["wentylator"],
            vacuum=["odkurzacz"],
            scene=["scena"],
            fillers=["to", "w", "na"],
            and_=["i"],
            or_=["lub"],
            yes=["tak", "ok"],
            all_=["wszystko"],
            living="salon",
            kitchen="kuchnia",
            unknown="Wlacz swiatlo w salonie.",
            need_on="Co wlaczyc?",
            need_off="Co wylaczyc?",
            confirm="Naprawde to zrobic?",
            numbers=["zero", "jeden", "dwa", "trzy", "cztery", "piec", "szesc", "siedem", "osiem", "dziewiec", "dziesiec", "jedenascie", "dwanascie", "trzynascie", "czternascie", "pietnascie", "szesnascie", "siedemnascie", "osiemnascie", "dziewietnascie", "dwadziescia", "trzydziesci", "czterdziesci", "piecdziesiat", "szescdziesiat", "siedemdziesiat", "osiemdziesiat", "dziewiecdziesiat", "sto"],
            colors=[("czerwony", "red"), ("niebieski", "blue"), ("zielony", "green"), ("zolty", "yellow"), ("pomaranczowy", "orange"), ("rozowy", "pink"), ("czarny", "black"), ("bialy", "white"), ("fioletowy", "purple")],
            and_join=" i ",
            or_join=" lub ",
        ),
        pack(
            "hu",
            "Magyar",
            ["hu", "hu-HU"],
            on=["kapcsold"],
            off=["oltsd"],
            open_=["nyisd"],
            close=["csukd"],
            query=["mi", "hogy"],
            set_=["allitsd"],
            light=["villany"],
            cover=["fuggony"],
            climate=["futes", "homerseklet"],
            media=["tv", "zene"],
            lock=["zar"],
            door=["ajto"],
            timer=["idomer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["porszivo"],
            scene=["jelenet"],
            fillers=["a", "az", "be"],
            and_=["es"],
            or_=["vagy"],
            yes=["igen", "ok"],
            all_=["mind"],
            living="nappali",
            kitchen="konyha",
            unknown="Kapcsold fel a villanyt a nappaliban.",
            need_on="Mit kapcsoljak?",
            need_off="Mit oltsak?",
            confirm="Tenyleg megcsinaljam?",
            numbers=["nulla", "egy", "ketto", "harom", "negy", "ot", "hat", "het", "nyolc", "kilenc", "tiz", "tizenegy", "tizenketto", "tizenharom", "tizennegy", "tizenot", "tizenhat", "tizenhet", "tizennyolc", "tizenkilenc", "husz", "harminc", "negyven", "otven", "hatvan", "hetven", "nyolcvan", "kilencven", "szaz"],
            and_join=" es ",
            or_join=" vagy ",
        ),
        pack(
            "hr",
            "Hrvatski",
            ["hr", "hr-HR"],
            on=["upali"],
            off=["ugasi"],
            open_=["otvori"],
            close=["zatvori"],
            query=["kako", "sto"],
            set_=["stavi"],
            light=["svjetlo"],
            cover=["zavjesa"],
            climate=["grijanje", "temperatura"],
            media=["televizor", "glazba"],
            lock=["brava"],
            door=["vrata"],
            timer=["tajmer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["usisivac"],
            scene=["scena"],
            fillers=["to", "u", "na"],
            and_=["i"],
            or_=["ili"],
            yes=["da", "ok"],
            all_=["sve"],
            living="dnevni",
            kitchen="kuhinja",
            unknown="Upali svjetlo u dnevnom.",
            need_on="Sto upaliti?",
            need_off="Sto ugasiti?",
            confirm="Trebam li to stvarno?",
            numbers=["nula", "jedan", "dva", "tri", "cetiri", "pet", "sest", "sedam", "osam", "devet", "deset", "jedanaest", "dvanaest", "trinaest", "cetrnaest", "petnaest", "sesnaest", "sedamnaest", "osamnaest", "devetnaest", "dvadeset", "trideset", "cetrdeset", "pedeset", "sezdeset", "sedamdeset", "osamdeset", "devedeset", "sto"],
            and_join=" i ",
            or_join=" ili ",
        ),
        pack(
            "sl",
            "Slovenščina",
            ["sl", "sl-SI"],
            on=["prizgi"],
            off=["ugasni"],
            open_=["odpri"],
            close=["zapri"],
            query=["kaj", "kako"],
            set_=["nastavi"],
            light=["luc"],
            cover=["zavesa"],
            climate=["ogrevanje", "temperatura"],
            media=["televizor", "glasba"],
            lock=["kljucavnica"],
            door=["vrata"],
            timer=["casovnik"],
            list_=["seznam"],
            fan=["ventilator"],
            vacuum=["sesalnik"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["in"],
            or_=["ali"],
            yes=["da", "ok"],
            all_=["vse"],
            living="dnevna",
            kitchen="kuhinja",
            unknown="Prizgi luc v dnevni.",
            need_on="Kaj prizgati?",
            need_off="Kaj ugasniti?",
            confirm="Naj res naredim?",
            numbers=["nic", "ena", "dva", "tri", "stiri", "pet", "sest", "sedem", "osem", "devet", "deset", "enajst", "dvanajst", "trinajst", "stirinajst", "petnajst", "sesnajst", "sedemnajst", "osemnajst", "devetnajst", "dvajset", "trideset", "stirideset", "petdeset", "sestdeset", "sedemdeset", "osemdeset", "devetdeset", "sto"],
            and_join=" in ",
            or_join=" ali ",
        ),
        pack(
            "bg",
            "Български",
            ["bg", "bg-BG"],
            script="Cyrl",
            on=["включи"],
            off=["изключи"],
            open_=["отвори"],
            close=["затвори"],
            query=["какво", "как"],
            set_=["сложи"],
            light=["светлина"],
            cover=["завеса"],
            climate=["парно", "температура"],
            media=["телевизор", "музика"],
            lock=["ключалка"],
            door=["врата"],
            timer=["таймер"],
            list_=["списък"],
            fan=["вентилатор"],
            vacuum=["прахосмукачка"],
            scene=["сцена"],
            fillers=["в", "на", "то"],
            and_=["и"],
            or_=["или"],
            yes=["да", "ок"],
            all_=["всичко"],
            living="хол",
            kitchen="кухня",
            unknown="Включи светлината в хола.",
            need_on="Какво да включа?",
            need_off="Какво да изключа?",
            confirm="Наистина ли да го направя?",
            numbers=["нула", "едно", "две", "три", "четири", "пет", "шест", "седем", "осем", "девет", "десет", "единадесет", "дванадесет", "тринадесет", "четиринадесет", "петнадесет", "шестнадесет", "седемнадесет", "осемнадесет", "деветнадесет", "двадесет", "тридесет", "четиридесет", "петдесет", "шестдесет", "седемдесет", "осемдесет", "деветдесет", "сто"],
            and_join=" и ",
            or_join=" или ",
        ),
        pack(
            "el",
            "Ελληνικά",
            ["el", "el-GR"],
            script="Grek",
            on=["αναψε"],
            off=["σβησε"],
            open_=["ανοιξε"],
            close=["κλεισε"],
            query=["τι", "πως"],
            set_=["βαλε"],
            light=["φως"],
            cover=["κουρτινα"],
            climate=["θερμανση", "θερμοκρασια"],
            media=["τηλεοραση", "μουσικη"],
            lock=["κλειδαρια"],
            door=["πορτα"],
            timer=["χρονομετρο"],
            list_=["λιστα"],
            fan=["ανεμιστηρας"],
            vacuum=["σκουπα"],
            scene=["σκηνη"],
            fillers=["το", "στο", "την"],
            and_=["και"],
            or_=["η"],
            yes=["ναι", "οκ"],
            all_=["ολα"],
            living="σαλονι",
            kitchen="κουζινα",
            unknown="Ανοιξε το φως στο σαλονι.",
            need_on="Τι να ανοιξω;",
            need_off="Τι να κλεισω;",
            confirm="Να το κανω οντως;",
            numbers=["μηδεν", "ενα", "δυο", "τρια", "τεσσερα", "πεντε", "εξι", "επτα", "οκτω", "εννια", "δεκα", "εντεκα", "δωδεκα", "δεκατρια", "δεκατεσσερα", "δεκαπεντε", "δεκαεξι", "δεκαεπτα", "δεκαοκτω", "δεκαεννια", "εικοσι", "τριαντα", "σαραντα", "πενηντα", "εξηντα", "εβδομηντα", "ογδοντα", "ενενηντα", "εκατο"],
            extra_w={"unlock": ["ξεκλειδωσε"], "lock_v": ["κλειδωσε"]},
            and_join=" και ",
            or_join=" η ",
        ),
        pack(
            "sr",
            "Српски",
            ["sr", "sr-RS"],
            script="Cyrl",
            on=["укључи"],
            off=["искључи"],
            open_=["отвори"],
            close=["затвори"],
            query=["шта", "како"],
            set_=["стави"],
            light=["светло"],
            cover=["завеса"],
            climate=["грејање", "температура"],
            media=["телевизор", "музика"],
            lock=["брава"],
            door=["врата"],
            timer=["тајмер"],
            list_=["листа"],
            fan=["вентилатор"],
            vacuum=["усисивач"],
            scene=["сцена"],
            fillers=["у", "на", "то"],
            and_=["и"],
            or_=["или"],
            yes=["да", "ок"],
            all_=["све"],
            living="дневна",
            kitchen="кухиња",
            unknown="Укључи светло у дневној.",
            need_on="Шта да укључим?",
            need_off="Шта да искључим?",
            confirm="Да ли заиста?",
            numbers=["нула", "један", "два", "три", "четири", "пет", "шест", "седам", "осам", "девет", "десет", "једанаест", "дванаест", "тринаест", "четрнаест", "петнаест", "шеснаест", "седамнаест", "осамнаест", "деветнаест", "двадесет", "тридесет", "четрдесет", "педесет", "шездесет", "седамдесет", "осамдесет", "деведесет", "сто"],
            and_join=" и ",
            or_join=" или ",
        ),
        pack(
            "sr-Latn",
            "Srpski",
            ["sr-Latn"],
            on=["ukljuci"],
            off=["iskljuci"],
            open_=["otvori"],
            close=["zatvori"],
            query=["sta", "kako"],
            set_=["stavi"],
            light=["svetlo"],
            cover=["zavesa"],
            climate=["grejanje", "temperatura"],
            media=["televizor", "muzika"],
            lock=["brava"],
            door=["vrata"],
            timer=["tajmer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["usisivac"],
            scene=["scena"],
            fillers=["u", "na", "to"],
            and_=["i"],
            or_=["ili"],
            yes=["da", "ok"],
            all_=["sve"],
            living="dnevna",
            kitchen="kuhinja",
            unknown="Ukljuci svetlo u dnevnoj.",
            need_on="Sta da ukljucim?",
            need_off="Sta da iskljucim?",
            confirm="Da li zaista?",
            numbers=["nula", "jedan", "dva", "tri", "cetiri", "pet", "sest", "sedam", "osam", "devet", "deset", "jedanaest", "dvanaest", "trinaest", "cetrnaest", "petnaest", "sesnaest", "sedamnaest", "osamnaest", "devetnaest", "dvadeset", "trideset", "cetrdeset", "pedeset", "sezdeset", "sedamdeset", "osamdeset", "devedeset", "sto"],
            and_join=" i ",
            or_join=" ili ",
        ),
        pack(
            "uk",
            "Українська",
            ["uk", "uk-UA"],
            script="Cyrl",
            on=["увімкни"],
            off=["вимкни"],
            open_=["відкрий"],
            close=["закрий"],
            query=["що", "як"],
            set_=["постав"],
            light=["світло"],
            cover=["штора"],
            climate=["опалення", "температура"],
            media=["телевізор", "музика"],
            lock=["замок"],
            door=["двері"],
            timer=["таймер"],
            list_=["список"],
            fan=["вентилятор"],
            vacuum=["пилосос"],
            scene=["сцена"],
            fillers=["в", "на", "це"],
            and_=["і"],
            or_=["або"],
            yes=["так", "ок"],
            all_=["все"],
            living="вітальня",
            kitchen="кухня",
            unknown="Увімкни світло у вітальні.",
            need_on="Що увімкнути?",
            need_off="Що вимкнути?",
            confirm="Справді це зробити?",
            numbers=["нуль", "один", "два", "три", "чотири", "пять", "шість", "сім", "вісім", "девять", "десять", "одинадцять", "дванадцять", "тринадцять", "чотирнадцять", "пятнадцять", "шістнадцять", "сімнадцять", "вісімнадцять", "девятнадцять", "двадцять", "тридцять", "сорок", "пятдесят", "шістдесят", "сімдесят", "вісімдесят", "девяносто", "сто"],
            and_join=" і ",
            or_join=" або ",
        ),
    ]
