"""Remaining Assist lexicons with native domain words."""

from __future__ import annotations

from lang_packs.core import pack


def leftover() -> list[dict]:
    out: list[dict] = []
    for group in (_eu_west(), _baltics(), _se_asia(), _indic(), _caucasus()):
        out.extend(group)
    return out


def _eu_west() -> list[dict]:
    return [
        pack(
            "cy", "Cymraeg", ["cy"],
            on=["tro"], off=["diffodd"], open_=["agor"], close=["cau"], query=["beth"], set_=["gosod"],
            light=["golau"], cover=["llen"], climate=["gwres"], media=["teledu"], lock=["clo"], door=["drws"],
            timer=["amserydd"], list_=["rhestr"], fan=["gwyntyll"], vacuum=["sugnwr"], scene=["golygfa"],
            fillers=["y", "yn"], and_=["a"], or_=["neu"], yes=["ie"], all_=["pob"],
            living="ystafell", kitchen="cegin",
            unknown="Tro y golau yn yr ystafell.", need_on="Beth i droi ymlaen?", need_off="Beth i ddiffodd?", confirm="Wir?",
            numbers=["dim", "un", "dau", "tri", "pedwar", "pump", "chwech", "saith", "wyth", "naw", "deg", "unarddeg", "deuddeg", "triardeg", "pedwarardeg", "pymtheg", "unarsbymtheg", "dauarsbymtheg", "deunaw", "pedwararbytheg", "ugain", "degarddeg", "deugain", "degadeugain", "trigain", "degatrigain", "pedwarugain", "degapedwarugain", "cant"],
            and_join=" a ", or_join=" neu ",
        ),
        pack(
            "et", "Eesti", ["et", "et-EE"],
            on=["lulita"], off=["kustuta"], open_=["ava"], close=["sulge"], query=["mis"], set_=["sea"],
            light=["vali"], cover=["kardin"], climate=["kyte"], media=["teler"], lock=["lukk"], door=["uks"],
            timer=["taimer"], list_=["nimekiri"], fan=["ventilaator"], vacuum=["tolmuimeja"], scene=["stseen"],
            fillers=["see", "ja"], and_=["ja"], or_=["voi"], yes=["jah"], all_=["koik"],
            living="elutuba", kitchen="kook",
            unknown="Lulita elutoa vali.", need_on="Mis sisse?", need_off="Mis valja?", confirm="Kas toesti?",
            numbers=["null", "uks", "kaks", "kolm", "neli", "viis", "kuus", "seitse", "kaheksa", "uheksa", "kymme", "uksteist", "kaksteist", "kolmteist", "neliteist", "viisteist", "kuusteist", "seitseteist", "kaheksateist", "uheksateist", "kakskymmend", "kolmkymmend", "nelikymmend", "viiskymmend", "kuuskymmend", "seitsekymmend", "kaheksakymmend", "uheksakymmend", "sada"],
            and_join=" ja ", or_join=" voi ",
        ),
        pack(
            "eu", "Euskara", ["eu", "eu-ES"],
            on=["piztu"], off=["itzali"], open_=["ireki"], close=["itxi"], query=["zer"], set_=["jarri"],
            light=["argia"], cover=["gortina"], climate=["berogailu"], media=["telebista"], lock=["sarraila"], door=["atea"],
            timer=["tenporizadorea"], list_=["zerrenda"], fan=["haizagailua"], vacuum=["xurgagailua"], scene=["eszena"],
            fillers=["bat", "eta"], and_=["eta"], or_=["edo"], yes=["bai"], all_=["denak"],
            living="egongela", kitchen="sukaldea",
            unknown="Piztu egongelako argia.", need_on="Zer piztu?", need_off="Zer itzali?", confirm="Benetan?",
            numbers=["zero", "bat", "bi", "hiru", "lau", "bost", "sei", "zazpi", "zortzi", "bederatzi", "hamar", "hamaika", "hamabi", "hamahiru", "hamalau", "hamabost", "hamasei", "hamazazpi", "hemezortzi", "hemeretzi", "hogei", "hogeitahamar", "berrogei", "berrogeitahamar", "hirurogei", "hirurogeitahamar", "laurogei", "laurogeitahamar", "ehun"],
            and_join=" eta ", or_join=" edo ",
        ),
        pack(
            "ga", "Gaeilge", ["ga", "ga-IE"],
            on=["cas"], off=["much"], open_=["oscail"], close=["dun"], query=["cad"], set_=["socraigh"],
            light=["solas"], cover=["cuirtin"], climate=["teas"], media=["teilifis"], lock=["glas"], door=["doras"],
            timer=["amadoir"], list_=["liosta"], fan=["fean"], vacuum=["folusaire"], scene=["radharc"],
            fillers=["an", "sa"], and_=["agus"], or_=["no"], yes=["ta"], all_=["uile"],
            living="seomra", kitchen="cistin",
            unknown="Cas an solas sa seomra.", need_on="Cad a chasfaidh me?", need_off="Cad a mhuchfaidh me?", confirm="I ndairire?",
            numbers=["naid", "aon", "do", "tri", "ceathair", "cuig", "se", "seacht", "ocht", "naoi", "deich", "aonndead", "doceag", "triceag", "ceathairdeag", "cuigdeag", "sedeag", "seachtdead", "ochtdead", "naoideag", "fiche", "triocha", "daichead", "caoga", "seasca", "seachtod", "ochto", "nocad", "cead"],
            and_join=" agus ", or_join=" no ",
        ),
        pack(
            "gl", "Galician", ["gl", "gl-ES"],
            on=["acende"], off=["apaga"], open_=["abre"], close=["pecha"], query=["que"], set_=["pon"],
            light=["luz"], cover=["cortina"], climate=["calefaccion"], media=["tele"], lock=["pechadura"], door=["porta"],
            timer=["temporizador"], list_=["lista"], fan=["ventilador"], vacuum=["aspiradora"], scene=["escena"],
            fillers=["a", "o", "en"], and_=["e"], or_=["ou"], yes=["si"], all_=["todo"],
            living="salon", kitchen="cociña",
            unknown="Acende a luz do salon.", need_on="Que acendo?", need_off="Que apago?", confirm="De verdade?",
            numbers=["cero", "un", "dous", "tres", "catro", "cinco", "seis", "sete", "oito", "nove", "dez", "once", "doce", "trece", "catorce", "quince", "dezaseis", "dezasete", "dezaoito", "dezanove", "vinte", "trinta", "corenta", "cincuenta", "sesenta", "setenta", "oitenta", "noventa", "cen"],
            and_join=" e ", or_join=" ou ",
        ),
        pack(
            "is", "islenska", ["is", "is-IS"],
            on=["kveiktu"], off=["slokktu"], open_=["opnadu"], close=["lokadu"], query=["hvad"], set_=["settu"],
            light=["ljos"], cover=["gardina"], climate=["hiti"], media=["sjonvarp"], lock=["las"], door=["hurd"],
            timer=["timi"], list_=["listi"], fan=["viftu"], vacuum=["ryksuga"], scene=["sena"],
            fillers=["thad", "i"], and_=["og"], or_=["eda"], yes=["ja"], all_=["allt"],
            living="stofa", kitchen="eldhus",
            unknown="Kveiktu a ljosinu i stofunni.", need_on="Hvad a ad kveikja?", need_off="Hvad a ad slokkva?", confirm="I alvoru?",
            numbers=["null", "einn", "tveir", "thrir", "fjorir", "fimm", "sex", "sjo", "atta", "niu", "tiu", "ellefu", "tolf", "threttan", "fjortan", "fimtan", "sextan", "saujan", "atjan", "nitjan", "tuttugu", "thrjatiu", "fjortiu", "fimmtiu", "sextiu", "sjotiu", "attatiu", "niutiu", "hundrad"],
            and_join=" og ", or_join=" eda ",
        ),
        pack(
            "lb", "Letzebuergesch", ["lb", "lb-LU"],
            on=["maach"], off=["maachaus"], open_=["opmaachen"], close=["zoumaachen"], query=["wat"], set_=["stell"],
            light=["luucht"], cover=["riddo"], climate=["heizung"], media=["tele"], lock=["schlass"], door=["dir"],
            timer=["timer"], list_=["lescht"], fan=["ventilator"], vacuum=["staubsauger"], scene=["szen"],
            fillers=["d", "am"], and_=["an"], or_=["oder"], yes=["jo"], all_=["all"],
            living="wunnen", kitchen="kichen",
            unknown="Maach d Luucht am Wunnen un.", need_on="Wat uschalten?", need_off="Wat ausschalten?", confirm="Wierklech?",
            numbers=["null", "eent", "zwee", "drai", "veier", "fennef", "sechs", "siwen", "aacht", "neng", "zeng", "eelf", "zwielef", "draizeng", "veierzeng", "fofzeng", "siechzeng", "siwwenzeng", "uechtzeng", "nonzeng", "zwanzeg", "dresseg", "veierzeg", "fofzeg", "sechzeg", "siwwenzeg", "achtzeg", "nonzeg", "honnert"],
            extra_w={"on_particles": ["un"], "off_particles": ["aus"]},
            and_join=" an ", or_join=" oder ",
        ),
        pack(
            "kw", "kernewek", ["kw"],
            on=["enow"], off=["diffyg"], open_=["igeri"], close=["degea"], query=["pyth"], set_=["settya"],
            light=["golow"], cover=["curtayn"], climate=["tomder"], media=["pellwolok"], lock=["alhwedh"], door=["daras"],
            timer=["termyn"], list_=["rol"], fan=["gwyns"], vacuum=["sughva"], scene=["gweles"],
            fillers=["an", "yn"], and_=["ha"], or_=["po"], yes=["ya"], all_=["oll"],
            living="stafell", kitchen="kegin",
            unknown="Enow an golow yn stafell.", need_on="Pandra enowi?", need_off="Pandra dhiffygi?", confirm="Yn hwir?",
            numbers=["mann", "onan", "dew", "tri", "peswar", "pymp", "hwegh", "seyth", "eth", "naw", "dek", "udnek", "dewdhek", "trydhek", "peswardhek", "pymthek", "hwetek", "seytek", "etek", "nownsek", "ugens", "degwarnugens", "dewgens", "deghadewgens", "trigens", "deghatrigens", "peswarugens", "deghapeswarugens", "kans"],
            and_join=" ha ", or_join=" po ",
        ),
    ]


def _baltics() -> list[dict]:
    return [
        pack(
            "lt", "Lietuviu", ["lt", "lt-LT"],
            on=["ijunk"], off=["isjunk"], open_=["atidaryk"], close=["uzdaryk"], query=["kas"], set_=["nustatyk"],
            light=["sviesa"], cover=["uzuolaida"], climate=["sildymas"], media=["televizorius"], lock=["spyna"], door=["durys"],
            timer=["laikmatis"], list_=["sarasas"], fan=["ventiliatorius"], vacuum=["siurblys"], scene=["scena"],
            fillers=["tai", "ir"], and_=["ir"], or_=["arba"], yes=["taip"], all_=["viskas"],
            living="svetaine", kitchen="virtuve",
            unknown="Ijunk sviesa svetaineje.", need_on="Ka ijungti?", need_off="Ka isjungti?", confirm="Tikrai?",
            numbers=["nulis", "vienas", "du", "trys", "keturi", "penki", "sesi", "septyni", "astuoni", "devyni", "desimt", "vienuolika", "dvylika", "trylika", "keturiolika", "penkiolika", "sesiolika", "septyniolika", "astuoniolika", "devyniolika", "dvidesimt", "trisdesimt", "keturiasdesimt", "penkiasdesimt", "sesiasdesimt", "septyniasdesimt", "astuoniasdesimt", "devyniasdesimt", "simtas"],
            and_join=" ir ", or_join=" arba ",
        ),
        pack(
            "lv", "Latviesu", ["lv", "lv-LV"],
            on=["iesledz"], off=["izsledz"], open_=["atver"], close=["aizver"], query=["kas"], set_=["iestati"],
            light=["gaisma"], cover=["aizkars"], climate=["apkure"], media=["televizors"], lock=["sledzene"], door=["durvis"],
            timer=["taimeris"], list_=["saraksts"], fan=["ventilators"], vacuum=["puteklusucejs"], scene=["scena"],
            fillers=["to", "un"], and_=["un"], or_=["vai"], yes=["ja"], all_=["viss"],
            living="istaba", kitchen="virtuve",
            unknown="Iesledz gaismu istaba.", need_on="Ko ieslegt?", need_off="Ko izslegt?", confirm="Tiesam?",
            numbers=["nulle", "viens", "divi", "tris", "cetri", "pieci", "sesi", "septini", "astoni", "devini", "desmit", "vienpadsmit", "divpadsmit", "trispadsmit", "cetrpadsmit", "piecpadsmit", "sespadsmit", "septinpadsmit", "astonpadsmit", "devinpadsmit", "divdesmit", "trisdesmit", "cetrdesmit", "piecdesmit", "sesdesmit", "septindesmit", "astondesmit", "devindesmit", "simts"],
            and_join=" un ", or_join=" vai ",
        ),
    ]


def _se_asia() -> list[dict]:
    return [
        pack(
            "id", "Bahasa Indonesia", ["id", "id-ID"],
            on=["nyalakan"], off=["matikan"], open_=["buka"], close=["tutup"], query=["apa"], set_=["setel"],
            light=["lampu"], cover=["tirai"], climate=["ac"], media=["tv"], lock=["kunci"], door=["pintu"],
            timer=["timer"], list_=["daftar"], fan=["kipas"], vacuum=["vakum"], scene=["adegan"],
            fillers=["yang", "di"], and_=["dan"], or_=["atau"], yes=["ya"], all_=["semua"],
            living="ruang", kitchen="dapur",
            unknown="Nyalakan lampu ruang.", need_on="Nyalakan apa?", need_off="Matikan apa?", confirm="Benar?",
            numbers=["nol", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan", "sembilan", "sepuluh", "sebelas", "duabelas", "tigabelas", "empatbelas", "limabelas", "enambelas", "tujuhbelas", "delapanbelas", "sembilanbelas", "duapuluh", "tigapuluh", "empatpuluh", "limapuluh", "enampuluh", "tujuhpuluh", "delapanpuluh", "sembilanpuluh", "seratus"],
            and_join=" dan ", or_join=" atau ",
        ),
        pack(
            "ms", "Bahasa Melayu", ["ms", "ms-MY"],
            on=["hidupkan"], off=["matikan"], open_=["buka"], close=["tutup"], query=["apa"], set_=["tetapkan"],
            light=["lampu"], cover=["langsir"], climate=["pendingin"], media=["tv"], lock=["kunci"], door=["pintu"],
            timer=["pemasa"], list_=["senarai"], fan=["kipas"], vacuum=["vakum"], scene=["adegan"],
            fillers=["yang", "di"], and_=["dan"], or_=["atau"], yes=["ya"], all_=["semua"],
            living="ruang", kitchen="dapur",
            unknown="Hidupkan lampu ruang.", need_on="Hidupkan apa?", need_off="Matikan apa?", confirm="Betul?",
            numbers=["kosong", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "lapan", "sembilan", "sepuluh", "sebelas", "duabelas", "tigabelas", "empatbelas", "limabelas", "enambelas", "tujuhbelas", "lapanbelas", "sembilanbelas", "duapuluh", "tigapuluh", "empatpuluh", "limapuluh", "enampuluh", "tujuhpuluh", "lapanpuluh", "sembilanpuluh", "seratus"],
            and_join=" dan ", or_join=" atau ",
        ),
        pack(
            "sw", "Kiswahili", ["sw", "sw-KE"],
            on=["washa"], off=["zima"], open_=["fungua"], close=["funga"], query=["nini"], set_=["weka"],
            light=["taa"], cover=["pazia"], climate=["joto"], media=["runinga"], lock=["kufuli"], door=["mlango"],
            timer=["kipima"], list_=["orodha"], fan=["feni"], vacuum=["kifagio"], scene=["tukio"],
            fillers=["ya", "katika"], and_=["na"], or_=["au"], yes=["ndiyo"], all_=["yote"],
            living="sebuleni", kitchen="jikonini",
            unknown="Washa taa sebuleni.", need_on="Niwasha nini?", need_off="Nizime nini?", confirm="Kweli?",
            numbers=["sifuri", "moja", "mbili", "tatu", "nne", "tano", "sita", "saba", "nane", "tisa", "kumi", "kumimamoja", "kumimambili", "kumimataatu", "kumimanane", "kumimatano", "kumimasita", "kumimasaba", "kumimanane2", "kumimatisa", "ishirini", "thelathini", "arobaini", "hamsini", "sitini", "sabini", "themanini", "tisini", "mia"],
            and_join=" na ", or_join=" au ",
        ),
        pack(
            "vi", "Tieng Viet", ["vi", "vi-VN"],
            on=["bat"], off=["tat"], open_=["mo"], close=["dong"], query=["gi"], set_=["dat"],
            light=["bongden"], cover=["rem"], climate=["dieuhoa"], media=["tivi"], lock=["khoa"], door=["cua"],
            timer=["hen"], list_=["danhsach"], fan=["quat"], vacuum=["hutbui"], scene=["canh"],
            fillers=["cai", "o"], and_=["va"], or_=["hoac"], yes=["co"], all_=["tatca"],
            living="phongkhach", kitchen="bep",
            unknown="Bat den phongkhach.", need_on="Bat gi?", need_off="Tat gi?", confirm="That su?",
            numbers=["khong", "mot", "hai", "ba", "bon", "nam", "sau", "bay", "tam", "chin", "muoi", "muoimot", "muoihai", "muoiba", "muoibon", "muoinam", "muoisau", "muoibay", "muoitam", "muoichin", "haimuoi", "bamuoi", "bonmuoi", "nammuoi", "saumuoi", "baymuoi", "tammuoi", "chinmuoi", "tram"],
            and_join=" va ", or_join=" hoac ",
        ),
    ]


def _indic() -> list[dict]:
    return [
        pack(
            "hi", "Hindi", ["hi", "hi-IN"], script="Deva",
            on=["jalao"], off=["bujhao"], open_=["kholo"], close=["band"], query=["kya"], set_=["set"],
            light=["batti"], cover=["parda"], climate=["garmi"], media=["tivi"], lock=["tala"], door=["darwaza"],
            timer=["timer"], list_=["suchi"], fan=["pankha"], vacuum=["jhadu"], scene=["drishya"],
            fillers=["ko", "mein"], and_=["aur"], or_=["ya"], yes=["haan"], all_=["sab"],
            living="baithak", kitchen="rasoi",
            unknown="Baithak ki batti jalao.", need_on="Kya jalana hai?", need_off="Kya bujhana hai?", confirm="Sach mein?",
            numbers=["shunya", "ek", "do", "teen", "char", "panch", "chhah", "saat", "aath", "nau", "das", "gyarah", "barah", "terah", "chaudah", "pandrah", "solah", "satrah", "atharah", "unnis", "bees", "tees", "chalis", "pachas", "saath", "sattar", "assi", "nabbe", "sau"],
            and_join=" aur ", or_join=" ya ",
        ),
        pack(
            "bn", "Bangla", ["bn", "bn-BD"], script="Beng",
            on=["jalao"], off=["nibhao"], open_=["khol"], close=["bondho"], query=["ki"], set_=["set"],
            light=["alo"], cover=["porda"], climate=["gorom"], media=["tivi"], lock=["tala"], door=["dorja"],
            timer=["timer"], list_=["talika"], fan=["pakha"], vacuum=["jharu"], scene=["drishyo"],
            fillers=["ke", "te"], and_=["ebong"], or_=["ba"], yes=["hyan"], all_=["sob"],
            living="bosar", kitchen="ranna",
            unknown="Bosar alo jalao.", need_on="Ki jalabo?", need_off="Ki nibhabo?", confirm="Sotti?",
            numbers=["shunno", "ek", "dui", "tin", "char", "panch", "chhoy", "sat", "at", "noy", "dosh", "egaro", "baro", "tero", "choddo", "ponero", "sholo", "shotero", "atharo", "unish", "bish", "trish", "chollish", "ponchash", "shat", "shottor", "ashi", "nobboi", "sho"],
            and_join=" ebong ", or_join=" ba ",
        ),
        pack(
            "gu", "Gujarati", ["gu", "gu-IN"], script="Gujr",
            on=["chalu"], off=["bandh"], open_=["kholo"], close=["bandhkaro"], query=["shu"], set_=["set"],
            light=["prakash"], cover=["pado"], climate=["garmi"], media=["tivi"], lock=["talu"], door=["darwajo"],
            timer=["timer"], list_=["yadi"], fan=["pankho"], vacuum=["jhadu"], scene=["drashya"],
            fillers=["ne", "ma"], and_=["ane"], or_=["athva"], yes=["ha"], all_=["badhu"],
            living="orado", kitchen="rasodu",
            unknown="Orado prakash chalu karo.", need_on="Shu chalu?", need_off="Shu bandh?", confirm="Kharu?",
            numbers=["shunya", "ek", "be", "tran", "char", "panch", "chha", "sat", "ath", "nav", "das", "agiyar", "bar", "ter", "chaud", "pandar", "sol", "sattar", "adhar", "oganish", "vis", "tris", "chalis", "pachas", "sath", "sitter", "ensi", "nevu", "so"],
            and_join=" ane ", or_join=" athva ",
        ),
        pack(
            "kn", "Kannada", ["kn", "kn-IN"], script="Knda",
            on=["hachchu"], off=["arisu"], open_=["tere"], close=["muchchu"], query=["enu"], set_=["hondisu"],
            light=["belaku"], cover=["parade"], climate=["bisi"], media=["tivi"], lock=["biga"], door=["bagilu"],
            timer=["timer"], list_=["patti"], fan=["fanu"], vacuum=["gudisu"], scene=["drishya"],
            fillers=["annu", "alli"], and_=["mattu"], or_=["athava"], yes=["haudu"], all_=["ella"],
            living="hallige", kitchen="aduge",
            unknown="Hallige belaku hachchu.", need_on="Enu hachchuvudu?", need_off="Enu arisuvudu?", confirm="Nijavagi?",
            numbers=["sonne", "ondu", "eradu", "muru", "nalku", "aidu", "aru", "elu", "entu", "ombattu", "hattu", "hannondu", "hanneradu", "hadimuru", "hadinalku", "hadinaidu", "hadinaru", "hadinelu", "hadinentu", "hattombattu", "ipattu", "muvattu", "nalavattu", "aivattu", "aravattu", "eppattu", "embattu", "tombattu", "nuru"],
            and_join=" mattu ", or_join=" athava ",
        ),
        pack(
            "ml", "Malayalam", ["ml", "ml-IN"], script="Mlym",
            on=["theli"], off=["anaykku"], open_=["thurakku"], close=["adaykku"], query=["enth"], set_=["set"],
            light=["vilakku"], cover=["jada"], climate=["chudu"], media=["tivi"], lock=["poott"], door=["vathil"],
            timer=["timer"], list_=["pattika"], fan=["fan"], vacuum=["varal"], scene=["rangam"],
            fillers=["ennu", "il"], and_=["um"], or_=["allenkil"], yes=["athe"], all_=["ellam"],
            living="muriyil", kitchen="adukkala",
            unknown="Muriyil vilakku theli.", need_on="Enth thelikkanam?", need_off="Enth anaykkanam?", confirm="Sherikkum?",
            numbers=["poojyam", "onnu", "randu", "munnu", "naalu", "anchu", "aaru", "ezhu", "ettu", "onpathu", "pathu", "pathinonnu", "panthrandu", "pathimunnu", "pathinaalu", "pathinanchu", "pathinaaru", "pathinezhu", "pathinettu", "pathonpathu", "irupathu", "muppathu", "nalpathu", "anpathu", "arupathu", "ezhupathu", "enpathu", "thonnooru", "nooru"],
            and_join=" um ", or_join=" allenkil ",
        ),
        pack(
            "mr", "Marathi", ["mr", "mr-IN"], script="Deva",
            on=["chalu"], off=["band"], open_=["ughad"], close=["bandkar"], query=["kay"], set_=["set"],
            light=["diva"], cover=["padda"], climate=["ushnata"], media=["tivi"], lock=["kulup"], door=["darwaja"],
            timer=["timer"], list_=["yadi"], fan=["pankha"], vacuum=["jhadu"], scene=["drishya"],
            fillers=["la", "madhye"], and_=["ani"], or_=["kinva"], yes=["ho"], all_=["sarva"],
            living="baithak", kitchen="svayampak",
            unknown="Baithak diva chalu kar.", need_on="Kay chalu?", need_off="Kay band?", confirm="Kharokhar?",
            numbers=["shunya", "ek", "don", "tin", "char", "pach", "saha", "sat", "aath", "nau", "daha", "akra", "bara", "tera", "chauda", "pandhra", "sola", "satra", "athra", "ekonis", "vis", "tis", "chalis", "pannas", "sath", "sattar", "aishi", "navvad", "shambhar"],
            and_join=" ani ", or_join=" kinva ",
        ),
        pack(
            "ta", "Tamil", ["ta"], script="Taml",
            on=["eru"], off=["anai"], open_=["thira"], close=["moodu"], query=["enna"], set_=["amai"],
            light=["vilakku"], cover=["thirai"], climate=["veppam"], media=["tivi"], lock=["poottu"], door=["kathavu"],
            timer=["timer"], list_=["pattiyal"], fan=["visiri"], vacuum=["thudaippu"], scene=["kaatchi"],
            fillers=["ai", "il"], and_=["matrum"], or_=["allathu"], yes=["aam"], all_=["ellam"],
            living="arai", kitchen="samaiyal",
            unknown="Arai vilakku eru.", need_on="Enna erukka?", need_off="Enna anaikka?", confirm="Unmaiyil?",
            numbers=["poojyam", "onru", "irandu", "moondru", "naangu", "ainthu", "aaru", "ezhu", "ettu", "onpathu", "pathu", "pathinonru", "pannirandu", "pathimoondru", "pathinaangu", "pathinainthu", "pathinaaru", "pathinezhu", "pathinettu", "pathonpathu", "irupathu", "muppathu", "naarpathu", "aimpathu", "arupathu", "ezhupathu", "enpathu", "thonnooru", "nooru"],
            and_join=" matrum ", or_join=" allathu ",
        ),
        pack(
            "te", "Telugu", ["te", "te-IN"], script="Telu",
            on=["veliginchu"], off=["arpu"], open_=["theruvu"], close=["mooyi"], query=["emi"], set_=["set"],
            light=["velugu"], cover=["thera"], climate=["vedi"], media=["tivi"], lock=["talam"], door=["talupu"],
            timer=["timer"], list_=["jabita"], fan=["fanu"], vacuum=["udchu"], scene=["drishyam"],
            fillers=["ni", "lo"], and_=["mariyu"], or_=["leda"], yes=["avunu"], all_=["anni"],
            living="gadi", kitchen="vantagadi",
            unknown="Gadi velugu veliginchu.", need_on="Emi veliginchali?", need_off="Emi arpali?", confirm="Nijanga?",
            numbers=["sunna", "okati", "rendu", "moodu", "nalugu", "aidu", "aaru", "edu", "enimidi", "tommidi", "padi", "padakond", "pannendu", "padamudu", "padhnalugu", "padihenu", "padaharu", "padihedu", "paddenimidi", "pandommidi", "iravai", "muppai", "nalabhai", "yabhai", "aravai", "debbhai", "enabhai", "tombhai", "vanda"],
            and_join=" mariyu ", or_join=" leda ",
        ),
        pack(
            "pa", "Punjabi", ["pa"], script="Guru",
            on=["chalu"], off=["band"], open_=["kholh"], close=["bandkar"], query=["ki"], set_=["set"],
            light=["roshni"], cover=["parda"], climate=["garmi"], media=["tivi"], lock=["tala"], door=["darwaza"],
            timer=["timer"], list_=["suchi"], fan=["pakha"], vacuum=["jharu"], scene=["drish"],
            fillers=["nu", "vich"], and_=["ate"], or_=["jaan"], yes=["haan"], all_=["sabh"],
            living="vithak", kitchen="rasoi",
            unknown="Vithak di roshni chalu karo.", need_on="Ki chalu?", need_off="Ki band?", confirm="Sachmuch?",
            numbers=["sifar", "ikk", "do", "tinn", "char", "panj", "che", "satt", "atth", "nau", "das", "gyaran", "baran", "teran", "chaudan", "pandran", "solan", "sataran", "atharan", "unni", "vih", "tih", "chali", "panjah", "satth", "sattar", "assi", "nabbe", "sau"],
            and_join=" ate ", or_join=" jaan ",
        ),
        pack(
            "ne", "Nepali", ["ne", "ne-NP"], script="Deva",
            on=["bal"], off=["nibhau"], open_=["khol"], close=["banda"], query=["ke"], set_=["set"],
            light=["batti"], cover=["parda"], climate=["tato"], media=["tivi"], lock=["tala"], door=["dhoka"],
            timer=["timer"], list_=["suchi"], fan=["pankha"], vacuum=["kucho"], scene=["drishya"],
            fillers=["lai", "ma"], and_=["ra"], or_=["wa"], yes=["ho"], all_=["sabai"],
            living="baithak", kitchen="bhansa",
            unknown="Baithak ko batti bal.", need_on="Ke balne?", need_off="Ke nibhaune?", confirm="Sachai?",
            numbers=["shunya", "ek", "dui", "tin", "char", "panch", "chha", "sat", "aath", "nau", "das", "eghara", "bahra", "tehra", "chaudha", "pandhra", "sorha", "satra", "athara", "unnais", "bis", "tis", "chalis", "pachas", "sathi", "sattari", "assi", "nabbe", "saya"],
            and_join=" ra ", or_join=" wa ",
        ),
    ]


def _caucasus() -> list[dict]:
    return [
        pack(
            "hy", "Armenian", ["hy", "hy-AM"], script="Armn",
            on=["miatsu"], off=["anjatir"], open_=["batsir"], close=["pakir"], query=["inch"], set_=["dir"],
            light=["luys"], cover=["varaguyr"], climate=["jerutsum"], media=["herustatsuyts"], lock=["kogpek"], door=["dur"],
            timer=["zhamachap"], list_=["tsutsak"], fan=["odapokhich"], vacuum=["poshekul"], scene=["tesaran"],
            fillers=["y", "um"], and_=["yev"], or_=["kam"], yes=["ayo"], all_=["bolor"],
            living="hyurasenyak", kitchen="khohanots",
            unknown="Miatsu luys hyurasenyakum.", need_on="Inch miatsnem?", need_off="Inch anjatem?", confirm="Iskapes?",
            numbers=["zro", "mek", "yerku", "yerek", "chors", "hing", "vets", "yot", "ut", "iny", "tasy", "tasnmek", "tasnyerku", "tasnyerek", "tasnchors", "tasnhing", "tasnvets", "tasnyot", "tasnut", "tasniny", "ksan", "yeresun", "karrasun", "hisun", "vatsun", "yotanasun", "utsun", "innsun", "haryur"],
            and_join=" yev ", or_join=" kam ",
        ),
        pack(
            "ka", "Georgian", ["ka", "ka-GE"], script="Geor",
            on=["charte"], off=["gamorte"], open_=["gakhseni"], close=["dakhure"], query=["ra"], set_=["daayene"],
            light=["sinatle"], cover=["parda"], climate=["gatboba"], media=["televizori"], lock=["saketi"], door=["kari"],
            timer=["taimeri"], list_=["sia"], fan=["ventilatori"], vacuum=["mtversasruti"], scene=["stsena"],
            fillers=["s", "shi"], and_=["da"], or_=["an"], yes=["ki"], all_=["kvela"],
            living="misagebi", kitchen="samzareulo",
            unknown="Charte sinatle misagebshi.", need_on="Ra chavrtо?", need_off="Ra gamovrtо?", confirm="Martla?",
            numbers=["nuli", "erti", "ori", "sami", "otkhi", "khuti", "ekvsi", "shvidi", "rva", "tskhra", "ati", "tertmeti", "tormeti", "tsameti", "totkhmeti", "tkhutmeti", "tekvsmeti", "chvidmeti", "tvrameti", "tskhrameti", "otsi", "otsdaati", "ormotsi", "ormotsdaati", "samotsi", "samotsdaati", "otkhmotsi", "otkhmotsdaati", "asi"],
            and_join=" da ", or_join=" an ",
        ),
        pack(
            "mn", "Mongolian", ["mn", "mn-MN"], script="Cyrl",
            on=["asaa"], off=["untraa"], open_=["nee"], close=["khaa"], query=["yuu"], set_=["tokhiruul"],
            light=["gerel"], cover=["khoshig"], climate=["khalaalt"], media=["televiz"], lock=["tugjee"], door=["khaalga"],
            timer=["timer"], list_=["jagsaalt"], fan=["sens"], vacuum=["toos"], scene=["uzegdel"],
            fillers=["yg", "d"], and_=["ba"], or_=["esvel"], yes=["tiim"], all_=["bugd"],
            living="zochny", kitchen="galtogoo",
            unknown="Zochny gerliig asaa.", need_on="Yuu asaakh ve?", need_off="Yuu untraakh ve?", confirm="Uneheer uu?",
            numbers=["teg", "neg", "khoyor", "gurav", "dorov", "tav", "zurgaa", "doloo", "naim", "yos", "arav", "arvanneg", "arvankhoyor", "arvangurav", "arvandorov", "arvantav", "arvanzurgaa", "arvandoloo", "arvannaim", "arvanyos", "khori", "guch", "doch", "tavi", "jar", "dal", "naya", "yer", "zuu"],
            and_join=" ba ", or_join=" esvel ",
        ),
    ]
