"""Nordic, German dialects, English UK, Portuguese BR, Afrikaans."""

from __future__ import annotations

from lang_packs.core import pack


def north() -> list[dict]:
    return [
        pack(
            "da",
            "Dansk",
            ["da", "da-DK"],
            on=["taend"],
            off=["sluk"],
            open_=["aabn"],
            close=["luk"],
            query=["hvad", "hvordan"],
            set_=["saet"],
            light=["lys"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musik"],
            lock=["laas"],
            door=["doer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["stoevsuger"],
            scene=["scene"],
            fillers=["det", "en", "i"],
            and_=["og"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="stue",
            kitchen="kokken",
            unknown="Taend lyset i stuen.",
            need_on="Hvad skal taendes?",
            need_off="Hvad skal slukkes?",
            confirm="Skal jeg virkelig?",
            numbers=["nul", "en", "to", "tre", "fire", "fem", "seks", "syv", "otte", "ni", "ti", "elleve", "tolv", "tretten", "fjorten", "femten", "seksten", "sytten", "atten", "nitten", "tyve", "tredive", "fyrre", "halvtreds", "tres", "halvfjerds", "firs", "halvfems", "hundrede"],
            colors=[("rod", "red"), ("bla", "blue"), ("gron", "green"), ("gul", "yellow"), ("orange", "orange"), ("pink", "pink"), ("sort", "black"), ("hvid", "white"), ("lilla", "purple")],
            and_join=" og ",
            or_join=" eller ",
        ),
        pack(
            "nb",
            "Norsk Bokmål",
            ["nb", "nb-NO"],
            on=["skru"],
            off=["slaa"],
            open_=["apne"],
            close=["lukk"],
            query=["hva", "hvordan"],
            set_=["sett"],
            light=["lys"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musikk"],
            lock=["laas"],
            door=["dor"],
            timer=["timer"],
            list_=["liste"],
            fan=["vifte"],
            vacuum=["stovsuger"],
            scene=["scene"],
            fillers=["det", "en", "i"],
            and_=["og"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="stue",
            kitchen="kjokken",
            unknown="Slaa pa lyset i stua.",
            need_on="Hva skal skrus pa?",
            need_off="Hva skal slas av?",
            confirm="Skal jeg virkelig?",
            numbers=["null", "en", "to", "tre", "fire", "fem", "seks", "sju", "atte", "ni", "ti", "elleve", "tolv", "tretten", "fjorten", "femten", "seksten", "sytten", "atten", "nitten", "tjue", "tretti", "forti", "femti", "seksti", "sytti", "atti", "nitti", "hundre"],
            colors=[("rod", "red"), ("bla", "blue"), ("gronn", "green"), ("gul", "yellow"), ("oransje", "orange"), ("rosa", "pink"), ("svart", "black"), ("hvit", "white"), ("lilla", "purple")],
            extra_w={"on_particles": ["pa"], "off_particles": ["av"]},
            and_join=" og ",
            or_join=" eller ",
        ),
        pack(
            "sv",
            "Svenska",
            ["sv", "sv-SE"],
            on=["tand"],
            off=["slack"],
            open_=["oppna"],
            close=["stang"],
            query=["vad", "hur"],
            set_=["satt"],
            light=["ljus"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musik"],
            lock=["las"],
            door=["dorr"],
            timer=["timer"],
            list_=["lista"],
            fan=["flakt"],
            vacuum=["dammsugare"],
            scene=["scen"],
            fillers=["det", "en", "i"],
            and_=["och"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alla"],
            living="vardagsrum",
            kitchen="kok",
            unknown="Tand ljuset i vardagsrummet.",
            need_on="Vad ska tandas?",
            need_off="Vad ska slackas?",
            confirm="Ska jag verkligen?",
            numbers=["noll", "ett", "tva", "tre", "fyra", "fem", "sex", "sju", "atta", "nio", "tio", "elva", "tolv", "tretton", "fjorton", "femton", "sexton", "sjutton", "arton", "nitton", "tjugo", "trettio", "fyrtio", "femtio", "sextio", "sjuttio", "attio", "nittio", "hundra"],
            colors=[("rod", "red"), ("bla", "blue"), ("gron", "green"), ("gul", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("svart", "black"), ("vit", "white"), ("lila", "purple")],
            and_join=" och ",
            or_join=" eller ",
        ),
        pack(
            "fi",
            "Suomi",
            ["fi", "fi-FI"],
            on=["sytyta"],
            off=["sammuta"],
            open_=["avaa"],
            close=["sulje"],
            query=["mika", "miten"],
            set_=["aseta"],
            light=["valo"],
            cover=["verho"],
            climate=["lampo", "lammitys"],
            media=["tv", "musiikki"],
            lock=["lukko"],
            door=["ovi"],
            timer=["ajastin"],
            list_=["lista"],
            fan=["tuuletin"],
            vacuum=["imuri"],
            scene=["kohtaus"],
            fillers=["se", "on", "ja"],
            and_=["ja"],
            or_=["tai"],
            yes=["kylla", "ok"],
            all_=["kaikki"],
            living="olohuone",
            kitchen="keittio",
            unknown="Sytyta olohuoneen valo.",
            need_on="Mika sytytetaan?",
            need_off="Mika sammutetaan?",
            confirm="Teenko tama oikeasti?",
            numbers=["nolla", "yksi", "kaksi", "kolme", "nelja", "viisi", "kuusi", "seitseman", "kahdeksan", "yhdeksan", "kymmenen", "yksitoista", "kaksitoista", "kolmetoista", "neljatoista", "viisitoista", "kuusitoista", "seitsemantoista", "kahdeksantoista", "yhdeksantoista", "kaksikymmenta", "kolmekymmenta", "neljakymmenta", "viisikymmenta", "kuusikymmenta", "seitsemankymmenta", "kahdeksankymmenta", "yhdeksankymmenta", "sata"],
            colors=[("punainen", "red"), ("sininen", "blue"), ("vihrea", "green"), ("keltainen", "yellow"), ("oranssi", "orange"), ("vaaleanpunainen", "pink"), ("musta", "black"), ("valkoinen", "white"), ("violetti", "purple")],
            and_join=" ja ",
            or_join=" tai ",
        ),
        pack(
            "de-CH",
            "Schwyzerdütsch",
            ["de-CH"],
            on=["mach"],
            off=["loesch"],
            open_=["ufmache"],
            close=["zue"],
            query=["was", "wie"],
            set_=["stell"],
            light=["liecht"],
            cover=["store", "vorhang"],
            climate=["heizig", "temperatur"],
            media=["fernseh", "musig"],
            lock=["schloss"],
            door=["tuer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["staubsauger"],
            scene=["szene"],
            fillers=["s", "im", "d", "bitte"],
            and_=["und"],
            or_=["oder"],
            yes=["ja", "ok"],
            all_=["alli"],
            living="wohnzimmer",
            kitchen="chuchi",
            unknown="Mach s Liecht im Wohnzimmer aa.",
            need_on="Was söll i aamache?",
            need_off="Was söll i usmache?",
            confirm="Soll i das würklich mache?",
            numbers=["null", "eis", "zwai", "drue", "vier", "foif", "saechs", "sibe", "acht", "nuen", "zae", "elf", "zwoelf", "drizae", "vierzae", "fuefzae", "saechzae", "sibzae", "achtzae", "nuenzae", "zwanzg", "drissg", "vierzg", "fuefzg", "saechzg", "sibzg", "achtzg", "nuenzg", "hundert"],
            extra_w={"on_particles": ["aa"], "off_particles": ["uus"], "scenes": ["filmabend"], "named": ["kugel"], "island": ["insel"], "ceiling": ["decke"]},
            colors=[("rot", "red"), ("blau", "blue"), ("gruen", "green"), ("gelb", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("schwarz", "black"), ("weiss", "white"), ("violett", "purple")],
            and_join=" und ",
            or_join=" oder ",
        ),
        pack(
            "de-AT",
            "Deutsch (Österreich)",
            ["de-AT"],
            on=["mach"],
            off=["schalt"],
            open_=["oeffne"],
            close=["schliesse"],
            query=["was", "wie"],
            set_=["stell"],
            light=["licht", "leuchte"],
            cover=["vorhang", "jalousie"],
            climate=["heizung", "temperatur"],
            media=["fernseher", "musik"],
            lock=["schloss"],
            door=["tuer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["staubsauger"],
            scene=["szene"],
            fillers=["das", "den", "im", "bitte"],
            and_=["und"],
            or_=["oder"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="wohnzimmer",
            kitchen="kuche",
            unknown="Mach das Licht im Wohnzimmer an.",
            need_on="Was soll ich einschalten?",
            need_off="Was soll ich ausschalten?",
            confirm="Soll ich das wirklich tun?",
            numbers=["null", "eins", "zwei", "drei", "vier", "fuenf", "sechs", "sieben", "acht", "neun", "zehn", "elf", "zwoelf", "dreizehn", "vierzehn", "fuenfzehn", "sechzehn", "siebzehn", "achtzehn", "neunzehn", "zwanzig", "dreissig", "vierzig", "fuenfzig", "sechzig", "siebzig", "achtzig", "neunzig", "hundert"],
            extra_w={"on_particles": ["an"], "off_particles": ["aus"], "scenes": ["filmabend"], "named": ["kugel"], "island": ["insel"], "ceiling": ["decke", "deckenlampe"]},
            colors=[("rot", "red"), ("blau", "blue"), ("gruen", "green"), ("gelb", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("schwarz", "black"), ("weiss", "white"), ("violett", "purple")],
            and_join=" und ",
            or_join=" oder ",
        ),
        pack(
            "en-GB",
            "English (UK)",
            ["en-GB"],
            on=["enable"],
            off=["extinguish"],
            open_=["open"],
            close=["close"],
            query=["what", "how"],
            set_=["set"],
            light=["light", "bulb"],
            cover=["curtain", "blind"],
            climate=["heating", "temperature"],
            media=["telly", "music"],
            lock=["lock"],
            door=["door"],
            timer=["timer"],
            list_=["list"],
            fan=["fan"],
            vacuum=["hoover"],
            scene=["scene"],
            fillers=["the", "a", "in"],
            and_=["and"],
            or_=["or"],
            yes=["yes", "ok"],
            all_=["all"],
            living="lounge",
            kitchen="kitchen",
            unknown="Turn on the lounge light.",
            need_on="What should I turn on?",
            need_off="What should I turn off?",
            confirm="Should I really do that?",
            numbers=["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred"],
            colors=[("red", "red"), ("blue", "blue"), ("green", "green"), ("yellow", "yellow"), ("orange", "orange"), ("pink", "pink"), ("black", "black"), ("white", "white"), ("purple", "purple")],
            extra_verbs=[("colour", "Color"), ("turn", "Switch"), ("switch", "Switch"), ("on", "OnParticle"), ("off", "Off")],
            extra_w={"on_particles": ["on"], "off_particles": ["off"]},
            smoke=[("turn on the lounge light", "HassTurnOn"), ("switch off the kitchen light", "HassTurnOff")],
            and_join=" and ",
            or_join=" or ",
        ),
        pack(
            "pt-BR",
            "Português (Brasil)",
            ["pt-BR"],
            on=["liga"],
            off=["desliga"],
            open_=["abre"],
            close=["fecha"],
            query=["que", "como"],
            set_=["poe"],
            light=["luz"],
            cover=["cortina"],
            climate=["ar", "temperatura"],
            media=["tv", "musica"],
            lock=["fechadura"],
            door=["porta"],
            timer=["timer"],
            list_=["lista"],
            fan=["ventilador"],
            vacuum=["aspirador"],
            scene=["cena"],
            fillers=["a", "o", "da", "do"],
            and_=["e"],
            or_=["ou"],
            yes=["sim", "ok"],
            all_=["tudo"],
            living="sala",
            kitchen="cozinha",
            unknown="Liga a luz da sala.",
            need_on="O que ligo?",
            need_off="O que desligo?",
            confirm="Devo mesmo fazer isso?",
            numbers=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito", "nove", "dez", "onze", "doze", "treze", "catorze", "quinze", "dezesseis", "dezessete", "dezoito", "dezenove", "vinte", "trinta", "quarenta", "cinquenta", "sessenta", "setenta", "oitenta", "noventa", "cem"],
            colors=[("vermelho", "red"), ("azul", "blue"), ("verde", "green"), ("amarelo", "yellow"), ("laranja", "orange"), ("rosa", "pink"), ("preto", "black"), ("branco", "white"), ("roxo", "purple")],
            and_join=" e ",
            or_join=" ou ",
        ),
        pack(
            "af",
            "Afrikaans",
            ["af", "af-ZA"],
            on=["skakel"],
            off=["doof"],
            open_=["oop"],
            close=["toe"],
            query=["wat", "hoe"],
            set_=["stel"],
            light=["lig"],
            cover=["gordyn"],
            climate=["verwarming", "temperatuur"],
            media=["tv", "musiek"],
            lock=["slot"],
            door=["deur"],
            timer=["timer"],
            list_=["lys"],
            fan=["waaier"],
            vacuum=["stofsuier"],
            scene=["toneel"],
            fillers=["die", "n", "in"],
            and_=["en"],
            or_=["of"],
            yes=["ja", "ok"],
            all_=["almal"],
            living="sitkamer",
            kitchen="kombuis",
            unknown="Skakel die sitkamerlig aan.",
            need_on="Wat moet ek aanskakel?",
            need_off="Wat moet ek afskakel?",
            confirm="Moet ek dit regtig doen?",
            numbers=["nul", "een", "twee", "drie", "vier", "vyf", "ses", "sewe", "agt", "nege", "tien", "elf", "twaalf", "dertien", "veertien", "vyftien", "sestien", "sewentien", "agtien", "negentien", "twintig", "dertig", "veertig", "vyftig", "sestig", "sewentig", "tagtig", "negentig", "honderd"],
            extra_w={"on_particles": ["aan"], "off_particles": ["af"]},
            colors=[("rooi", "red"), ("blou", "blue"), ("groen", "green"), ("geel", "yellow"), ("oranje", "orange"), ("pienk", "pink"), ("swart", "black"), ("wit", "white"), ("pers", "purple")],
            and_join=" en ",
            or_join=" of ",
        ),
    ]
