"""CJK, RTL, Thai, Korean, Japanese, Turkish."""

from __future__ import annotations

from lang_packs.core import pack


def script() -> list[dict]:
    return [
        pack(
            "zh-CN",
            "简体中文",
            ["zh-CN", "zh"],
            script="Hans",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "的", "一下"],
            and_=["和"],
            or_=["或"],
            yes=["好", "行"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="打开客厅的灯。",
            need_on="打开什么？",
            need_off="关闭什么？",
            confirm="真的要执行吗？",
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="和",
            or_join="或",
        ),
        pack(
            "zh-TW",
            "繁體中文（台灣）",
            ["zh-TW"],
            script="Hant",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "的", "一下"],
            and_=["和"],
            or_=["或"],
            yes=["好", "行"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="打開客廳的燈。",
            need_on="打開什麼？",
            need_off="關閉什麼？",
            confirm="真的要執行嗎？",
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="和",
            or_join="或",
        ),
        pack(
            "zh-HK",
            "繁體中文（香港）",
            ["zh-HK"],
            script="Hant",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "嘅", "吓"],
            and_=["同"],
            or_=["定"],
            yes=["好", "得"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="開客廳燈。",
            need_on="開咩？",
            need_off="關咩？",
            confirm="真係要做？",
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="同",
            or_join="定",
        ),
        pack(
            "ar",
            "العربية",
            ["ar", "ar-JO"],
            script="Arab",
            on=["شغل"],
            off=["اطفئ"],
            open_=["افتح"],
            close=["اغلق"],
            query=["ايش", "كيف"],
            set_=["حط"],
            light=["ضوء"],
            cover=["ستارة"],
            climate=["تكييف", "حرارة"],
            media=["تلفاز", "موسيقى"],
            lock=["قفل"],
            door=["باب"],
            timer=["مؤقت"],
            list_=["قائمة"],
            fan=["مروحة"],
            vacuum=["مكنسة"],
            scene=["مشهد"],
            fillers=["ال", "في", "على"],
            and_=["و"],
            or_=["أو"],
            yes=["نعم", "حسنا"],
            all_=["كل"],
            living="صالون",
            kitchen="مطبخ",
            unknown="شغل الضوء في الصالون.",
            need_on="ماذا أشغل؟",
            need_off="ماذا أطفئ؟",
            confirm="هل أفعل ذلك حقا؟",
            numbers=["صفر", "واحد", "اثنان", "ثلاثة", "اربعة", "خمسة", "ستة", "سبعة", "ثمانية", "تسعة", "عشرة", "احد عشر", "اثنا عشر", "ثلاثة عشر", "اربعة عشر", "خمسة عشر", "ستة عشر", "سبعة عشر", "ثمانية عشر", "تسعة عشر", "عشرون", "ثلاثون", "اربعون", "خمسون", "ستون", "سبعون", "ثمانون", "تسعون", "مائة"],
            and_join=" و ",
            or_join=" أو ",
        ),
        pack(
            "he",
            "עברית",
            ["he", "he-IL"],
            script="Hebr",
            on=["הדלק"],
            off=["כבה"],
            open_=["פתח"],
            close=["סגור"],
            query=["מה", "איך"],
            set_=["שים"],
            light=["אור"],
            cover=["וילון"],
            climate=["חימום", "טמפרטורה"],
            media=["טלוויזיה", "מוזיקה"],
            lock=["מנעול"],
            door=["דלת"],
            timer=["טיימר"],
            list_=["רשימה"],
            fan=["מאוורר"],
            vacuum=["שואב"],
            scene=["סצנה"],
            fillers=["את", "ב", "של"],
            and_=["ו"],
            or_=["או"],
            yes=["כן", "אוקיי"],
            all_=["הכל"],
            living="סלון",
            kitchen="מטבח",
            unknown="הדלק את האור בסלון.",
            need_on="מה להדליק?",
            need_off="מה לכבות?",
            confirm="באמת לבצע?",
            numbers=["אפס", "אחת", "שתיים", "שלוש", "ארבע", "חמש", "שש", "שבע", "שמונה", "תשע", "עשר", "אחת עשרה", "שתים עשרה", "שלוש עשרה", "ארבע עשרה", "חמש עשרה", "שש עשרה", "שבע עשרה", "שמונה עשרה", "תשע עשרה", "עשרים", "שלושים", "ארבעים", "חמישים", "שישים", "שבעים", "שמונים", "תשעים", "מאה"],
            and_join=" ו ",
            or_join=" או ",
        ),
        pack(
            "fa",
            "فارسی",
            ["fa", "fa-IR"],
            script="Arab",
            on=["روشن"],
            off=["خاموش"],
            open_=["باز"],
            close=["بسته"],
            query=["چی", "چطور"],
            set_=["بگذار"],
            light=["چراغ"],
            cover=["پرده"],
            climate=["سرما", "دما"],
            media=["تلویزیون", "موسیقی"],
            lock=["قفل"],
            door=["در"],
            timer=["تایمر"],
            list_=["فهرست"],
            fan=["پنکه"],
            vacuum=["جارو"],
            scene=["صحنه"],
            fillers=["را", "در", "به"],
            and_=["و"],
            or_=["یا"],
            yes=["بله", "باشه"],
            all_=["همه"],
            living="پذیرایی",
            kitchen="آشپزخانه",
            unknown="چراغ پذیرایی را روشن کن.",
            need_on="چه چیزی روشن شود؟",
            need_off="چه چیزی خاموش شود؟",
            confirm="واقعا انجام بدهم؟",
            numbers=["صفر", "یک", "دو", "سه", "چهار", "پنج", "شش", "هفت", "هشت", "نه", "ده", "یازده", "دوازده", "سیزده", "چهارده", "پانزده", "شانزده", "هفده", "هجده", "نوزده", "بیست", "سی", "چهل", "پنجاه", "شصت", "هفتاد", "هشتاد", "نود", "صد"],
            and_join=" و ",
            or_join=" یا ",
        ),
        pack(
            "ur",
            "اُردُو",
            ["ur", "ur-IN"],
            script="Arab",
            on=["چالو"],
            off=["بند"],
            open_=["کھولو"],
            close=["بندکرو"],
            query=["کیا", "کیسے"],
            set_=["رکھو"],
            light=["روشنی"],
            cover=["پردہ"],
            climate=["گرمی", "درجہ"],
            media=["ٹی وی", "موسیقی"],
            lock=["تالا"],
            door=["دروازہ"],
            timer=["ٹائمر"],
            list_=["فہرست"],
            fan=["پنکھا"],
            vacuum=["جھاڑو"],
            scene=["منظر"],
            fillers=["کو", "میں", "کی"],
            and_=["اور"],
            or_=["یا"],
            yes=["ہاں", "ٹھیک"],
            all_=["سب"],
            living="لانج",
            kitchen="باورچی",
            unknown="لانج کی روشنی چالو کرو.",
            need_on="کیا چالو کروں؟",
            need_off="کیا بند کروں؟",
            confirm="کیا واقعی کروں؟",
            numbers=["صفر", "ایک", "دو", "تین", "چار", "پانچ", "چھ", "سات", "آٹھ", "نو", "دس", "گیارہ", "بارہ", "تیرہ", "چودہ", "پندرہ", "سولہ", "سترہ", "اٹھارہ", "انیس", "بیس", "تیس", "چالیس", "پچاس", "ساٹھ", "ستر", "اسی", "نوے", "سو"],
            and_join=" اور ",
            or_join=" یا ",
        ),
        pack(
            "tr",
            "Türkçe",
            ["tr", "tr-TR"],
            on=["yak"],
            off=["sondur"],
            open_=["ac"],
            close=["kapat"],
            query=["ne", "nasil"],
            set_=["ayarla"],
            light=["isik"],
            cover=["perde"],
            climate=["klima", "sicaklik"],
            media=["televizyon", "muzik"],
            lock=["kilit"],
            door=["kapi"],
            timer=["zamanlayici"],
            list_=["liste"],
            fan=["vantilator"],
            vacuum=["supurge"],
            scene=["sahne"],
            fillers=["bir", "de", "mi"],
            and_=["ve"],
            or_=["veya"],
            yes=["evet", "tamam"],
            all_=["hepsi"],
            living="salon",
            kitchen="mutfak",
            unknown="Salondaki isigi ac.",
            need_on="Neyi acayim?",
            need_off="Neyi kapatayim?",
            confirm="Bunu gercekten yapayim mi?",
            numbers=["sifir", "bir", "iki", "uc", "dort", "bes", "alti", "yedi", "sekiz", "dokuz", "on", "onbir", "oniki", "onuc", "ondort", "onbes", "onalti", "onyedi", "onsekiz", "ondokuz", "yirmi", "otuz", "kirk", "elli", "altmis", "yetmis", "seksen", "doksan", "yuz"],
            extra_w={"unlock": ["kilidiac"], "lock_v": ["kilitle"]},
            and_join=" ve ",
            or_join=" veya ",
        ),
        pack(
            "th",
            "ภาษาไทย",
            ["th", "th-TH"],
            script="Thai",
            on=["poetfai"],
            off=["pitfai"],
            open_=["poet"],
            close=["pit"],
            query=["arai", "yangngai"],
            set_=["tang"],
            light=["fai"],
            cover=["man"],
            climate=["air"],
            media=["thiwi", "phleng"],
            lock=["kunjae"],
            door=["pratu"],
            timer=["tangwela"],
            list_=["raikan"],
            fan=["phat"],
            vacuum=["dutfun"],
            scene=["chak"],
            fillers=["ที่", "ใน", "หน่อย"],
            and_=["และ"],
            or_=["หรือ"],
            yes=["ok", "chai"],
            all_=["ทั้งหมด"],
            living="hongnang",
            kitchen="hongkrua",
            unknown="เปิดไฟห้องนั่งเล่น",
            need_on="เปิดอะไร",
            need_off="ปิดอะไร",
            confirm="ทำจริงหรือ",
            numbers=["ศูนย์", "หนึ่ง", "สอง", "สาม", "สี่", "ห้า", "หก", "เจ็ด", "แปด", "เก้า", "สิบ", "สิบเอ็ด", "สิบสอง", "สิบสาม", "สิบสี่", "สิบห้า", "สิบหก", "สิบเจ็ด", "สิบแปด", "สิบเก้า", "ยี่สิบ", "สามสิบ", "สี่สิบ", "ห้าสิบ", "หกสิบ", "เจ็ดสิบ", "แปดสิบ", "เก้าสิบ", "ร้อย"],
            and_join=" และ ",
            or_join=" หรือ ",
        ),
        pack(
            "ko",
            "한국어",
            ["ko", "ko-KR"],
            script="Hang",
            on=["kyeo"],
            off=["kkaeo"],
            open_=["yeolo"],
            close=["dada"],
            query=["mwo", "eotteoke"],
            set_=["seoljeong"],
            light=["bul"],
            cover=["keoteun"],
            climate=["nanbang"],
            media=["tibi", "eumak"],
            lock=["jamulsoe"],
            door=["mun"],
            timer=["taimeo"],
            list_=["mongnok"],
            fan=["seonpunggi"],
            vacuum=["cheongsogi"],
            scene=["jangmyeon"],
            fillers=["을", "를", "에"],
            and_=["그리고"],
            or_=["또는"],
            yes=["응", "네"],
            all_=["모두"],
            living="geosil",
            kitchen="bueok",
            unknown="거실 불 켜",
            need_on="뭘 켤까요?",
            need_off="뭘 끌까요?",
            confirm="정말 할까요?",
            numbers=["영", "일", "이", "삼", "사", "오", "육", "칠", "팔", "구", "십", "십일", "십이", "십삼", "십사", "십오", "십육", "십칠", "십팔", "십구", "이십", "삼십", "사십", "오십", "육십", "칠십", "팔십", "구십", "백"],
            and_join=" 그리고 ",
            or_join=" 또는 ",
        ),
        pack(
            "ja",
            "日本語",
            ["ja", "ja-JP"],
            script="Jpan",
            on=["tsukete"],
            off=["keshite"],
            open_=["akete"],
            close=["shimete"],
            query=["nani", "dou"],
            set_=["setto"],
            light=["raito"],
            cover=["kaaten"],
            climate=["eakon"],
            media=["terebi", "ongaku"],
            lock=["kagi"],
            door=["doa"],
            timer=["taimaa"],
            list_=["risuto"],
            fan=["fan"],
            vacuum=["soujiki"],
            scene=["shiin"],
            fillers=["を", "に", "の"],
            and_=["と"],
            or_=["か"],
            yes=["ok", "hai"],
            all_=["全部"],
            extra_w={
                "play": ["play"],
                "pause": ["pause"],
                "add": ["add"],
                "done": ["done"],
                "minutes": ["fun", "minutes"],
            },
            extra_verbs=[("next", "Next"), ("tsugi", "Next")],
            living="ribingu",
            kitchen="kitchin",
            unknown="リビングのライトをつけて",
            need_on="何をつけますか",
            need_off="何をけしますか",
            confirm="本当に実行しますか？",
            numbers=["ゼロ", "いち", "に", "さん", "よん", "ご", "ろく", "なな", "はち", "きゅう", "じゅう", "じゅういち", "じゅうに", "じゅうさん", "じゅうよん", "じゅうご", "じゅうろく", "じゅうなな", "じゅうはち", "じゅうきゅう", "にじゅう", "さんじゅう", "よんじゅう", "ごじゅう", "ろくじゅう", "ななじゅう", "はちじゅう", "きゅうじゅう", "ひゃく"],
            and_join="と",
            or_join="か",
        ),
    ]
