"""More / Details chrome for every Assist locale."""

from __future__ import annotations

MORE: dict[str, tuple[str, str]] = {
    "af": ("Meer", "Besonderhede"),
    "ar": ("المزيد", "التفاصيل"),
    "bg": ("Още", "Подробности"),
    "bn": ("আরও", "বিস্তারিত"),
    "ca": ("Més", "Detalls"),
    "cs": ("Více", "Podrobnosti"),
    "cy": ("Mwy", "Manylion"),
    "da": ("Mere", "Detaljer"),
    "de-AT": ("Mehr", "Details"),
    "de-CH": ("Mehr", "Details"),
    "el": ("Περισσότερα", "Λεπτομέρειες"),
    "en-GB": ("More", "Details"),
    "es": ("Más", "Detalles"),
    "et": ("Veel", "Üksikasjad"),
    "eu": ("Gehiago", "Xehetasunak"),
    "fa": ("بیشتر", "جزئیات"),
    "fi": ("Lisää", "Tiedot"),
    "fr": ("Plus", "Détails"),
    "ga": ("Tuilleadh", "Sonraí"),
    "gl": ("Máis", "Detalles"),
    "gu": ("વધુ", "વિગતો"),
    "he": ("עוד", "פרטים"),
    "hi": ("और", "विवरण"),
    "hr": ("Više", "Detalji"),
    "hu": ("Több", "Részletek"),
    "hy": ("Ավելին", "Մանրամասներ"),
    "id": ("Lainnya", "Detail"),
    "is": ("Meira", "Upplýsingar"),
    "it": ("Altro", "Dettagli"),
    "ja": ("その他", "詳細"),
    "ka": ("მეტი", "დეტალები"),
    "kn": ("ಇನ್ನಷ್ಟು", "ವಿವರಗಳು"),
    "ko": ("더보기", "세부정보"),
    "kw": ("Moy", "Manylyon"),
    "lb": ("Méi", "Detailer"),
    "lt": ("Daugiau", "Išsamiau"),
    "lv": ("Vairāk", "Detaļas"),
    "ml": ("കൂടുതൽ", "വിശദാംശങ്ങൾ"),
    "mn": ("Өөр", "Дэлгэрэнгүй"),
    "mr": ("अधिक", "तपशील"),
    "ms": ("Lagi", "Butiran"),
    "nb": ("Mer", "Detaljer"),
    "ne": ("थप", "विवरण"),
    "nl": ("Meer", "Details"),
    "pa": ("ਹੋਰ", "ਵੇਰਵੇ"),
    "pl": ("Więcej", "Szczegóły"),
    "pt": ("Mais", "Detalhes"),
    "pt-BR": ("Mais", "Detalhes"),
    "ro": ("Mai mult", "Detalii"),
    "sk": ("Viac", "Podrobnosti"),
    "sl": ("Več", "Podrobnosti"),
    "sr": ("Још", "Детаљи"),
    "sr-Latn": ("Još", "Detalji"),
    "sv": ("Mer", "Detaljer"),
    "sw": ("Zaidi", "Maelezo"),
    "ta": ("மேலும்", "விவரங்கள்"),
    "te": ("మరిన్ని", "వివరాలు"),
    "th": ("เพิ่มเติม", "รายละเอียด"),
    "tr": ("Daha fazla", "Ayrıntılar"),
    "uk": ("Більше", "Подробиці"),
    "ur": ("مزید", "تفصیلات"),
    "vi": ("Thêm", "Chi tiết"),
    "zh-CN": ("更多", "详情"),
    "zh-HK": ("更多", "詳情"),
    "zh-TW": ("更多", "詳細資料"),
}


def apply_more(packs: dict[str, dict[str, str]]) -> None:
    for code, fields in packs.items():
        more, details = MORE.get(code, ("More", "Details"))
        fields["trainerMore"] = more
        fields["trainerDetails"] = details
