"""Operator UI field map. Catalogs store unique chrome; expand() fills aliases."""

from __future__ import annotations

ALIASES = {
    "dashboard": "home",
    "parse": "lab",
    "houseGraph": "graph",
    "houseDevices": "entities",
    "houseMap": "calibrate",
    "matchedRule": "addRule",
    "ragMode": "nluRag",
    "sentences": "custom",
}

CONSTANTS = {
    "unitsPercent": "%",
    "entityId": "entity_id",
    "nluRag": "House context on miss",
    "processPath": "conversation.process",
    "advancedJson": "JSON",
    "unitsUs": "µs",
    "coverageGraph": "Graph",
    "coverageAssist": "Assist",
    "coverageReady": "ready",
    "coverageOpen": "open",
    "undoLastCommand": "Undo last command",
    "applyDone": "Applied {count} room suggestions",
    "applyUndone": "Room suggestions undone",
    "applyUndoFailed": "Could not undo room suggestions",
    "modeFull": "Resolve devices",
    "modeContext": "Rooms only",
    "engineHint": "Mode binds devices or rooms only. House context on a miss is optional.",
    "inLab": "In Lab",
    "operatorLanguage": "Operator language",
    "operatorLanguageHint": "This app only. Saved here, or KLAR_UI_LOCALE before the first save. Not Assist, not the Home Assistant profile.",
}

CATALOG_KEYS = (
    "home",
    "conversations",
    "rules",
    "house",
    "lab",
    "graph",
    "calibrate",
    "entities",
    "custom",
    "settings",
    "open",
    "bundleOn",
    "bundleOff",
    "engineReady",
    "understandsHome",
    "assistVisible",
    "certain",
    "needsWork",
    "recordings",
    "processed",
    "coverage",
    "confidence",
    "domains",
    "rooms",
    "recent",
    "replay",
    "applyAll",
    "undo",
    "accept",
    "otherRoom",
    "dismiss",
    "noGaps",
    "unmapped",
    "parseHint",
    "command",
    "analyze",
    "raw",
    "speech",
    "intent",
    "slots",
    "searchDevice",
    "alias",
    "room",
    "preferred",
    "save",
    "personality",
    "mode",
    "supportBundle",
    "recordProtocol",
    "includeRawText",
    "semanticAdapters",
    "downloadDataset",
    "downloadProtocol",
    "deleteSelected",
    "clearAll",
    "token",
    "customJson",
    "customHint",
    "addPhrase",
    "previewRule",
    "explainRule",
    "rollback",
    "noRules",
    "emptyBundle",
    "confirmApply",
    "cancel",
    "apply",
    "close",
    "low",
    "medium",
    "high",
    "source",
    "language",
    "time",
    "text",
    "answer",
    "graphHint",
    "resetLayout",
    "score",
    "noIntent",
    "loading",
    "nluRagHint",
    "confirmRisky",
    "languages",
    "languageSearch",
    "allLanguages",
    "noLanguageMatch",
    "languageHint",
    "mappingHint",
    "parseSample",
    "tryOn",
    "tryLock",
    "tryTime",
    "tryNight",
    "tryUndo",
    "tryRoom",
    "nluIgnore",
    "nluIgnoreHint",
    "savePhrase",
    "ignoreTarget",
    "teachSaved",
    "journal",
    "journalHint",
    "decisionMix",
    "mixCaption",
    "coverageCaption",
    "latency",
    "latencyCaption",
    "unitsTurns",
    "timeline",
    "noConversations",
    "when",
    "then",
    "priority",
    "evaluator",
    "bakeSpeech",
    "addRule",
    "noPolicies",
    "compiledRisk",
    "finalBand",
    "triggerFirst",
    "discarded",
    "stageTokens",
    "stageBind",
    "stageRank",
    "stagePolicy",
    "stageBand",
    "effectConfirm",
    "effectBlock",
    "effectAllow",
    "effectPreferEntity",
    "effectPreferArea",
    "effectReply",
    "effectScript",
    "effectTemplate",
    "effectLlm",
    "payloadReply",
    "payloadScript",
    "payloadTemplate",
    "payloadLlm",
    "whenPhrase",
    "chatMode",
    "variantPreview",
    "policies",
    "routines",
    "routineHint",
    "routinePhraseHint",
    "addRoutine",
    "noRoutines",
    "routineInvalid",
    "lastTurn",
    "heardIn",
    "tryThese",
    "tryTheseHint",
    "anyRoom",
    "personalityHa",
)


def expand(fields: dict[str, str]) -> dict[str, str]:
    out = {**CONSTANTS}
    for key in CATALOG_KEYS:
        out[key] = fields[key]
    for dest, src in ALIASES.items():
        out[dest] = out[src]
    return out
