"""Operator UI field map. Catalogs store unique chrome; expand() fills aliases."""

from __future__ import annotations

ALIASES = {
    "dashboard": "home",
    "parse": "lab",
    "houseGraph": "graph",
    "houseDevices": "entities",
    "houseMap": "calibrate",
    "matchedRule": "addRule",
    "ragMode": "nluRag",
    "sentences": "custom",
}

CONSTANTS = {
    "unitsPercent": "%",
    "entityId": "entity_id",
    "nluRag": "House context on miss",
    "processPath": "conversation.process",
    "advancedJson": "JSON",
    "unitsUs": "µs",
    "coverageGraph": "Graph",
    "coverageAssist": "Assist",
    "coverageReady": "ready",
    "coverageOpen": "open",
    "undoLastCommand": "Undo last command",
    "applyDone": "Applied {count} room suggestions",
    "applyUndone": "Room suggestions undone",
    "applyUndoFailed": "Could not undo room suggestions",
    "modeFull": "Resolve devices",
    "modeContext": "Rooms only",
    "engineHint": "Mode binds devices or rooms only. House context on a miss is optional.",
    "inLab": "In Lab",
    "operatorLanguage": "Operator language",
    "operatorLanguageHint": "This app only. Saved here, or KLAR_UI_LOCALE before the first save. Not Assist, not the Home Assistant profile.",
}

CATALOG_KEYS = (
    "home",
    "conversations",
    "rules",
    "house",
    "lab",
    "graph",
    "calibrate",
    "entities",
    "custom",
    "settings",
    "open",
    "bundleOn",
    "bundleOff",
    "engineReady",
    "understandsHome",
    "assistVisible",
    "certain",
    "needsWork",
    "recordings",
    "processed",
    "coverage",
    "confidence",
    "domains",
    "rooms",
    "recent",
    "replay",
    "applyAll",
    "undo",
    "accept",
    "otherRoom",
    "dismiss",
    "noGaps",
    "unmapped",
    "parseHint",
    "command",
    "analyze",
    "raw",
    "speech",
    "intent",
    "slots",
    "searchDevice",
    "alias",
    "room",
    "preferred",
    "save",
    "personality",
    "mode",
    "supportBundle",
    "recordProtocol",
    "includeRawText",
    "semanticAdapters",
    "downloadDataset",
    "downloadProtocol",
    "deleteSelected",
    "clearAll",
    "token",
    "customJson",
    "customHint",
    "addPhrase",
    "previewRule",
    "explainRule",
    "rollback",
    "noRules",
    "emptyBundle",
    "confirmApply",
    "cancel",
    "apply",
    "close",
    "low",
    "medium",
    "high",
    "source",
    "language",
    "time",
    "text",
    "answer",
    "graphHint",
    "resetLayout",
    "score",
    "noIntent",
    "loading",
    "nluRagHint",
    "confirmRisky",
    "languages",
    "languageSearch",
    "allLanguages",
    "noLanguageMatch",
    "languageHint",
    "mappingHint",
    "parseSample",
    "tryOn",
    "tryLock",
    "tryTime",
    "tryNight",
    "tryUndo",
    "tryRoom",
    "nluIgnore",
    "nluIgnoreHint",
    "savePhrase",
    "ignoreTarget",
    "teachSaved",
    "journal",
    "journalHint",
    "decisionMix",
    "mixCaption",
    "coverageCaption",
    "latency",
    "latencyCaption",
    "unitsTurns",
    "timeline",
    "noConversations",
    "when",
    "then",
    "priority",
    "evaluator",
    "bakeSpeech",
    "addRule",
    "noPolicies",
    "compiledRisk",
    "finalBand",
    "triggerFirst",
    "discarded",
    "stageTokens",
    "stageBind",
    "stageRank",
    "stagePolicy",
    "stageBand",
    "effectConfirm",
    "effectBlock",
    "effectAllow",
    "effectPreferEntity",
    "effectPreferArea",
    "effectReply",
    "effectScript",
    "effectTemplate",
    "effectLlm",
    "payloadReply",
    "payloadScript",
    "payloadTemplate",
    "payloadLlm",
    "whenPhrase",
    "chatMode",
    "variantPreview",
    "policies",
    "routines",
    "routineHint",
    "routinePhraseHint",
    "addRoutine",
    "noRoutines",
    "routineInvalid",
    "lastTurn",
    "heardIn",
    "tryThese",
    "tryTheseHint",
    "anyRoom",
    "personalityHa",
    "pathUnchecked",
    "pathMatch",
    "pathSeed",
    "pathHouse",
    "pathBand",
    "laneMatch",
    "laneLanguage",
    "laneHouse",
    "lexiconOverlay",
    "lexiconEmpty",
    "governSeed",
    "governEmpty",
    "matchCatalog",
    "matchReadOnly",
    "matchEnabled",
    "matchDisabled",
    "matchPrecedence",
    "matchDisableWarning",
    "lexiconPath",
    "lexiconToken",
    "lexiconAdd",
    "lexiconRemove",
    "originEngine",
    "originOperator",
    "originSeed",
    "originTrainer",
    "compiledFloor",
    "trainer",
    "trainerHint",
    "trainerContext",
    "trainerValidate",
    "trainerApply",
    "trainerProposal",
    "trainerOk",
    "trainerFail",
    "trainerSend",
    "trainerNeedLlm",
    "trainerOpenSettings",
    "trainerApplyHouse",
    "trainerApplyMatch",
    "trainerApplyLanguage",
    "trainerAdvanced",
    "trainerStreaming",
    "llm",
    "llmHint",
    "llmBaseUrl",
    "llmModel",
    "llmApiKey",
    "llmApiKeyHint",
    "llmPresetOpenAi",
    "llmPresetOllama",
    "llmConfigured",
    "llmNotConfigured",
    "llmClear",
    "seedOn",
    "seedOff",
)


# English fallbacks for operator-chrome keys not yet hand-translated in pack tables.
FALLBACKS = {
    "pathUnchecked": "—",
    "pathMatch": "Match",
    "pathSeed": "Seed",
    "pathHouse": "House",
    "pathBand": "Band",
    "laneMatch": "Match",
    "laneLanguage": "Language",
    "laneHouse": "House",
    "lexiconOverlay": "Lexicon overlay",
    "lexiconEmpty": "No lexicon overlay deltas.",
    "governSeed": "Govern seed",
    "governEmpty": "Safety seeds ship with every pack. Off writes a house override; the compiled floor stays on.",
    "matchCatalog": "Compiled matchers",
    "matchReadOnly": "Missing row uses the engine default. Empty overlay is today’s candidate list.",
    "matchEnabled": "On",
    "matchDisabled": "Off",
    "matchPrecedence": "Precedence",
    "matchDisableWarning": "Disabling area_command or all_lights changes room-wide and whole-home commands.",
    "lexiconPath": "Set path",
    "lexiconToken": "Token",
    "lexiconAdd": "Add",
    "lexiconRemove": "Remove",
    "originEngine": "engine",
    "originOperator": "operator",
    "originSeed": "seed",
    "originTrainer": "trainer",
    "compiledFloor": "compiled floor",
    "trainer": "Trainer",
    "trainerHint": "Klar calls an OpenAI-compatible model in Rust. Chat, validate, then apply per lane. No Home Assistant LLM integration is required. Advanced JSON is for debug.",
    "trainerContext": "Context",
    "trainerValidate": "Validate",
    "trainerApply": "Apply",
    "trainerProposal": "Proposal JSON",
    "trainerOk": "Valid",
    "trainerFail": "Invalid",
    "trainerSend": "Send",
    "trainerNeedLlm": "Configure an LLM in Settings first. Klar does not need another Home Assistant conversation integration.",
    "trainerOpenSettings": "Open Settings",
    "trainerApplyHouse": "Apply House",
    "trainerApplyMatch": "Apply Match",
    "trainerApplyLanguage": "Apply Language",
    "trainerAdvanced": "Advanced JSON",
    "trainerStreaming": "Streaming…",
    "llm": "LLM",
    "llmHint": "Klar talks to an OpenAI-compatible endpoint. Assist chat and the trainer use this same config. No Home Assistant OpenAI or Ollama integration is required.",
    "llmBaseUrl": "Base URL",
    "llmModel": "Model",
    "llmApiKey": "API key",
    "llmApiKeyHint": "Leave empty to keep the stored key. Ollama can stay empty.",
    "llmPresetOpenAi": "OpenAI",
    "llmPresetOllama": "Ollama",
    "llmConfigured": "Configured",
    "llmNotConfigured": "Not configured",
    "llmClear": "Clear",
    "seedOn": "On",
    "seedOff": "Off",
}


def expand(fields: dict[str, str]) -> dict[str, str]:
    out = {**CONSTANTS}
    for key in CATALOG_KEYS:
        out[key] = fields[key]
    for dest, src in ALIASES.items():
        out[dest] = out[src]
    return out
