"""Operator UI field map. Catalogs store unique chrome; expand() fills aliases."""

from __future__ import annotations

ALIASES = {
    "dashboard": "home",
    "parse": "lab",
    "houseGraph": "graph",
    "houseDevices": "entities",
    "houseMap": "calibrate",
    "matchedRule": "addRule",
    "ragMode": "nluRag",
    "sentences": "custom",
}

CONSTANTS = {
    "unitsPercent": "%",
    "entityId": "entity_id",
    "processPath": "conversation.process",
    "advancedJson": "JSON",
    "unitsUs": "µs",
    "coverageGraph": "Graph",
    "coverageAssist": "Assist",
    "coverageReady": "ready",
    "coverageOpen": "open",
}

CATALOG_KEYS = (
    "home",
    "conversations",
    "rules",
    "house",
    "lab",
    "graph",
    "calibrate",
    "entities",
    "custom",
    "settings",
    "open",
    "bundleOn",
    "bundleOff",
    "engineReady",
    "understandsHome",
    "assistVisible",
    "certain",
    "needsWork",
    "recordings",
    "processed",
    "coverage",
    "confidence",
    "domains",
    "rooms",
    "recent",
    "replay",
    "applyAll",
    "undo",
    "accept",
    "otherRoom",
    "dismiss",
    "noGaps",
    "unmapped",
    "parseHint",
    "command",
    "analyze",
    "raw",
    "speech",
    "intent",
    "slots",
    "searchDevice",
    "alias",
    "room",
    "preferred",
    "save",
    "personality",
    "mode",
    "modeFull",
    "modeContext",
    "supportBundle",
    "recordProtocol",
    "includeRawText",
    "semanticAdapters",
    "downloadDataset",
    "downloadProtocol",
    "deleteSelected",
    "clearAll",
    "token",
    "customJson",
    "customHint",
    "addPhrase",
    "previewRule",
    "explainRule",
    "rollback",
    "noRules",
    "emptyBundle",
    "confirmApply",
    "cancel",
    "apply",
    "close",
    "low",
    "medium",
    "high",
    "source",
    "language",
    "time",
    "text",
    "answer",
    "graphHint",
    "resetLayout",
    "score",
    "noIntent",
    "loading",
    "nluRag",
    "nluRagHint",
    "confirmRisky",
    "languages",
    "languageSearch",
    "allLanguages",
    "noLanguageMatch",
    "languageHint",
    "operatorLanguage",
    "operatorLanguageHint",
    "engineHint",
    "assistLanguages",
    "assistLanguagesHint",
    "allAssistLanguages",
    "pinLanguage",
    "voice",
    "voiceHint",
    "extraPrompt",
    "extraPromptHint",
    "refineSpeech",
    "refineSpeechHint",
    "quietAck",
    "quietAckHint",
    "calendarLlm",
    "calendarLlmHint",
    "allowLlmTools",
    "allowLlmToolsHint",
    "missTitle",
    "missHint",
    "operatorChrome",
    "operatorChromeHint",
    "haGlueHint",
    "settingsGuide",
    "settingsGuideVoice",
    "settingsGuideLlm",
    "settingsGuideLang",
    "appearanceDark",
    "appearanceLight",
    "setupReplay",
    "mappingHint",
    "parseSample",
    "tryOn",
    "tryLock",
    "tryTime",
    "tryNight",
    "tryUndo",
    "tryRoom",
    "nluIgnore",
    "nluIgnoreHint",
    "savePhrase",
    "ignoreTarget",
    "teachSaved",
    "journal",
    "journalHint",
    "decisionMix",
    "mixCaption",
    "coverageCaption",
    "latency",
    "latencyCaption",
    "unitsTurns",
    "timeline",
    "noConversations",
    "when",
    "then",
    "priority",
    "evaluator",
    "bakeSpeech",
    "addRule",
    "noPolicies",
    "compiledRisk",
    "finalBand",
    "triggerFirst",
    "discarded",
    "stageTokens",
    "stageBind",
    "stageRank",
    "stagePolicy",
    "stageBand",
    "effectConfirm",
    "effectBlock",
    "effectAllow",
    "effectPreferEntity",
    "effectPreferArea",
    "effectReply",
    "effectScript",
    "effectTemplate",
    "effectLlm",
    "payloadReply",
    "payloadScript",
    "payloadTemplate",
    "payloadLlm",
    "whenPhrase",
    "chatMode",
    "variantPreview",
    "policies",
    "routines",
    "routineHint",
    "routinePhraseHint",
    "addRoutine",
    "noRoutines",
    "routineInvalid",
    "lastTurn",
    "heardIn",
    "tryThese",
    "tryTheseHint",
    "anyRoom",
    "inLab",
    "undoLastCommand",
    "applyDone",
    "applyUndone",
    "applyUndoFailed",
    "personalityHa",
    "personalityDefault",
    "personalityButler",
    "personalityLocker",
    "personalityFuersorglich",
    "personalityParty",
    "personalityGrantig",
    "personalitySarkastisch",
    "personalityPirat",
    "personalityHippie",
    "personalityGollum",
    "personalityJarvis",
    "pathUnchecked",
    "pathMatch",
    "pathSeed",
    "pathHouse",
    "pathBand",
    "laneMatch",
    "laneMatchEngine",
    "laneLanguage",
    "laneHouse",
    "laneTabs",
    "lexiconOverlay",
    "lexiconOverlayPlus",
    "lexiconEmpty",
    "governSeed",
    "governEmpty",
    "matchCatalog",
    "matchReadOnly",
    "matchEnabled",
    "matchDisabled",
    "matchPrecedence",
    "matchDisableWarning",
    "lexiconPath",
    "lexiconToken",
    "lexiconAdd",
    "lexiconRemove",
    "originEngine",
    "originOperator",
    "originSeed",
    "originTrainer",
    "compiledFloor",
    "trainer",
    "trainerForLane",
    "trainerHint",
    "trainerContext",
    "trainerValidate",
    "trainerApply",
    "trainerProposal",
    "trainerOk",
    "trainerFail",
    "trainerSend",
    "trainerNeedLlm",
    "trainerOpenSettings",
    "trainerApplyHouse",
    "trainerApplyMatch",
    "trainerApplyLanguage",
    "trainerAdvanced",
    "trainerStreaming",
    "llm",
    "llmHint",
    "llmBaseUrl",
    "llmModel",
    "llmApiKey",
    "llmApiKeyHint",
    "llmPresetOpenAi",
    "llmPresetOllama",
    "llmConfigured",
    "llmNotConfigured",
    "llmClear",
    "seedOn",
    "seedOff",
)


# English fallbacks for operator-chrome keys not yet hand-translated in pack tables.
FALLBACKS = {
    "pathUnchecked": "—",
    "pathMatch": "Match",
    "pathSeed": "Seed",
    "pathHouse": "House",
    "pathBand": "Band",
    "laneMatch": "Match",
    "laneMatchEngine": "Match (Engine)",
    "laneLanguage": "Language",
    "laneHouse": "House",
    "laneTabs": "Lanes",
    "lexiconOverlay": "Lexicon overlay",
    "lexiconOverlayPlus": "Lexicon overlay +{count}",
    "lexiconEmpty": "No lexicon overlay deltas.",
    "governSeed": "Govern seed",
    "governEmpty": "Safety seeds ship with every pack. Off writes a house override; the compiled floor stays on.",
    "matchCatalog": "Compiled matchers",
    "matchReadOnly": "Missing row uses the engine default. Empty overlay is today’s candidate list.",
    "matchEnabled": "On",
    "matchDisabled": "Off",
    "matchPrecedence": "Precedence",
    "matchDisableWarning": "Disabling area_command or all_lights changes room-wide and whole-home commands.",
    "lexiconPath": "Set path",
    "lexiconToken": "Token",
    "lexiconAdd": "Add",
    "lexiconRemove": "Remove",
    "originEngine": "engine",
    "originOperator": "operator",
    "originSeed": "seed",
    "originTrainer": "trainer",
    "compiledFloor": "compiled floor",
    "trainer": "Trainer",
    "trainerForLane": "Trainer for this lane",
    "trainerHint": "Klar calls an OpenAI-compatible model in Rust. Chat, validate, then apply per lane. No Home Assistant LLM integration is required. Advanced JSON is for debug.",
    "trainerContext": "Context",
    "trainerValidate": "Validate",
    "trainerApply": "Apply",
    "trainerProposal": "Proposal JSON",
    "trainerOk": "Valid",
    "trainerFail": "Invalid",
    "trainerSend": "Send",
    "trainerNeedLlm": "Configure an LLM in Settings first. Klar does not need another Home Assistant conversation integration.",
    "trainerOpenSettings": "Open Settings",
    "trainerApplyHouse": "Apply House",
    "trainerApplyMatch": "Apply Match",
    "trainerApplyLanguage": "Apply Language",
    "trainerAdvanced": "Advanced JSON",
    "trainerStreaming": "Streaming…",
    "llm": "LLM",
    "llmHint": "Klar talks to an OpenAI-compatible endpoint. Assist chat and the trainer use this same config. No Home Assistant OpenAI or Ollama integration is required.",
    "llmBaseUrl": "Base URL",
    "llmModel": "Model",
    "llmApiKey": "API key",
    "llmApiKeyHint": "Leave empty to keep the stored key. Ollama can stay empty.",
    "llmPresetOpenAi": "OpenAI",
    "llmPresetOllama": "Ollama",
    "llmConfigured": "Configured",
    "llmNotConfigured": "Not configured",
    "llmClear": "Clear",
    "seedOn": "On",
    "seedOff": "Off",
    "nluRag": "House context on miss",
    "operatorLanguage": "Operator language",
    "operatorLanguageHint": "This app only. Saved here, or KLAR_UI_LOCALE before the first save. Not Assist, not the Home Assistant profile.",
    "modeFull": "Resolve devices",
    "modeContext": "Rooms only",
    "inLab": "In Lab",
    "undoLastCommand": "Undo last command",
    "applyDone": "Applied {count} room suggestions",
    "applyUndone": "Room suggestions undone",
    "applyUndoFailed": "Could not undo room suggestions",
    "languageHint": "Empty list keeps every compiled Assist locale. Pinning one pack is the usual household.",
    "personalityHa": "Voice, languages, and the LLM live on this Settings page.",
    "engineHint": "Voice, languages, and the LLM live here. Home Assistant only connects the engine.",
    "assistLanguages": "Assist languages",
    "assistLanguagesHint": "Which packs Klar may parse. The satellite still sends one language per request. Empty = all compiled locales.",
    "allAssistLanguages": "Every compiled locale",
    "pinLanguage": "Pin one pack",
    "voice": "Voice",
    "voiceHint": "Personality and spoken replies. Assist reads this from the engine, not from Home Assistant options.",
    "extraPrompt": "Extra prompt",
    "extraPromptHint": "Optional line on top of the packed personality. Leave empty unless you need a house-specific rule.",
    "refineSpeech": "LLM refine",
    "refineSpeechHint": "Klar still controls devices. The engine LLM then rewrites finished NLU replies in this voice.",
    "quietAck": "Short confirmation",
    "quietAckHint": "On a simple light or switch on/off, skip TTS and play a chime on the satellite.",
    "calendarLlm": "Calendar through the LLM",
    "calendarLlmHint": "Klar still reads the calendar. On: the LLM speaks the events. Off: Klar speaks the list.",
    "allowLlmTools": "Allow Assist tools on chat",
    "allowLlmToolsHint": "Off by default. On: the chat model may control Home Assistant. Off: Klar skips that agent when it has tools.",
    "missTitle": "When Klar misses",
    "missHint": "Optional layers after a deterministic reject. None of these put a model on parse.",
    "operatorChrome": "This screen",
    "operatorChromeHint": "Theme and chrome language for operators. Not Assist.",
    "haGlueHint": "Home Assistant Configure only needs engine URL, token, channel, and an optional leftover conversation agent. Voice and LLM stay here.",
    "settingsGuide": "Set these three, then map the house.",
    "settingsGuideVoice": "Voice",
    "settingsGuideLlm": "LLM",
    "settingsGuideLang": "Assist language",
    "appearanceDark": "Dark",
    "appearanceLight": "Light",
    "setupReplay": "Replay setup",
    "personalityDefault": "Normal",
    "personalityButler": "Butler",
    "personalityLocker": "Casual",
    "personalityFuersorglich": "Caring",
    "personalityParty": "Party",
    "personalityGrantig": "Grumpy",
    "personalitySarkastisch": "Sarcastic",
    "personalityPirat": "Pirate",
    "personalityHippie": "Hippie",
    "personalityGollum": "Gollum",
    "personalityJarvis": "Jarvis",
}


def expand(fields: dict[str, str]) -> dict[str, str]:
    out = {**CONSTANTS}
    for key in CATALOG_KEYS:
        out[key] = fields[key]
    for dest, src in ALIASES.items():
        out[dest] = out[src]
    return out
